### ISSUE TITLE
Slack integration uses old API/Token method

### ISSUE THREAD

**Issue by law** [opsdroid/opsdroid#1000]
# Description
Opsdroid's Slack integration wants to operate off of a Webhook or API Token, which seems to be a deprecating (not yet deprecated) method of integrating with Slack.  See attached screenshot of the warning message they display when trying to do a 'Webhook' or generic 'Bot' integration in an Enterprise Slack instance.  

## Steps to Reproduce
Try to set up a 'Webhook' or 'API/Bot' integration in the usual manner: 
Menu -> Customize Slack -> Configure Apps -> Custom Integrations

Observe Slack's notice that "Custom integrations will be deprecated and possibly removed in the future.  Learn more about replacing them with apps that have more features and use the latest APIs" 

## Expected Functionality
Ideally, Opsdroid would be able to integrate with Slack using their shiny Apps/not-Webhook API, and I don't have to go through a Security Team review because of the deprecation warning :-) 

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:** latest
- **Python version:** 3.2
- **OS/Docker version:** latest

## Configuration File
n/a

## Additional Details

[Custom Integration warning](https://i.imgur.com/fWWFXHw.png)

**Comment by jacobtomlinson** [comment]
This may be resolved with #1036

**Comment by jacobtomlinson** [comment]
The documentation is still outdated. Sorry this got closed as stale.
