### ISSUE TITLE
Unable to send message to connector from a crontab skill

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1001]
I am still trying to debug the slack connector, I created a silly skill that would log the date of each day just to make it easier to divide the logs. 
I've also noticed that some of my skills that use cron aren't sending messages to a connector.

I tried to send a test message to the connector every minute but it didn't work.

This is the log:
```python
DEBUG opsdroid.parsers.crontab: Running crontab skills at Sat Jul  6 12:21:00 2019 
ERROR opsdroid.core: Exception when running skill 'warning' 
Traceback (most recent call last):
  File "/home/fabiorosado/Github/opsdroid/opsdroid/connector/websocket/__init__.py", line 125, in send_message
    message.target = next(iter(self.active_connections))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fabiorosado/Github/opsdroid/opsdroid/core.py", line 361, in run_skill
    await skill(message)
  File "/root/.local/share/opsdroid/opsdroid-modules/skill/warning/__init__.py", line 26, in ring_warning
    await message.respond("test")
  File "/home/fabiorosado/Github/opsdroid/opsdroid/events.py", line 204, in respond
    return await super().respond(response)
  File "/home/fabiorosado/Github/opsdroid/opsdroid/events.py", line 109, in respond
    await opsdroid.send(event)
  File "/home/fabiorosado/Github/opsdroid/opsdroid/core.py", line 500, in send
    return await event.connector.send(event)
  File "/home/fabiorosado/Github/opsdroid/opsdroid/connector/__init__.py", line 206, in send
    return await self.events[type(event)](self, event)
RuntimeError: coroutine raised StopIteration
```

This is the skill:

```python
import logging
import psutil
import datetime

from opsdroid.skill import Skill
from opsdroid.matchers import match_crontab
from opsdroid.events import Message

_LOGGER = logging.getLogger(__name__)

class Warning(Skill):
    def __init__(self, opsdroid, config):
        super(Warning, self).__init__(opsdroid, config)
        self.opsdroid = opsdroid
        self.config = config
    
    @match_crontab("* * * * *", timezone="Europe/London")
    async def ring_warning(self, message):
        mem = psutil.virtual_memory()
        ram_usage = mem.percent

        connector = self.opsdroid.default_connector
        room = connector.default_target
        message = Message("", None, room, connector)

        await message.respond("test")

        if mem.percent > 70:
            _LOGGER.warning("Memory usage is higher than 70%!")
            await message.respond("Warning! Mem usage is higher than 70%")
```

**Comment by jacobtomlinson** [comment]
This looks like a problem with the way that the websocket connector is getting the default target.

A quick look at the code makes me think that the websocket connector doesn't implement the default connector which results in a default of `None`. Then [there appears to be a check](https://github.com/opsdroid/opsdroid/blob/8b252588aeb2f7bfcfda01845b5c9c985c2b19a8/opsdroid/connector/websocket/__init__.py#L124) for the target being `None` in the send method which tried to iterate over the active connections. I expect this is intended to just send the message to the first connection.

None of this logic feels ideal. 

For now I recommend possibly using a different connector or trying to more explicitly figure out your connection target in the skill and point it to that.

Do you have thoughts on where default target messages should go in the websocket connector?

**Comment by FabioRosado** [comment]
I'll just try to get the right place to send the message within the skill itself since I just need to add the target.

As for where the default target messages, I'm not entirely sure. If we get any information about the connectors that are currently using websockets we could add a param to set it as default or just use the first one 🤔
