### ISSUE TITLE
Update example config script

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1019]
Our `configuration.yaml` file has suffered a few alterations and the script that should update the `example_configuration.yaml` file is really out of date. 

There are also a few bugs where the skill is added both to commented ones and active ones.

We should update this script in order to get out configuration files up to date. We should also update the `example_configuration.yaml` file.

**Comment by bistaastha** [comment]
Hi
Can I work on this issue?

**Comment by FabioRosado** [comment]
Hello! That would be awesome!

Please let me know if you need any help whilst working on this issue 😄👍

**Comment by bistaastha** [comment]
Hi
I went through the `example_config.yaml` and the corresponding script that updates it, and I don't understand what needs to be updated.

**Comment by FabioRosado** [comment]
Hello @bistaastha  Apologies for not replying to you sooner. 
You will need to do a few things to fix this issue:

1.  Update the script to remove the connectors/databases that have been included in the core
2. Make sure that the connectors/databases that have been included into core are shown in the example_config.yaml
3. Update the script to not include duplicate things - sometimes it would leave commented out skills and letter would show them commented as well
4. Update the example_config with the latest version.

I hope this made things more clear?

**Comment by bistaastha** [comment]
Yes, it does. Thank you :)

**Comment by bistaastha** [comment]
Hi.
I'm editing the example_config.yaml right now. There are skills which are both commented out and active. Which part has to be kept?

**Comment by FabioRosado** [comment]
The default connectors/skills that should remain uncommented are:
connectors: websockets
skills: dance, hello, loudnoises, seen

All the others should remain commented out. Hope this helps

**Comment by bistaastha** [comment]
Actually loudnoises and seen were commented as well as uncommented.
Thanks, this helps.

**Comment by sagardubey3** [comment]
Hi @bistaastha ,
I was going through the conversation.are you still working on the same?
I was thinking about helping out so let  me know if you need my help.

**Comment by FabioRosado** [comment]
Since we haven't got any PR being raised in regards to this issue I am going to say that this issue is still open and we are accepting PR's to fix this 😄

**Comment by jos3p** [comment]
Hello,
can I take this issue?

**Comment by jacobtomlinson** [comment]
Sure @jos3p!

**Comment by endersonmenezes** [comment]
> Hello,
> can I take this issue?

Hello @jos3p if you are not working on this issue I would like to try, can you update me where you left off, or need help?

**Comment by jos3p** [comment]
I'm still on it, will post a pullrequest soon
