### ISSUE TITLE
Migrate to slackapi/python-slackclient 

### ISSUE THREAD

**Issue by n8felton** [opsdroid/opsdroid#1036]
# Description
With v2, the [python-slackclient library](https://github.com/slackapi/python-slackclient) provided by Slack now supports asyncio natively (https://github.com/slackapi/python-slackclient/blob/add2757ce7ce688ba45355079bafa911a9b61ea5/README.md#async-usage). 

I wanted to mention this in case there was any benefit to migrating to using the Slack-provided library. It may be easier to support new Slack features faster with this library, as well as add support for the RTM API.

**Comment by FabioRosado** [comment]
Since we are having a memory leak with the slack connector it might be a good idea to think about replacing the connector to use the slack provided lib 🤔

**Comment by jacobtomlinson** [comment]
This sounds good to me. Let's do it!

**Comment by FabioRosado** [comment]
I had a quick read through the clients and the official documentation. It seems they have two different clients:

-  Slack Web API and Real Time Messaging (RTM) API
- Slack Events API 

For what I gathered it seems that the RTM api is the one we been using on the connector and looks like they still using token based authentication. 

In #1000 is mentioned that the token based authentication will be deprecated, so I checked the migration documentation and it seems they will use token based authentication.

With this in mind the big new shiny things is the events and app based integrations so perhaps we should migrate to start using the app based integration when working on this issue. 

The only downside of the app based integration is that on free workspaces you can only install a certain number of apps.

So yeah should we just use the events client?
