### ISSUE TITLE
Issue with pyyaml schema validation

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1055]
# Description

I'm working on the upgrade for dialogflow and usually use Telegram to test opsdroid. Opsdroid didn't start due to pyyaml validation issues. It seems that for some reason the validation is asking to use all the options on the other connectors - the log should make more sense.

I'm going to assume that since we are saying that these options are optional, the validating code is complaining?

@kollyuchka do you have any idea why this is happening?

## Steps to Reproduce
Use latest dev version, set up a connector, start opsdroid, fails to load

## Expected Functionality
Opsdroid should start without any issues.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

```shell
python -m opsdroid

Error validating data /Users/fabiorosado/Library/Application Support/opsdroid/configuration.yaml with schema /Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/configuration/schema.yaml
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.webhook-url: Required field missing
	connectors.1.access-token: Required field missing
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.verify-token: Required field missing
	connectors.1.page-access-token: Required field missing
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.mxid: Required field missing
	connectors.1.password: Required field missing
	connectors.1.room: Required field missing
	connectors.1.rooms: Required field missing
	connectors.1.homeserver: Required field missing
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.api-token: Required field missing
	connectors.1.whitelisted_users: Required field missing
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.consumer_key: Required field missing
	connectors.1.consumer_secret: Required field missing
	connectors.1.oauth_token: Required field missing
	connectors.1.oauth_token_secret: Required field missing
	connectors.1.name: 'Telegram' is not a regex match.
	connectors.1.room-id: Required field missing
	connectors.1.access-token: Required field missing
```

## Versions
- **Opsdroid version:** opsdroid dev
- **Python version:** 3.7
- **OS/Docker version:** macos

## Configuration File
Please include your version of the configuration file bellow.

```yaml
connectors:
   - name: Telegram
      token: <api token>
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
Should it be `telegram` with a lowercase t?

**Comment by kollyuchka** [comment]
Hello. My examples of configs:
`welcome-message: true

connectors:

  - name: Telegram
    token: "811186170:AAEKCnmBg89g9Q7mZIrO0JQLtLjXgVSmALA"  
    update_interval: 0.5
    default_user: user1
    whitelisted_users:
      - user1
      - user2

skills:

  - name: dance
  - name: hello
`

**Comment by kollyuchka** [comment]
`welcome-message: true

connectors:

  - name: Telegram
    token: "811186170:AAEKCnmBg89g9Q7mZIrO0JQLtLjXgVSmALA"  
    update_interval: 0.5
    default_user: user1
    whitelisted_users:
      - user1
      - user2

skills:

  - name: dance
  - name: hello
`

**Comment by FabioRosado** [comment]
I've tried with lowercase as well and got the same error, unless the schema is setting all the optional configs of the connector as required?

**Comment by kollyuchka** [comment]
Hello. My example config:
```
welcome-message: true

connectors:

  - name: Telegram
    token: <api token>
    update_interval: 0.5
    default_user: user1
    whitelisted_users:
      - user1
      - user2

skills:

  - name: dance
  - name: hello

**Comment by kollyuchka** [comment]
Both options work with a lower case letter and without.

**Comment by FabioRosado** [comment]
just out of curiosity did you set token, update_interval, default_user and whitelisted_users as required in the schema? 🤔

**Comment by goruha** [comment]
@FabioRosado can you try with the following config?

```
connectors:
  - name: Telegram
    token: <api token>
```

**Comment by kollyuchka** [comment]
@FabioRosado
Can you review PR ?
Because whitelisted_users field was required, an error occurred.

**Comment by jacobtomlinson** [comment]
I've merged the PR. Thanks!

@FabioRosado could you test that things are ok for you now and then reclose this?

**Comment by FabioRosado** [comment]
Can confirm that this issue has been resolved thanks for working on it 👍
