### ISSUE TITLE
Expand maintenance team

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1077]
As the third and fourth biggest contributors to opsdroid and active members of the community I would love to extend and invitation to @Cadair and @SolarDrew to join the @opsdroid/maintainers team.

![image](https://user-images.githubusercontent.com/1610850/65587364-a3970400-df7d-11e9-9951-4880cf04954a.png)

You are both very fimilar with the internals of the project due to your awesome work on #721, #826, and of course the matrix connector. You have also been great at engaging in discussion and reviewing other contributions (mainly mine).

I would love you to be more involved in steering the direction of the project and for you to be able to iterate faster on your own PRs by being able to merge each others contributions.

**Comment by Cadair** [comment]
Thanks @jacobtomlinson I would be very happy to join the maintainers, opsdroid is a great project :smile:

**Comment by SolarDrew** [comment]
Agreed, thanks very much :D

**Comment by jacobtomlinson** [comment]
Awesome! Invitations have been sent.
