### ISSUE TITLE
Hacktoberfest 2019 - Documentation Drive

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1078]
We are nearly at [hacktoberfest](https://hacktoberfest.digitalocean.com/) time again! This year I propose we focus our efforts on documentation and stability.

There are some tasks which should be done this week:
- [x] Get a release out to put a pin in things before hacktoberfest
- [x] Create the `hacktoberfest` label
- [x] Label up existing issues we want to highlight
- [x] Write a blog post announcing our involvement in hacktoberfest
- [x] Raise a load of nicely written issues for participants

In terms of improving the documentation, there are a bunch of things I'd like to look at. I'll start raising issues for these shortly.

- Revisit the structure of the documentation. I think we could lay it out better.
- Improve the docs theme to more closely match https://opsdroid.dev
- Update links to the documentation (https://docs.opsdroid.dev)
- Add more tutorials/examples (this is going to be the main effort)

As for stability, it would be great to do a push on all the bugs raised. Hopefully encouraging people to write tutorials/examples will highlight more.

**Comment by Cadair** [comment]
What are peoples opinions on changing the way the documentation is built to include api documentation. I think this is more relevant now we have things like the Events classes which has raised the amount of API surface area we are exposing to skill writers quite considerably?

I know I was finding myself looking at the source code for reference when using the Events classes in Picard, so I would assume others would need that info as well.

**Comment by jacobtomlinson** [comment]
Yup sounds good to me. How do you propose we do that?

**Comment by Cadair** [comment]
The most common tool for that is sphinx, but that comes with a whole load of other baggage. I certainly would be willing to set that up (I may have done it just a few times before). How attached to markdown as the language are you?! :grin:

**Comment by jacobtomlinson** [comment]
I'm pretty attached to markdown. I find rst pretty unpleasant to write, it's a necessary evil in Python docstrings sadly.

You can use sphinx with markdown though right?

**Comment by Cadair** [comment]
> I'm pretty attached to markdown.

I thought you might say that :grin: 

There are extensions which let you do it, it's something I can certainly look into.

**Comment by FabioRosado** [comment]
This sounds good. Since there was talks about i11n on matrix we should perhaps add translation of opsdroid to the list and also convert all logs and messages to include the `_()` pattern - i know I had failed to follow this convention a few times mostly because I forgot :/

The translated files are also out of date and we should update them as well adding other languages.

I agree that more examples would be brilliant and a great way to do things. It would be good to organise the documentation better like you suggested Jacob
