### ISSUE TITLE
All events should take both "user" and "user_id"

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1082]
Currently the base [`Event` class](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/events.py#L103) takes a `user=` parameter to it's constructor. This is generally implemented as the human readable name of the user. For a number of events we also need the machine readable user id for the event. 

I propose that we add `user_id=` to the event base class and all subclasses, and in all places connectors create events. This will allow us to provide a standard way of using one or the other for the event types that need one or both.

**Comment by dLaMothe** [comment]
I'll take a look at this one if that works.

**Comment by Cadair** [comment]
@dLaMothe sounds great :)

**Comment by dLaMothe** [comment]
Looks like I was a little slow. I'll let @himanshupathak21061998 take over on this one.
