### ISSUE TITLE
Replace references to the Gitter room with matrix

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1084]
The matrix channel appears to have been more active than the gitter channel recently, should we replace links and stuff everywhere with the matrix channel, or link to both?

**Comment by jacobtomlinson** [comment]
You're right about that. I'm keen to just link everyone to the Riot web app.

**Comment by FabioRosado** [comment]
Yeah I think we should move to the Riot web app. We might need to update the documentation with how to join the room, at least I remember that I had to figure out how to join haha

**Comment by jacobtomlinson** [comment]
For anyone who wants to tackle this issue [here is a search](https://github.com/opsdroid/opsdroid/search?q=%22gitter.im%2Fopsdroid%22&unscoped_q=%22gitter.im%2Fopsdroid%22) for all the references to the gitter chat room in this repo.

Links to the general room need to be updated to [this Riot/Matrix room](https://riot.im/app/#/room/#opsdroid-general:matrix.org). And links to the developers room needs to be updated to [this one](https://riot.im/app/#/room/#opsdroid-developer:matrix.org).

**Comment by jacobtomlinson** [comment]
Also see opsdroid/opsdroid.github.io#38

**Comment by rafaeelaudibert** [comment]
I can tackle this issue altogether with https://github.com/opsdroid/opsdroid.github.io/issues/38.
Is it okay for you?

**Comment by FabioRosado** [comment]
Hello Rafael thank you for showing interest on this issue. It seems you have shown interest in different issues, I'd say take on one and then try to do the other ones.

Also this issue is marked as a beginner level
