### ISSUE TITLE
Meta contraints

### ISSUE THREAD

**Issue by SolarDrew** [opsdroid/opsdroid#1086]
@Cadair and I were just chatting about how best to combine constraints, given the conversation in #1083 about using multiples. What we came up with is that we could have `@constrain_all` and `@constrain_any` decorators. Without arguments, these could apply `and` and `or respectively to all other constraint decorators specified on the skill, or you could optionally pass them decorators to only apply to those particular constraints. For example:

```python
@constrain_all
@some_constraint
@some_other_constraint
def my_skill():
    """Runs only if some_constraint and some_other_constraint are both met"""


@constrain_any
@some_constraint
@some_other_constraint
def my_skill():
    """Runs if either of some_constraint or some_other_constraint is met"""


@constrain_all(some_constraint, some_other_constraint)
@some_third_constraint
def my_skill():
    """Runs if some_constraint and some_other_constraint are both met, or if some_third_constraint is."""
```

The final example assumes that `or` is the default behaviour for multiple constraints (i.e. that `@constrain_any` is implied) - I can't remember what constraints do at the moment.

Thoughts welcome.

**Comment by jacobtomlinson** [comment]
Yeah I've thought about something similar in the past. My worry here is that we are reinventing control flow logic in decorators. It feels like it could be taken too far. 

Decorators like `constrain_users` could be also implemented within the skill. Check whether the event user is in a list and if not return and short circuit the skill. This would have the added benefit that the list of users could be loaded from the config, which we don't have access to when using the decorators. 

The decorators are more for convenience than anything else and my current position would be that advanced logic should be implemented within the skill. 

Happy to further discuss though!
