### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1091]
I think we need to restructure our documentation to make it a little friendlier to new users. I think we need to put more emphasis on skills than connectors and databases as it is more likely that people will be building skills.

I also think we should put a lot of effort into an examples section which would provide people with a rich copy-paste pool to draw from when writing their own skills. I'm tempted to suggest that we start by taking all of the skills that already exist in the opsdroid repo and writing them up in the documentation. From looking at the GitHub insights many of them have not been installed for a long time if ever, so we may even want to remove them. They were only ever intended to be examples anyway so perhaps they would be better off in the docs.

I would also love to add more visibility to matchers, constraints and events, and clear up the difference between matchers and parsers (as laid out in #693). 

Thoughts would be appreciated.

**Comment by jacobtomlinson** [comment]
I would still like this to be tackled regardless of hacktoberfest to pinning as an `enhancement`.

**Comment by daniccan** [comment]
I would like to help with this. Where do I start?

**Comment by jacobtomlinson** [comment]
Thanks for the offer @daniccan. I think this may actually be done as of #1265.

You can find the new docs here https://docs.opsdroid.dev/en/latest/index.html.

If you are looking to contribute to the documentation I would really appreciate some help on #1198.
