### ISSUE TITLE
Remove function skill deprecation warning

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1093]
A while back we added class based skills and added a deprecation warning to function based skills.

In hindsight we probably don't want to deprecate function based skills as they can still be useful and easier for a beginner to get on with.

So let's remove [this deprecation warning](https://github.com/opsdroid/opsdroid/blob/96477f218d4b900746bc868956caa53d1b862c76/opsdroid/core.py#L259).

**Comment by rafaeelaudibert** [comment]
I can certainly do that to get used to the code, as I'm a beginner to the project (as well as to count towards my PR's for Hacktoberfest).

If possible, will contribute with another PR as well, for some other issue.

**Comment by vgangaprasad** [comment]
Hi Jacob, 

I did the changes and trying to push but getting 403 access denied message, do i have to add myself in contributor list or something?

Thanks,
Vijay

**Comment by jacobtomlinson** [comment]
Thanks @vgangaprasad, you need to raise a Pull Request from your own fork. 

https://help.github.com/en/articles/creating-a-pull-request
