### ISSUE TITLE
!include constructor is broken on python 3.6

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1113]
# Description

After adding pyyaml validation, the `!include` constructor stopped working. I am still unsure if the issue is due to yamale and how it handles nested yaml files.

We need to fix the include constructor so we can keep the functionality of including a yaml file inside another.

## Steps to Reproduce
Add [skill-chat](https://github.com/FabioRosado/skill-chat) to opsdroid
set up skill-chat with a costumised yaml - follow the readme
start opsdroid

## Expected Functionality
Opsdroid should be able to include the custom file inside the configuration

## Experienced Functionality
```
python -m opsdroid start
could not determine a constructor for the tag '!include'
  in "/Users/fabiorosado/Library/Application Support/opsdroid/configuration.yaml", line 130, column 16
```

## Versions
- **Opsdroid version:**
- **Python version:**
- **OS/Docker version:**

## Configuration File
Please include your version of the configuration file bellow.

```yaml
Skills:
  - name: chat
    path: /Users/fabiorosado/Documents/GitHub/skill-chat
    customise: !include customise.yaml

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
Does anyone actually use the include functionality? I use the env var one all the time, but never this one.

Maybe we should consider just removing it?

**Comment by FabioRosado** [comment]
I don't really use it to be honest. I think we added the include constructor because we wanted to allow users to use it like how homeassistant does 🤔

**Comment by jacobtomlinson** [comment]
Yeah. I say let's remove it. If anyone complains then we can always re-instate it.

**Comment by FabioRosado** [comment]
I've tried a few things based on @ MrNaif2018 PR and everything seems to work fine - the coverage gets bumped up to 100% as well it seems so perhaps we can get the PR merged and leave it until it breaks for good? 😄

**Comment by jacobtomlinson** [comment]
Ok sure. If both the `!include` and `!envvar` constructors work and test coverage is up then I'm happy. I'll leave it to you!
