### ISSUE TITLE
Documentation Cleanup

### ISSUE THREAD

**Issue by butuzov** [opsdroid/opsdroid#1120]
# Description
There are a lot of links broken in documentation. I have  fix it! (or maybe made it worse!)

## Steps to Reproduce
I have used my tool `deadlinks` (in dev), but I guess you can use any link checker.

```bash
deadlinks https://docs.opsdroid.dev/en/stable/ -n 10 -s failed -r 2 -e \
    -p "master/docs" \
    -d opencollective.com
```
Stats: Found 157; Not Found 18; Ignored 65
* https://docs.opsdroid.dev/en/stable/tutorials/matchers/recast.ai.md - 404
* https://rasahq.github.io/rasa_nlu/dataformat.html - 404
* https://docs.opsdroid.dev/docs/contributing.md - 404
* https://rasahq.github.io/rasa_nlu - 404
* https://docs.opsdroid.dev/en/stable/tutorials/introduction.md - 404
* https://docs.opsdroid.dev/events.md - 404
* https://docs.opsdroid.dev/en/stable/contributing/graphs/contributors - 404
* https://docs.opsdroid.dev/en/stable/configuration-reference.md - 404
* https://docs.opsdroid.dev/en/stable/tutorials/docs/extending/skills - 404
* https://docs.opsdroid.dev/en/stable/graphs/contributors - 404
* https://docs.opsdroid.dev/en/opsdroid/configuration/example_configuration.yaml - 404
* https://docs.opsdroid.dev/en/stable/parsers/webhook - 404
* https://docs.opsdroid.dev/en/stable/maintainers/PULL_REQUEST_TEMPLATE.md - 404
* https://docs.opsdroid.dev/en/stable/tutorials - 404
* https://docs.opsdroid.dev/en/stable/extending/skills/tutorials/introduction.md - 404

in the list above result:
- False positives removed.
- Somehow `mkdocs build --clean --site-dir build/docs/html --theme readthedocs` had generate additional 404 in case of slash starting link (something like `/connectors/fasebook.md` ). I have changed that in my PR , so there won't be a problem in the future.

After additional manual changes, running against the local site. 
```bash
deadlinks http://localhost:8080/ -n 10 -s failed -r 2 -e \ 
 -d redis.io -d telegram.org -d codecov.io -d opencollective.com  -p "master/docs"
URL=<http://localhost:8080>; External Cheks=On; Threads=10; Retry=2
Stats: Found 161; Not Found 2; Ignored 69
```
Ones that left.

* http://localhost:8080/contributing/tutorials - 404
* http://localhost:8080/events.md - 404

**Comment by butuzov** [comment]
1) somehow, index pages not available in docs... so link 1 skipped.
2) haven't found events.md, not sure about history of this link/page.

**Comment by jacobtomlinson** [comment]
Thanks for raising this!

The [events page is here](https://github.com/opsdroid/opsdroid/blob/master/docs/extending/events.md).

**Comment by jacobtomlinson** [comment]
Reopening as not all links fixed in #1121.

**Comment by butuzov** [comment]
Hi Jacob. Somehow, few more errors ware added. 

```
 deadlinks http://localhost:8080/ -n 10 -s failed -r 2 -e -d redis.io -d telegram.org -d codecov.io -d opencollective.com  -p "master/docs"
URL=<http://localhost:8080>; External Cheks=On; Threads=10; Retry=2
Stats:
Found 161; Not Found 5; Ignored 69
[ failed ] http://localhost:8080/events.md - 404
[ failed ] http://localhost:8080/graphs/contributors - 404
[ failed ] http://localhost:8080/contributing/tutorials - 404
[ failed ] http://localhost:8080/docs/contributing.md - 404
[ failed ] http://localhost:8080/tutorials/basic-skill/docs/extending/skills - 404
```

- As for CI:  I think it's first to sinish tool (current state - is training in so I can polish it), in future.. maybe github action or bot will be created alongside with tutorial how to implement to travis or Jenkins.. 

P.S.
And for CI... check tox.ini line 33. It was giving few advices, on how to implement things.

**Comment by butuzov** [comment]
Oh, btw. It's a part of #hacktoberfest, but I am genuinely interested to dig in, once have more time.

**Comment by butuzov** [comment]
Thanks for not closing it!

Got weird issue with linking `matchers/webhook` from `rest-api` page.  RTD generates addiitional `../` so it ends up generating bad links. 

While locally, the link looks correct, I will back in town on Wednesday and will be check what's wrong more carefully.
