### ISSUE TITLE
Make all logging translatable

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1128]
We have started using gettext to translate our logging messages, although I've come across a lot of messages that won't be translated.

In order to make a message translatable it has to be wrapped with `_(<string>)` so we should update all the logging messages to use this convention so we can translate all the messages available.

As an example on opsdroid.logging.ParsingFilter we are logging the following warning:

```python
                _LOGGER.warning(
                    "Both whitelist and blacklist "
                    "filters found in configuration. "
                    "Only one can be used at a time - "
                    "only the whitelist filter will be used."
                )

```

this logging needs to e changed like this:

```python

_LOGGER.warning(
    _(
        "Both whitelist and blacklist "
         "filters found in configuration. "
         "Only one can be used at a time - "
         "only the whitelist filter will be used."
     )
)
```

**Comment by Pralkarz** [comment]
I can pick this up if that's okay for you.

**Comment by FabioRosado** [comment]
Hello @Pralkarz that would be great 👍 please let me know if you need any help

**Comment by Pralkarz** [comment]
Hello @FabioRosado, I'm pretty much done working on the issue right now, however I cannot commit due to the following message:

```
[INFO] Installing environment for https://github.com/ambv/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('d:\\python374\\python.exe', '-mvirtualenv', 'C:\\Users\\<username>\\.cache\\pre-commit\\repotcx701a4\\py_env-python3.6', '-p', 'C:\\python36\\python.exe')
Return code: 3
Expected return code: 0
Output:
    The path C:\python36\python.exe (from --python=C:\python36\python.exe) does not exist

Errors: (none)

Check the log at C:\Users\<username>/.cache\pre-commit\pre-commit.log
```

Does that mean I need to install Python 3.6?

**Comment by FabioRosado** [comment]
Did you install pre-commit and back with the command:
`pip install pre-commit black`?

I'm wondering if its a problem with precommit

**Comment by Pralkarz** [comment]
Yes, I have. Maybe the problem stems from the fact that I have only Python 3.7 installed?

**Comment by jos3p** [comment]
I had the same problem when I was working on my PR earlier, installing Python 3.6 didnt seem to have worked so I uninstalled pre-commit ($ pre-commit uninstall) and did run black ($ black ./pathto/file) manually
