### ISSUE TITLE
Inconsistency in the logging messages

### ISSUE THREAD

**Issue by ziebam** [opsdroid/opsdroid#1137]
# Description
A lot of the logging messages are inconsistent. Let's take the file `loader.py` for example. On the line 254 there's that message that doesn't end with a dot:
```
_LOGGER.debug(
    _(
        "Couldn't find the command 'pip', "
        "trying again with command 'pip3'"
    )
)
```
Yet just a few lines ahead, on line 267, there's a message that does end with a dot:
```
_LOGGER.debug(
    _(
        "Couldn't find the command 'pip3', "
        "install of %s will be skipped."
    ),
    str(requirements_path),
)
```

There are also some inconsistencies with the parsers and connectors naming. In some logging messages they are capitalized properly while in the others they are not like in telegram's `__init__.py` file on lines 24 and 41:
```
_LOGGER.debug(_("Loaded telegram connector"))
```
```
_LOGGER.error(
    _(
        "Unable to login: Access token is missing. "
        "Telegram connector will be unavailable."
    )
)
```

I don't know for certain, but this might require some tweaking of the tests so they recognize the capital or lowercase letters properly.

I will tackle this issue if there will be no volunteers. :D

**Comment by FlipTheBit** [comment]
Attempted to fix the issue with the dots, can I try my hand at the capitalisation issue?

**Comment by Abelarm** [comment]
I would like to work on this.
I had an idea to solve this problem in a nice way, but it requires pylint.
I would write a custom checker for pylint that will check all the logs and raise and warning based on a config file.

**Comment by ammar0211** [comment]
I would like to work on this issue and look for all sorts of logging messages issues to make them all uniform

**Comment by jacobtomlinson** [comment]
Thanks so much for raising this issue @ziebam and for picking it up folks.

Perhaps a good thing to do would be to add a section to the [contributing docs](https://github.com/opsdroid/opsdroid/blob/master/docs/contributing.md) with guidelines on how logs should be formatted.

**Comment by FabioRosado** [comment]
Thats actually a good idea Jacob since we should explain better how gettext works and how we should pass the params to a logging that uses gettext 🤔

**Comment by Abelarm** [comment]
Hi guys,
Are you looking more for:
- a test/checker for bad formatted logs
- a guideline for writing logs

**Comment by jacobtomlinson** [comment]
> a guideline for writing logs

Let's start with this.
