### ISSUE TITLE
No file [...]\opsdroid\\configuration\\schema.yaml on windows starting opsdroid

### ISSUE THREAD

**Issue by iguyking** [opsdroid/opsdroid#1189]
# Description
Attempting to start opsdroid in a clean config

## Steps to Reproduce
virtualenv venv
. venv/Scripts/activate.ps1 
pip install opsdroid
opsdroid start

## Expected Functionality
Opsdroid starts with a default configuration or says "need to create base files" or creates the base folder structure to start with the defaults.  

## Experienced Functionality
(venv) ~\[...]> opsdroid start
[Errno 2] No such file or directory: 'C:\\Users\\[...]\\opsdroid\\configuration\\schema.yaml'

## Versions
- **Opsdroid version:**  v0.16.0
- **Python version:** 3.7.3
- **OS/Docker version:**  Windows 10

**Comment by jacobtomlinson** [comment]
This has been fixed in #1187.

Could you test the master branch to ensure this fix works for you?

`pip install git+https://github.com/opsdroid/opsdroid.git`

**Comment by iguyking** [comment]
That appears to have fixed it.   Thanks.
