### ISSUE TITLE
ci for checking links

### ISSUE THREAD

**Issue by butuzov** [opsdroid/opsdroid#1207]
# Description
Thanks for `opsdroid` project made some improvements on my tool, and I keep using your docs live goto docs for tests. One thing I would like to ask to focus on is documentation.  

You already have in place `mkdocs build` instruction, but we have two important conclusions:
1) It's wouldn't error if there something wrong.
2) It shows what problems you already have.

Like at this moment, running `mkdocs build` will show next message 

```
INFO    -  Building documentation...
WARNING -  Config value: 'pages'. Warning: The 'pages' configuration
           option has been deprecated and will be removed in a future release of
           MkDocs. Use 'nav' instead.
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included 
           in the "nav" configuration:
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - matchers/watson.md
```
well, more or less. 

## Suggestion

Can I add `deadlinks` as checking instruction to travis-ci, so it will error if broken link introduced to docs? I have already tried to add it to tox, but it looks like it requires some extra effort.
I am planning to make 0.0.3 version on the next two weeks (ideally on 15/11), and use it for this proposes. 

Any thoughts?

**Comment by butuzov** [comment]
btw, guess `matchers/watson.md` needs to be located in the new menu ?

**Comment by FabioRosado** [comment]
Yeah I probably forgot to add it to the mkdocs.yml - I tend to forget this one haha 

I think that would be good and it would prevent me from forgetting to add stuff to this file.

Let me know if you need help with your project would be more than happy to give a hand 😄👍

**Comment by jacobtomlinson** [comment]
Yes please go ahead and add your tool to the CI.

**Comment by butuzov** [comment]
Implemented

@jacobtomlinson @FabioRosado can you check it?
