### ISSUE TITLE
Update regex pattern for the envvar construtor

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1240]
You can use envvars on your configuration, but they need to follow this pattern `$ENVVARNAME` the regex pattern should be updated to allow users to use either `$ENVVARNAME` or `${ENVVARNAME}`. 

While we are at it we should allow users to use other characters as well like `_` or `-`. 

This change needs to be done on [opsdroid.loader.load_config_file](https://github.com/opsdroid/opsdroid/blob/674013037eab826640174407a73f8fed1a29b290/opsdroid/loader.py#L347)

**Comment by jacobtomlinson** [comment]
I'm also having issues when using quotes.

#### Works

```yaml
connectors:
  - name: slack
    api-token: $OPSDROID_SLACK_TOKEN
```

#### Doesn't work

```
connectors:
  - name: slack
    api-token: "$OPSDROID_SLACK_TOKEN"
```

**Comment by benjpalmer** [comment]
Hey @FabioRosado, 

I am new to opsdroid and just starting to dip my toes into open source. Something like this might satisfy your requirements:
`re.compile(r"^\"?\${?([A-Z-_]*)}?\"?$")`  

Here are some examples:
![Screen Shot 2019-11-25 at 7 25 49 AM](https://user-images.githubusercontent.com/28970163/69548661-f88ed080-0f54-11ea-9b47-46648657d20c.png)

Is this issue available to work on? I would also be happy to add tests for the regex pattern if necessary.

**Comment by jacobtomlinson** [comment]
Thanks for commenting @benjpalmer, that looks great (I think `$something` is a valid env var, just not a best practice style). Please feel free to pick this up. 

Shout if you need any help, we are usually around in Matrix chat [over here](https://riot.im/app/#/room/#opsdroid-developers:matrix.org).
