### ISSUE TITLE
Documentation - matchers/watson.md missing from mkdocs file

### ISSUE THREAD

**Issue by butuzov** [opsdroid/opsdroid#1250]
A separate issue for `matchers/watson.md` not found in the menu. 

@FabioRosado can you take a look to this?

**Comment by FabioRosado** [comment]
Thank you for this @butuzov  as usual I have forgot to put the documentation into the `mkdocs.yaml`. 

This could be a good issue for new beginners so I am going to label it and if in 2 days we don't have it fixed I will create a PR to fix this issue 😄 👍

**Comment by butuzov** [comment]
Just tell in which category that file should fit: Simple, Third party NLU (my guess page belong here) or Misc ?

**Comment by FabioRosado** [comment]
You are right it should be under Third party NLU and above the wit.ai due to alphabetical order 😄

**Comment by butuzov** [comment]
Now let's wait for one who whats to get that fruit!
