### ISSUE TITLE
Token based authentication for Webhook Matcher

### ISSUE THREAD

**Issue by daniccan** [opsdroid/opsdroid#1259]
# Description

The webhook matcher allows you to trigger the skill by calling a specific URL endpoint.

Currently, a skill with a webhook matcher would be called if you send a `POST` to `http://localhost:8080/skill/exampleskill/examplewebhook`. 

This URL is public and does not have any form of authentication/authorization checks, which means it can be triggered by anyone. Adding an `Authorization` header with a token-based authentication would secure the webhook.

## Steps to Reproduce
1. Create a skill `exampleskill` with a webhook matcher `examplewebhook`.

2. Send a `POST` request to `http://localhost:8080/skill/exampleskill/examplewebhook` to trigger the bot.

## Expected Functionality
1. The webhook should check for the `Authorization` header and perform a token-based authentication.

2. The bot should be triggered based on the success/failure of the authentication.

## Experienced Functionality
The Bot gets triggered without any authentication/authorization.

## Versions
- **Opsdroid version:** master branch in git
- **Python version:** 3.6.8
- **OS/Docker version:** Ubuntu 18.04

**Comment by jacobtomlinson** [comment]
Yep this would be awesome! What are your thoughts on now we would configure this? Would there be one token for all endpoints, would we configure it in the skill?

**Comment by daniccan** [comment]
My choice would be one token for all endpoints. Configuring in each skill would not be maintainable as the number of skills grows.

**Comment by jacobtomlinson** [comment]
Sounds good to me! Maybe it should be in the `web` section of the config.
