### ISSUE TITLE
Add ability to specify configuration file

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1283]
It would be nice if you could do something like

```
$ opsdroid start --config development_configuration.yaml
```

to override the config on a run, by run basis.

**Comment by jacobtomlinson** [comment]
We are way ahead of you!

See #634 and #1271.

**Comment by FabioRosado** [comment]
On the PR that I’m working allows you to start opsdroid from a path but doesn’t overwrite the normal config. Should we add a new flag to do this? 🤔

**Comment by jacobtomlinson** [comment]
I think @Cadair means just use the config specified by the flag. Not replace their default config with that file.

**Comment by FabioRosado** [comment]
Ah got it I misunderstood the overwrite bit haha

**Comment by Cadair** [comment]
Closing as a dupe of #634
