### ISSUE TITLE
Skills folder

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#129]
It might be good to have a directory where users can drop single file Python skills which will be loaded without updating the configuration. 

Perhaps somewhere like `~/.opsdroid/custom-skills`. 

This would require #119 for dependency installation.

**Comment by go8ose** [comment]
Given you've closed off #119, is it worth closing this as well?

**Comment by jacobtomlinson** [comment]
@go8ose not necessarily because of closing #119.

After reading it again though I don't think I like the idea any more. Everything should be in the config, if there are skills running which aren't specified in the config it could be confusing to debug issues. 

A better approach would be to create a generic custom skill, even if it's huge and messy, which could be treated as a place to drop random little snippets which don't add up to a whole skill. Maybe this could go in a "Tips and trick" section of the docs.
