### ISSUE TITLE
Skill configuration issues

### ISSUE THREAD

**Issue by quulah** [opsdroid/opsdroid#1347]
# Description
I'm working on a skill which should have the ability to pull the room and connector from it's config. This issue is partly a feature request, and maybe bit of a bug report or at least the documentation may need some additions.

## Steps to Reproduce
Skill `__init__()`:
```
class CVESkill(Skill):
    def __init__(self, opsdroid, config):
        super(CVESkill, self).__init__(opsdroid, config)
        ...
        # Dynamically add a decorator based on config
        # See: https://github.com/opsdroid/opsdroid/issues/1198
        expression = self.config.get("cron", {}).get("expression", "15 * * * *")
        self.schedule = match_crontab(expression)(self.schedule)
```

```
@match_regex("^cve$", case_sensitive=False)
async def schedule(self, message):
...
    if not message:
        if self.config.get("cron", {}).get("connector"):
            # Waiting for: https://github.com/opsdroid/opsdroid/issues/1345
            [connector] = [
                x
                for x in self.opsdroid.connectors
                if x.name == self.config.get("cron", {}).get("connector")
            ]
        else:
            connector = self.opsdroid.default_connector

        room = self.config.get("cron", {}).get(
            "room", self.opsdroid.default_connector.default_target
        )

        message = Message("", None, room, connector)

    await message.respond(f"Searching CVEs with queries: {', '.join(queries)}")
...
```

## Expected Functionality
The above should work and push the message from the cron trigger to #somethingelse. When triggered by hand with the regex match, it should write to the room being asked from.

The feature request part of this issue would be out-of-the-box configurability of the connector and room per skill. Also, it would be nice to have some sort of default configuration along the lines of `CONFIG_SCHEMA`. I'm currently using the `self.config.get()` and setting some sane values.

It's also a bit tricky to configure the decorators, as you need to do it like #1198 states. Perhaps it would be worthwhile to add this in the documentation.

The bug report / cry for help is that I originally had the room / connector selection in the `__init__()` of the skill, but this just causes the whole bot to hang when starting. I'd like to do it that way to have all the configuration handling in one place. As seen below, there's also something wrong with the current approach as the connector ends up being `None` for some reason.

## Experienced Functionality

When the room / connector selection is in the `schedule()` method:
```
hemmo_1  | DEBUG opsdroid.parsers.crontab: Running crontab skills at Thu Jan 30 08:29:00 2020.
hemmo_1  | ERROR opsdroid.core: Exception when running skill 'cve'.
hemmo_1  | Traceback (most recent call last):
hemmo_1  |   File "/usr/local/lib/python3.7/site-packages/opsdroid/core.py", line 397, in run_skill
hemmo_1  |     return await skill(event)
hemmo_1  |   File "/root/.local/share/opsdroid/opsdroid-modules/skill/cve/__init__.py", line 142, in schedule
hemmo_1  |     await message.respond(f"Searching CVEs with queries: {', '.join(queries)}")
hemmo_1  |   File "/usr/local/lib/python3.7/site-packages/opsdroid/events.py", line 263, in respond
hemmo_1  |     "thinking-delay" in self.connector.configuration
hemmo_1  | AttributeError: 'NoneType' object has no attribute 'configuration'
```
When the room / connector selection is in the `__init__()`:

```
hemmo_1  | DEBUG opsdroid.connector.slack: Default room is #general.
hemmo_1  | INFO opsdroid.connector.slack: Connected successfully.
hemmo_1  | DEBUG asyncio: Using selector: EpollSelector
^CERROR: Aborting.
```

It hangs, and never starts the web server, hence the CTRL-C.

## Versions
- **Opsdroid version:** For some reason this says: opsdroid 0+unknown, I'm using the Docker image and it should be v0.17.1, I'll need to check my `docker-compose.yml` file... 
- **Python version:** 3.7.6
- **OS/Docker version:**

## Configuration File
```yaml
---
logging:
  level: debug
  console: true
connectors:
  slack:
    default-room: "#general"
...
skills:
  cve:
...
    cron:
      room: "#somethingelse"
      expression: "29 * * * *"
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by quulah** [comment]
For the image, it is indeed v0.17.1, so there might be something wrong with the image or the `opsdroid version` command. :)

**Comment by FabioRosado** [comment]
Hello @quulah  thank you for raising this issue. 
I am going to just touch on the `CONFIG_SCHEMA` suggestion - I remember that when I touched the config validation, each module will try to look for this const and run the validation.  Got to be honest and say that didn't really try  validating skills, but it should work 🤔 

For the rest I think we need to try and fix #1345 and should help you, perhaps Jacob has some suggestion for you before we fix this issue.

**Comment by jacobtomlinson** [comment]
Let me unpack this a little as there are a few things to discuss.

## Bugs

> When the room / connector selection is in the schedule() method:

This is because you are not constructing the `Message` object correctly. This is certainly our fault for having some out of date documentation somewhere, if you could point us to it I would appreciate it. As we kept fiddling with the interface to the event objects we switched everything over to kwargs to avoid future problems. Perhaps we should raise an exception when folks use kwargs.

Try this instead:

```
message = Message(text="", target=room, connector=connector)
```

> When the room / connector selection is in the __init__():

I am unsure why this is happening. Are you able to attach a debugger or add some debug log statements before and after the skill is decorated so we can try and figure out what is happening here?

> It's also a bit tricky to configure the decorators, as you need to do it like #1198 states. Perhaps it would be worthwhile to add this in the documentation.

There was a PR to add this to the docs which went stale. If you feel you could contribute this we would really appreciate it.

> For some reason this says: opsdroid 0+unknown, I'm using the Docker image and it should be v0.17.1, I'll need to check my docker-compose.yml file...

This is a known issue covered in #950.

## Feature requests

> The feature request part of this issue would be out-of-the-box configurability of the connector and room per skill. 

Do you mean that it would be good to have `self.opsdroid.default_connector` and `self.opsdroid.default_connector.default_target` report different values based on which skill you are in?

> Also, it would be nice to have some sort of default configuration along the lines of CONFIG_SCHEMA. I'm currently using the self.config.get() and setting some sane values.

I feel like `self.config.get()` is an acceptable way to do this. If you feel like proposing an alternative I'd be keen to see an example.

**Comment by quulah** [comment]
Thanks for the Swift responses. I really appreciate it!

Sorry for smashing multiple things together. I was in a bit of a hurry and
wanted to get it all out of my head. :)

For the bugs, I'll do some more digging and get back to you. This may not
be until next week.

The configuration things: I meant that it could be nice to have a
`CONFIG_DEFAULTS` similarly to `CONFIG_SCHEMA` which would be automatically
consumed, merged with the configuration file, so the skill author could
just look at `self.config`. But, as you said, using `.get()` and providing
some values during init is OK too.

Yup, the room and connector could work the way you described when
configured separately for a skill.

**Comment by jacobtomlinson** [comment]
It turns out it is actually possible to specify defaults in `CONFIG_SCHEMA`, we just aren't capturing them correctly at the moment. I've raised #1348 to resolve this.

I'll start a separate discussion issue around default rooms and connectors.

**Comment by quulah** [comment]
I found the mistake in the docs for the crontab example and created #1350 

I noticed that there's also the older non-kwargs `Message()`s being created in the tests.

For example:

https://github.com/opsdroid/opsdroid/blob/master/tests/test_parser_regex.py#L37
