### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1422]
As those of us who maintain opsdroid do it in our spare time we often work on it in bursts. 

One of the things I find hardest is making releases. Writing up the release notes and the blog post takes a couple of hours and I just struggle to fit that in. Which means we often go a long time between releases.

Recently I've been finding it even harder to work on opsdroid, and so I propose we automate this process to try and reduce the burden and increase release frequency.

Here is what I propose:
- We label PRs with `Breaking`, `Enhancement` and `Bug Fix` for anything substantial
- We create a GitHub action which runs weekly/fornightly/monthly/whatever which increases the version based on the labels and semver if there have been suitable PRs during that period and pushes a tag
- We stop publishing a release blog post

Releases are automated already once a tag is pushed, so new versions will be pushed to PyPI automatically.

Thoughts?

**Comment by Cadair** [comment]
Sounds like it could work, how could we integrate better change descriptions into this process. For other projects I use towncrier, but I wonder if we can do it with Github?

**Comment by FabioRosado** [comment]
That sounds good, should we add a description to what the PR does as well? Might give some context if needed 🤔

**Comment by jacobtomlinson** [comment]
I feel like there are two options here:

1. Use PR titles more strictly and update them before merging to be really descriptive
1. Add a section to the PR template for a description which we scrape after

I feel like option 1 would be less effort. But option 2 would probably make better descriptions.

My preference is option 1.

**Comment by FabioRosado** [comment]
Some PR's probably wouldn't need any further description other than the title, for instance if we fixed typos or tiny fixes. But if it's a breaking change it could be good, but we could add it if needed.

The only thing that might get on the way of automation is when travis decides to stop working properly for some reason. I noticed that when I could go into opsdroid travis account, that the job got cancelled (perhaps because the update bot pushed the changes at the same time and stopped the previous job?) but had to manually run the CI. 

When travis acts up you will need to merge the PRs or manually run the jobs

**Comment by Cadair** [comment]
The other option is to use the commit info from the squashed commits to master, this puts the responsibility on the person who merges the PR to make a nice title + description.

Perhaps we could add something to the PR template to encourage the contributor to add a description that we could then copy into the commit?

**Comment by jacobtomlinson** [comment]
> The only thing that might get on the way of automation is when travis decides to stop working properly for some reason.

I think this is rare enough that I'm not worried about it. Perhaps expanding the permissions so that you can merge without Travis approval would help.

> Perhaps we could add something to the PR template to encourage the contributor to add a description that we could then copy into the commit?

Yeah this sounds good.
