### ISSUE TITLE
How to create a OpsDroid instance for test case?

### ISSUE THREAD

**Issue by cupen** [opsdroid/opsdroid#1430]
# Description
How to create a OpsDroid instance for test case?

## Expected Functionality
```
instance = testhelper.CreateOpsDroid(path/to/config)
msg = Message(text="abc", user="user", ...)
resp = await instance.parse(msg)
assert resp.STATUS  == ...
```
## Experienced Functionality
It's hard to debug opsdroid and skill.

## Versions
- **Opsdroid version:** 0.17.1
- **Python version:**  3.8.0
- **OS/Docker version:** -

**Comment by FabioRosado** [comment]
Hello @cupen  thank you for raising this issue, you can follow the example of some of the tests we have created already. 

The quick answer would be to import `OpsDroid` from `opsdroid.core` and use a `with` statement like such:

```python
from opsdroid.core import OpsDroid

with OpsDroid() as opsdroid:
    # Do stuff with opsdroid
```

Here's an example of how to create an opsdroid instance and how to test a message (find it on [opsdroid.tests.test_connector_telegram](https://github.com/opsdroid/opsdroid/blob/1af196fb064b7f3aa627014cdec2ff531baf674e/tests/test_connector_telegram.py#L432))

```python
    async def test_respond(self):
        post_response = amock.Mock()
        post_response.status = 200

        with OpsDroid() as opsdroid, amock.patch.object(
            self.connector.session, "post"
        ) as patched_request:

            self.assertTrue(opsdroid.__class__.instances)
            test_message = Message(
                text="This is a test",
                user="opsdroid",
                target={"id": 12404},
                connector=self.connector,
            )

            patched_request.return_value = asyncio.Future()
            patched_request.return_value.set_result(post_response)
            await test_message.respond("Response")
            self.assertTrue(patched_request.called)
            self.assertLogs("_LOGGER", "debug")
```

Hope this helps you. Do let us know if you need any further help with it 👍

**Comment by cupen** [comment]
@FabioRosado  It's great. Tanks you very much.
