### ISSUE TITLE
Add support for video events

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1446]
We currently only have event types for file and image, but we should also have a video type to handle things like mp4.

**Comment by arctdav** [comment]
I'm a beginner, but I'd like to help. Could you assign this issue to me?

**Comment by Cadair** [comment]
Let us know how you get on or if you need any help. The best thing to do is open a PR early and ask for comments on it :smile:

**Comment by arctdav** [comment]
just to confirm, the place to modify event types is at this file: opsdroid/opsdroid/connector/matrix/create_events.py

**Comment by arctdav** [comment]
If I was wrong, could you let me know which file I should dig into as a starting point? tyty

**Comment by arctdav** [comment]
What feature should the Video event type support? I suppose it's not the same feature as image dimension.

**Comment by SaquibShahzad** [comment]
Since @arctdav hasn't been working on the issue, could I continue on this? I read the progress so far on the PR and could help with the testing!

**Comment by arctdav** [comment]
@SaquibShahzad go ahead

**Comment by FabioRosado** [comment]
Awesome @SaquibShahzad  let us know if you need any help 👍

**Comment by HritwikSinghal** [comment]
Hey is anyone working on this issue? My team would like to work on this issue as a project.

**Comment by FabioRosado** [comment]
Hello @haardikdharma10  no one is currently working on this issue. Would be great if your team could pick it up 👍

**Comment by HritwikSinghal** [comment]
> Hello @haardikdharma10 no one is currently working on this issue. Would be great if your team could pick it up 👍

are you referring to my team?

**Comment by haardikdharma10** [comment]
> > Hello @haardikdharma10 no one is currently working on this issue. Would be great if your team could pick it up 👍
> 
> are you referring to my team?

That's what I guess. @FabioRosado :P

**Comment by subodhawasthi** [comment]
I'm on @HritwikSinghal 's team. Can you provide us some tests on this issue?

**Comment by jacobtomlinson** [comment]
@HritwikSinghal yes I think @FabioRosado meant you 😆.

@subodhawasthi we expect all contributors to write tests and documentation for their changes. We will not provide tests.

**Comment by HritwikSinghal** [comment]
@jacobtomlinson So what would be the criteria for acceptance? There have to be some standard tests that you perform for every PR to accept it

**Comment by FabioRosado** [comment]
You can check the other PRs but to sum up:
- Coverage must remain the same (100% or close)
- your tests must all pass
- other tests need to pass 
- you need to run black to lint your code
- you must write documentation for the thing you are adding

If you need help with running tests or black the contributing section in our docs explains it but we can give you a hand if you have any issues 👍

**Comment by HritwikSinghal** [comment]
ok thanks, we will start working on it ASAP

**Comment by devraj4522** [comment]
Can I get much detail about that

**Comment by HritwikSinghal** [comment]
@devraj4522 my team is actually working on this issue and we need to close this pull request for submission of our project. So can you please leave this issue to us since our grade depends on it ?

FabioRosado, i assure you i am working on this issue with my team and we will close this issue in near future, its just that our mid-sem exams are going on currently.

**Comment by devraj4522** [comment]
Ok I didn't knew .
