### ISSUE TITLE
Document options for events with multiple possible users

### ISSUE THREAD

**Issue by SolarDrew** [opsdroid/opsdroid#1448]
Some chat platforms supported by opsdroid have the possibility of a single event corresponding to multiple users. For example, slack's api call to invite users to a channel takes a list of users as input. Opsdroid, on the other hand, only supports a single user on any given event, and for the sake of flexibility I think this is as it should be.

That being the case, the documentation needs to reflect this disconnect - skill developers should know that they need to create multiple single-user events rather than trying to create one multi-user one, or that their skill can call the api directly rather than emitting many events, if they're concerned about performance. All of this should be described in the documentation for the [base `Event` class](https://docs.opsdroid.dev/en/stable/skills/events.html).

**Comment by codeboy5** [comment]
Hi @SolarDrew can I work on this ?

**Comment by FabioRosado** [comment]
Hello @codeboy5 it would awesome if you could work on this issue, please let us know if you need help with anything

**Comment by codeboy5** [comment]
Okay thanks 🙂

**Comment by Pratik-ahirrao** [comment]
Is anyone still working on this issue? I would like to work on that

**Comment by FabioRosado** [comment]
No one is currently working on this issue so it remains open 😄 👍

**Comment by Pratik-ahirrao** [comment]
Can you help me to start with this issue?

**Comment by SolarDrew** [comment]
@Pratik-ahirrao you'll need to edit the [file in the docs which describes `Events`](https://github.com/opsdroid/opsdroid/blob/master/docs/skills/events.md) to include a short discussion of how to use them for multi-user events. Are you familiar with the workflow of using git and github to create a Pull Request?

**Comment by Pratik-ahirrao** [comment]
Yes i know basic commands of git

**Comment by Pratik-ahirrao** [comment]
Can you tell me where is the code that describes about events.md?

**Comment by FabioRosado** [comment]
hello, you can find the events here: opsdroid.events.Event

**Comment by Leotuashutosh** [comment]
Hello! I would like to work on this issue if this is still open

**Comment by jacobtomlinson** [comment]
@Leotuashutosh please go ahead

**Comment by haardikdharma10** [comment]
Hey there, @jacobtomlinson I hope this issue is still open. I went through the events.md file and I think the issue mentioned just requires a small note at the end of the Events section in the events.md file. Did I get this right? If yes, can I start working on it as it won't take more than a few minutes?
