### ISSUE TITLE
Anyone working on a MS Teams connector?

### ISSUE THREAD

**Issue by jedelman8** [opsdroid/opsdroid#1511]
# Description
Just checking to see if there is anyone working on a MS Teams connector?

**Comment by FabioRosado** [comment]
Hello @jedelman8 , there is no one working on a Teams connector but it's something we want to add very soon, if you would like you could contribute to the project by adding this connector.

Let us know if you need any help 😄 👍

**Comment by jedelman8** [comment]
Thanks for the quick response.  We'll be sure to let you know if we are going to pursue it!
