### ISSUE TITLE
Add message.room

### ISSUE THREAD

**Issue by dizzi90** [opsdroid/opsdroid#1520]
version:
`v0.18.0`

`opsdroid start`

user:
> some_command_that_references_room

opsdroid-desktop:
> Check logs for details

logs:
> AttributeError: 'Message' object has no attribute 'room'

**Comment by jacobtomlinson** [comment]
I've moved this over to opsdroid/opsdroid as it isn't related to opsdroid-desktop.

As I said `room` has been renamed to `target`, so you will want something like this.

```python
from opsdroid.skill import Skill
from opsdroid.matchers import match_regex

class RoomSkill(Skill):
    @match_regex('room')
    def say_room(self, message):
        message.respond(f"{message.target}")
```

**Comment by dizzi90** [comment]
@jacobtomlinson It's still showing up as None, with message.target

![image](https://user-images.githubusercontent.com/3081351/84420335-2ea65000-ac1a-11ea-9aaa-9cfdbe8e70ac.png)
![image](https://user-images.githubusercontent.com/3081351/84420384-3fef5c80-ac1a-11ea-88ba-7c51baac7733.png)

Am I doing something wrong or is it a bug?

**Comment by jacobtomlinson** [comment]
This is expected from opsdroid desktop. There are no rooms or targets.

**Comment by dizzi90** [comment]
I'm suggesting that it would be a good idea to name that one place

**Comment by jacobtomlinson** [comment]
For what purpose?
