### ISSUE TITLE
Improvements to the Matrix Connector now that it's using nio

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1529]
I am opening this as a placeholder for a bunch of smaller tasks that need investigating or doing after the merge of #1418, as is usual with a large PR somethings got delayed to follow ups.

- [x] Handle all cases of (send) methods returning a `nio.Error` instance where previously errors would be raised. Proposed solution: write a decorator which converts a return Error to a raised error. (https://github.com/opsdroid/opsdroid/pull/1418#discussion_r436615260)

- [ ] Handle multiple events in one sync response. (https://github.com/opsdroid/opsdroid/pull/1418#discussion_r435176024)

- [x] Investigate generalising the logging of errors from nio in non-send methods. Could potentially use the same solution as the send methods above. (https://github.com/opsdroid/opsdroid/pull/1418#discussion_r432383617)

- [x] Ensuring 100% test coverage and test improvements, it's clear from the refactoring work that a bunch of our tests are not great tests of the behaviour only good tests of the code. Given nio provides clients which do no no io :wink: maybe we could look at developing tests based on nio classes?

- [x] User documentation! We just completely changed the type of `ConnectorMatrix.connection` we need to document it.

- [ ] Provide some information in the logs if events don't decrypt properly, and if we can get it out of nio, why they didn't decrypt.

- [ ] Improve logging of some transport errors with sync, currently they show as unknown errors.

Also this rewrite needs a lot of testing before we release it onto the world.

**Comment by Tyagdit** [comment]
- [ ] Sending files using URLs doesn't work correctly, returns a TypeError which needs fixing
- [ ] Initial sync is being rate limited for some reason, needs some fiddling with sync tokens or device IDs
- [ ] Receiving membership events isn't proper

**Comment by Cadair** [comment]
I have moved the remaining three issues to #1712 #1713 and #1714
