### ISSUE TITLE
Add 3.8 support to setup.py

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1534]
We've been running CI against 3.8 for a while now, we should update the metadata in `setup.py` to explicitly state we support 3.8.

We should also update the [support table](https://github.com/opsdroid/opsdroid/blob/master/docs/maintaining/supported-python-versions.md) to say we support 3.8.

**Comment by Cadair** [comment]
and also pull 3.6 now 0.19 is out as well.

**Comment by elijose55** [comment]
Can I work on this issue?

**Comment by FabioRosado** [comment]
Hello @elijose55  please go ahead and submit a PR, let us know if you need any help
