### ISSUE TITLE
GitHub Connector uses deprecated query params when retrieving authenticated user

### ISSUE THREAD

**Issue by nkuik** [opsdroid/opsdroid#1546]
# Description

The GitHub connector uses a deprecated query params method to authenticate to GitHub for retrieving the username. Besides being less-than-ideal in sending the token in the query, this approach will eventually be unsupported by GitHub. 

## Steps to Reproduce

1. Setup the configuration for using the opsdroid GitHub connector (by adding the token in `configuration.yaml`).
2. Start opsdroid.
3. Wait for an email from GitHub notifying that a deprecated way of using the `user` API was used (if the token you used is connected to your GitHub account.

Here is an example of GitHub's warning email:

<img width="1401" alt="Screenshot 2020-06-23 at 11 28 56" src="https://user-images.githubusercontent.com/14183156/85394074-4cdf4a80-b54e-11ea-8ab8-0c6b80d260c5.png">

## Expected Functionality

Opsdroid should authenticate to GitHub without a deprecated method of doing so.

## Experienced Functionality

When starting up Opsdroid with the GitHub connector, I later received an email from GitHub warning that my GitHub token had been used with the GitHub API using a deprecated authentication strategy.

## Versions
- **Opsdroid version:** 0.19.0
- **Python version:** 3.8.3
- **OS/Docker version:** macOS Catalina (10.15.3)

## Configuration File

```yaml
skills:
  hello: {}

connectors:
  github:
    token: <my token>
```

## Additional Details

None.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I made a start on rewriting this connector recently but lost me branch due to a corrupt SSD. I intend on taking another run at it soon.

I noticed the same issue, the authentication method we are using has been deprecated. It would be great to get this updated.
