### ISSUE TITLE
Pyup badge in README links to a 404 page.

### ISSUE THREAD

**Issue by haardikdharma10** [opsdroid/opsdroid#1623]
# Description
The Pyup badge in the README links to a 404 page. Can we consider removing it? It links to https://pyup.io/repos/github/opsdroid/opsdroid/ which is pretty straightforward and correct as other repositories that use this badge have the same format and links correctly for them.

**Comment by jacobtomlinson** [comment]
Yes we no longer use PyUp bot. Would you be interested in raising a PR to fix this? And perhaps also reviewing our other badges to ensure they are working correctly.

**Comment by haardikdharma10** [comment]
@jacobtomlinson I am on it.
