### ISSUE TITLE
Trouble in add new locale support

### ISSUE THREAD

**Issue by chunibyo-wly** [opsdroid/opsdroid#1630]
# Description

Hello
I'm a beginner and I attempt to add Chinese locale support for start.
But I met a trouble which is locale not worked shown below after I compiled.
![locale.png](http://ww1.sinaimg.cn/large/006XlhXpgy1gicd3caevxj32801e0k43.jpg)
Thanks for your help.

And I use `print(locale.getlocale())` to get shell env which is `('zh_CN', 'UTF-8')`
I have no idea how to solve it
Thanks for your help

**Comment by haardikdharma10** [comment]
Hello @chunibyo-wly, you can refer to the documentation here: https://docs.opsdroid.dev/en/stable/contributing.html?highlight=locale#localization. Hope you'll find the solution:)
cc: @FabioRosado, I hope that is it, anything to add here?

**Comment by FabioRosado** [comment]
Hello @chunibyo-wly  thank you for raising this PR. Can you please share your opsdroid config as well?

Currently opsdroid will only use the translated file, if you have the `lang:` parameter. You can read more on the [configuration reference documentation](https://docs.opsdroid.dev/en/stable/configuration.html#language)

**Comment by chunibyo-wly** [comment]
Oh, that's the point.
It worked well after editing configration.
I thought I havn't read env doc cause this mistake, sorry for that.
I wrongly thought opsdroid will get locale from shell parameter.
thanks

**Comment by FabioRosado** [comment]
No worries, glad I could help!
This is something that should be set in the configuration example, but is not. So I am going to raise a new issue to add the `lang` parameter to the configuration.
