### ISSUE TITLE
Add a SIGHUP handler to reload opsdroid

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1631]
Many linux daemons respond to the [`SIGHUP`](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGHUP) signal by reloading their configurations. Combined with opsdroid's `no_cache: true` this could be used to reload a skill (or other plugin) while developing it.

This should be added in the same manner as the [existing handlers](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/core.py#L56-L60).

**Comment by haardikdharma10** [comment]
Hey @Cadair, I would like to work on this issue and fix it. Any starting steps you'd like to suggest? Thanks.
