### ISSUE TITLE
Create an opsdroid instance for the opsdroid chat

### ISSUE THREAD

**Issue by SolarDrew** [opsdroid/opsdroid#1637]
# Description
Inexplicably, we don't currently have opsdroid actually running in the opsdroid matrix/slack chat rooms, which seems like something of an oversight.

## Steps to Reproduce
Go to any one of the opsdroid chat rooms.

## Expected Functionality
There should be a bot, so we can demo cool features, show off useful functionality and encounter bugs first-hand. We could have the config file in the repo, or in its own separate one, so that we and others can keep it up to date and add skills, etc.

## Experienced Functionality
Ain't no bot. You've just got to imagine what it would be doing.

## Configuration File

```yaml
# There is no code

```

**Comment by Cadair** [comment]
there is now the jitsi bot, but yeah

**Comment by tardigrde** [comment]
Hi! I would like to do this if nobody else doing it already. Where would it be running? It has to be connected to both matrix and slack right?

**Comment by FabioRosado** [comment]
Hello @tardigrde, this PR was raised after we had a meeting last month and realised that we should probably have opsdroid running on our chat rooms. We will host the bot ourselves, but we need to figure out what sort of skills we need to build/add to it
