### ISSUE TITLE
Proposal to add All-Contributors Bot.

### ISSUE THREAD

**Issue by haardikdharma10** [opsdroid/opsdroid#1643]
# Description
Current Contributions graph on the README is not updated and of course it doesn't include me as one of the contributors :P I have came across this amazing bot (https://github.com/all-contributors/all-contributors-bot) which will pull a user's profile, grab the contribution type emoji, update the project README and then open a Pull Request against the project. The documentation is easy to understand and can be found here: https://allcontributors.org/docs/en/bot/overview
Let me know what you guys think :)
cc: @jacobtomlinson, @FabioRosado

**Comment by jacobtomlinson** [comment]
The contributors image in the README is provided by Open Collective our fiscal host. It appears the image is showing 112 contributors, but opsdroid has had over 150 now. So I'm not sure if this is a limitation of their image generation, we should probably raise it with them.

You are listed in the GitHub contributor graph as number 21.

https://github.com/opsdroid/opsdroid/graphs/contributors

I don't think adding an automation which raises PRs is something we want to do here. The current method requires no effort from us, but reviewing PRs does. Sorry!
