### ISSUE TITLE
Add a config option to disable registering a route for /

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1656]
In the web server by default a route is registered for the base / path. This should be configurable in case a user wants to register their own.

**Comment by mdb571** [comment]
Hey there,I would like to work on this issue since this is beginner one.Can you guide me as to what has to be done inorder to resolve this issue?

**Comment by Cadair** [comment]
[this](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/web.py#L28) line needs to be configurable. If the `serve_root_path: false` then it shouldn't be run.

**Comment by dexterpuru** [comment]
is this what you are asking for?
`
if (self.web_index_handler){
    self.web_app.router.add_get("/", self.web_index_handler)
}
`

**Comment by anushkrishnav** [comment]
I wish to work on it
