### ISSUE TITLE
Required information before installing

### ISSUE THREAD

**Issue by hashtag-incIude** [opsdroid/opsdroid#1666]
Still installing the  modules of each set of requirements is individually pip installed. It would be better to gather all requirements (including core opsdroid requirements) and to do in a single pip install. That way any collisions will be detected and potentially handled by pip, or many error durning installed is also solved.

**Comment by jacobtomlinson** [comment]
I'm not sure I understand. You can install all optional dependencies with `pip install opsdroid[all]`.

**Comment by hashtag-incIude** [comment]
How can I get the sticker!!

**Comment by FabioRosado** [comment]
We only give stickers if a PR closes an issue, but we haven't had the time to send new ones yet
