### ISSUE TITLE
Add a tweet scraper in opsdroid site

### ISSUE THREAD

**Issue by akshitagupta15june** [opsdroid/opsdroid#1670]
# Description
Please include a summary of the issue.

Add a tweet scraper in opsdroid site https://opsdroid.dev/

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.
https://github.com/Hsankesara/Tweets-Scrapper
from this we can scrap the tweets

## Expected Functionality
Explain what should happen.

Site will be more enhanced and real time friendly it will show real time tweets related to opsdroid.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

real time experience

## Versions
- **Opsdroid version:**
- **Python version:**
- **OS/Docker version:**

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
Closing as spam promoting another project.
