### ISSUE TITLE
Slack Connector, search a channel ID, by its name

### ISSUE THREAD

**Issue by chillipeper** [opsdroid/opsdroid#1699]
# Description
Currently, if we need to send any message to a Slack Channel, we have to know the channel ID. Unfortunately, this is not always possible, and it would be nice to have a way that Opsdroid translates channel names to channel ids.

I have been searching on the Slack API and there is no method that would do this, so the only thing I can think of, is iterating over all the channels. (probably when Opsdroid starts the connector?)  https://api.slack.com/methods/conversations.list
I would like to submit a PR for this, and I would love your thoughts, suggestions on how could this be better implemented.

## Steps to Reproduce
N/A

## Expected Functionality
```
await self.opsdroid.send(Message("Hello", target="test-channel"))
```

## Experienced Functionality
This will throw an error:
```
await self.opsdroid.send(Message("Hello", target="test-channel"))
```
Only works when channel ID is mentioned:
```
await self.opsdroid.send(Message("Hello", target="CF3ZP8KS8"))
```

## Versions
- **Opsdroid version:** All versions
- **Python version:** All Versions 
- **OS/Docker version:** All Versions

**Comment by jacobtomlinson** [comment]
Does this work for you?

```python
await self.opsdroid.send(Message("Hello", target="#test-channel"))
```

**Comment by chillipeper** [comment]
I think this behaviour has changed very recently on the Slack API. The following methods are working now:
```
await self.opsdroid.send(Message("Hello", target="test-channel"))
await self.opsdroid.send(Message("Hello", target="#test-channel"))
```

I am saying very recently because this has been an issue that I have been trying to tackle for a while, and it was not working on the past.

I see that not even the documentation of https://api.slack.com/methods/chat.postMessage#channels has been updated yet

> Post to a public channel
> Pass the channel's ID (C024BE91L) to the channel parameter and the message will be posted to that channel. The channel's ID can be retrieved through the conversations.list API method.

I am not sure if this issue is relevant now, I have found another method, with the same problem (https://api.slack.com/methods/conversations.setTopic) where the ID is required, and the channel name won't work

**Comment by jacobtomlinson** [comment]
I've always used the `#` prefixed version with no issues.

I don't think opsdroid supports `setTopic` right now. But yes I see that this could be a problem in other places.

I would be very happy to review a PR which grabs the channel list and automatically converts names to IDs as part of the send methods.

**Comment by chillipeper** [comment]
I have opened #1765  to try to tackle this
