### ISSUE TITLE
Error during installation on debian and Matrix database raise an error when we are returning None on getting a nonexistent key

### ISSUE THREAD

**Issue by Anshika66-Gupta** [opsdroid/opsdroid#1700]
# Description
Please include a summary of the issue.

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.

## Expected Functionality
Explain what should happen.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:**
- **Python version:**
- **OS/Docker version:**

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by Cadair** [comment]
Can you provide more information? The code you ran, the error you saw?

**Comment by jacobtomlinson** [comment]
Closing as no information was provided.

Please open a new issue and fill out the template.
