### ISSUE TITLE
Add `web` to example config

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#171]
Add the [web config](http://opsdroid.readthedocs.io/en/latest/configuration-reference/#web) to the [example config file](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/configuration/example_configuration.yaml).

**Comment by jacobtomlinson** [comment]
README would need updating too.

**Comment by jacobtomlinson** [comment]
Done example config file in #190

**Comment by bege13mot** [comment]
Hi jacobtomlinson,

Hope that pull request #257 is the correct one to close this issue.
