### ISSUE TITLE
Handle multiple events in a single sync response in the matrix connector

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1712]
# Description

Currently, when parsing a sync response, the matrix connector returns out of the method when it encounters the first event in the timeline.

https://github.com/opsdroid/opsdroid/blob/3fe47d89df719e22861352fc3806d4093832c024/opsdroid/connector/matrix/connector.py#L284-L286

This is then subsequently passed to `opsdroid.parse` in the `listen` method:

https://github.com/opsdroid/opsdroid/blob/3fe47d89df719e22861352fc3806d4093832c024/opsdroid/connector/matrix/connector.py#L306-L309

The fix for this is to allow returning a list of `Event`s from the `_parse_sync_response` method and then iterating over them in `listen`.

**Comment by Cadair** [comment]
An alternative (probably preferable) solution is to move the call to `opsdroid.parse` into the `_parse_sync_response` method.

**Comment by ShrillShrestha** [comment]
Since I am a beginner, I am not sure if what I understood was what you were referring to. Just wanted to ask is it just moving the call for` opsdorid.parse` in the `_parse_sync_response` method instead of this [return statement](https://github.com/opsdroid/opsdroid/blob/3fe47d89df719e22861352fc3806d4093832c024/opsdroid/connector/matrix/connector.py#L284) where each event will be passed in the `opsdorid.parse` method inside the `for` loop.

**Comment by cognifloyd** [comment]
This is approximately @Cadair's solution in #1715.

```python
    async def _parse_sync_response(self, response):
        # ... snip
        for roomid, roomInfo in response.rooms.join.items():
            if roomInfo.timeline:
                for event in roomInfo.timeline.events:
                    if event.sender != self.mxid:
                        # ... snip
                        await self.opsdroid.parse(
                            self._event_creator.create_event(event.source, roomid)
                        )

    async def listen(self):
        # ... snip
        while True:
            response = await self.connection.sync(
                # ... snip
            )
            # ... snip
            await self._parse_sync_response(response)
```

I think this might be a bit cleaner (which I've recommended in #1715):

```python
    async def _parse_sync_response(self, response):
        # ... snip
        for roomid, roomInfo in response.rooms.join.items():
            if roomInfo.timeline:
                for event in roomInfo.timeline.events:
                    if event.sender != self.mxid:
                        # ... snip
                        yield await self._event_creator.create_event(
                            event.source, roomid
                        )
        return

    async def listen(self):
        # ... snip
        while True:
            response = await self.connection.sync(
                # ... snip
            )
            # ... snip
            async for message in self._parse_sync_response(response):
                if message:
                    await self.opsdroid.parse(message)
```

**Comment by ShrillShrestha** [comment]
I was thinking more like this, similar to @Cadair :
> 
> ```python
>     async def _parse_sync_response(self, response):
>         # ... snip
>         for roomid, roomInfo in response.rooms.join.items():
>             if roomInfo.timeline:
>                 for event in roomInfo.timeline.events:
>                     if event.sender != self.mxid:
>                         # ... snip
>                         await self.opsdroid.parse(
>                             self._event_creator.create_event(event.source, roomid)
>                         )
> 
>     async def listen(self):
>         # ... snip
>         while True:
>             response = await self.connection.sync(
>                 # ... snip
>             )
>             # ... snip
>             await self._parse_sync_response(response)
> ```
> 
@cognifloyd, yours is also a beautiful solution:
> 
> ```python
>     async def _parse_sync_response(self, response):
>         # ... snip
>         for roomid, roomInfo in response.rooms.join.items():
>             if roomInfo.timeline:
>                 for event in roomInfo.timeline.events:
>                     if event.sender != self.mxid:
>                         # ... snip
>                         yield await self._event_creator.create_event(
>                             event.source, roomid
>                         )
>         return
> 
>     async def listen(self):
>         # ... snip
>         while True:
>             response = await self.connection.sync(
>                 # ... snip
>             )
>             # ... snip
>             async for message in self._parse_sync_response(response):
>                 if message:
>                     await self.opsdroid.parse(message)
> ```

**Comment by ShrillShrestha** [comment]
@Cadair, @cognifloyd Do you want me to make the change as the one stated above?
