### ISSUE TITLE
Update documentation on memory

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1736]
While answering a question from @xDiesel76 on our matrix channel, I realised that the documentation on opsdroid memory is missing some things like the [`delete` method](https://github.com/opsdroid/opsdroid/blob/d92a129c557d209172fb83507a3e1a414fb8e28a/opsdroid/memory.py#L53).

Just to make sure that this documentation stays up to date with the code, I would use the sphinx autodoc to generate the documentation from the docstrings. For example:

```
```eval_rst
.. autoclass:: opsdroid.memory.Memory
    :members:
```

Feel free to ask for help if you need a hand with sphinx autodoc!

Jacob also mentioned on the chat that you could grab the database connection with `self.opsdroid.get_database("sqlite").client`

**Comment by xDiesel76** [comment]
Where are you supposed to put the sphinx autodoc?

**Comment by FabioRosado** [comment]
I would say move the example up and then use 

```
```eval_rst
.. autoclass:: opsdroid.memory.Memory
    :members:
```

After, that will make sphinx to generate the docs automatically, we can then remove the mention of `put, get`

**Comment by xDiesel76** [comment]
It isn't generating me anything? Am I doing something wrong

**Comment by FabioRosado** [comment]
are you closing the backticks? I am unable to do it in here. You might need to install some dependencies for the docs, feel free to update the open PR that you have and I'll test it on my end 😄 👍

**Comment by xDiesel76** [comment]
Thanks fabio, no I wasn't closing the backticks. I updated the PR, can you see if the autoclass work?
