### ISSUE TITLE
Add remove user option in telegram connector 

### ISSUE THREAD

**Issue by thechawla225** [opsdroid/opsdroid#1766]
Hello guys ! new comer here, as I was going through the docs for the telegram connector I realized that there is no way to remove users from a group chat/channel . So I would like to request that this feature be added.

Also I would like to volunteer to add this feature.

Thanks a lot!

**Comment by FabioRosado** [comment]
Hello @thechawla225  thank you for raising this issue. The Telegram connector does a few things, but it mostly builds events that were triggered by the chat. I feel that if you would like the ability to remove a user from a group, you could create a skill to do this following a command from an ADMIN or by the trigger of banned words.

You could use my [Twitch skill](https://github.com/FabioRosado/skill-twitch/blob/master/__init__.py#L55:L59) as an example. Let me know if that helps

**Comment by thechawla225** [comment]
Thanks a lot @FabioRosado I will try to do as u suggested.
