### ISSUE TITLE
Not really an issue or a bug... just an assignment I had!

### ISSUE THREAD

**Issue by gxomalis** [opsdroid/opsdroid#1782]
# Description
Hello there! I have this assignment in university where I pick an open source project and analyze some metrics about it. I chose opsdroid as it seems very exciting, and i analyzed File Type metrics based on LOC(via MetricsRealoded in PyCharm). Overall the results where great there's nothing to worry about (for now at least). File types with the most lines where Python files(34k lines), gettext PO files(8.5k lines), Text files (8.4k files) and Markdown files(4k lines).
I really liked the whole process and this project, it's a very good idea.
I wish you all the best of luck!  Hope to see opsdroid become famous in the future.

**Comment by jacobtomlinson** [comment]
Many thanks! Good luck with your assignment.
