### ISSUE TITLE
Slash commands do not work

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1787]
# Description

Using slash commands do not work. There is no event type for them, no docs on using them and opsdroid seems to error if you try.

## Steps to Reproduce

- Create a slash command for your bot
- Use the slash command in Slack
- See opsdroid output

## Expected Functionality

An event should be triggered which can be matched with `match_event`.

## Experienced Functionality

```
EBUG slack_sdk.socket_mode.aiohttp: Received message (type: TEXT, data: {"envelope_id":"c98bb0d2-2522-49e4-ae77-f453bc25055a","payload":{"token":"uLr3No9RxHh6kKW2DbbPMrtK","team_id":"T033XLNMP","team_domain":"jacobtomlinson","channel_id":"D01RFGW6QN9","channel_name":"directmessage","user_id":"U033XLNMR","user_name":"jacobtomlinson","command":"\/opsdroid","text":"","api_app_id":"A01R3RSRBMM","is_enterprise_install":"false","response_url":"https:\/\/hooks.slack.com\/commands\/T033XLNMP\/2212151098501\/CWmAvXOf6OphspoPEPaLyjVz","trigger_id":"2227832050993.3133702737.e40bf7f6909be8a7b97c5cda5b226627"},"type":"slash_commands","accepts_response_payload":true}, extra: )
DEBUG slack_sdk.socket_mode.aiohttp: A new message enqueued (current queue size: 1)
DEBUG slack_sdk.socket_mode.aiohttp: Message processing started (type: slash_commands, envelope_id: c98bb0d2-2522-49e4-ae77-f453bc25055a)
DEBUG slack_sdk.socket_mode.aiohttp: Sending a message: {"envelope_id": "c98bb0d2-2522-49e4-ae77-f453bc25055a"}
ERROR slack_sdk.socket_mode.aiohttp: Failed to run a request listener: local variable 'event' referenced before assignment
Traceback (most recent call last):
  File "/Users/jacob/mambaforge/envs/opsdroid/lib/python3.8/site-packages/slack_sdk/socket_mode/async_client.py", line 133, in run_message_listeners
    await listener(self, request)
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/connector/slack/connector.py", line 166, in socket_event_handler
    await self.event_handler(payload)
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/connector/slack/connector.py", line 147, in event_handler
    if isinstance(event, list):
UnboundLocalError: local variable 'event' referenced before assignment
DEBUG slack_sdk.socket_mode.aiohttp: Message processing completed (type: slash_commands, envelope_id: c98bb0d2-2522-49e4-ae77-f453bc25055a)
```

## Versions
- **Opsdroid version:** 0.22.0
- **Python version:** 0.3.8
- **OS/Docker version:** macos 11.2.3

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by ajitdsa** [comment]
This is great, thank you for creating this. I would like to add a little context so that the best value can be achieved when adding this feature. It is common for someone to create a slash command with an additional subcommand. However, the subcommand is typically hidden within the text following the command itself. So for example:

```
/command subcommand
```
or
```
/command subcommand parameter1 parameter2 etc
```
or
```
/command whatever the heck you want here
```

And it turns out this is returned in the response in the `command` and `text` keys respectively.

So it would be helpful to support being able to match on the command itself, and then have an additional regex match for the text key.
