### ISSUE TITLE
Change pipeline name and link in "making a release"

### ISSUE THREAD

**Issue by Sleuth56** [opsdroid/opsdroid#1789]
This page is outdated. https://docs.opsdroid.dev/en/stable/maintaining/making-a-release.html
From what I can see it needs changed to we use github CI for our build system and use this link. https://github.com/opsdroid/opsdroid/actions
I'll probably make this change my self when I start looking at updating parts of the docs. If you know for sure that what I'm saying is correct please thumbs up this post or comment on it so I know.

**Comment by jacobtomlinson** [comment]
Moving this over here as the docs live in this repo. Would be very happy to review PRs to resolve this.

**Comment by Sleuth56** [comment]
Ok, didn't know they were here. Maybe the old docs repo should be archived then?

**Comment by jacobtomlinson** [comment]
You comments on the website repo (https://opsdroid.dev), not the docs repo. Docs have always lived here.
