### ISSUE TITLE
Contribute link not working

### ISSUE THREAD

**Issue by aasim-syed** [opsdroid/opsdroid#1816]
Tried to click on contribute it doesnt show a correct page.
![image](https://user-images.githubusercontent.com/70385414/128608844-67a80f6c-145d-4893-af2d-d94f00fe91ef.png)

**Comment by jacobtomlinson** [comment]
Where was the contribute link that you clicked?

**Comment by aasim-syed** [comment]
> Where was the contribute link that you clicked?

In the README.md
![image](https://user-images.githubusercontent.com/70385414/128900667-70e6551b-a091-4f66-9518-d362dd78991e.png)
