### ISSUE TITLE
Install failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by yypptest** [opsdroid/opsdroid#1829]
# Description
I'm new to opsdroid, install opsdroid failed after the step `sudo pip3 install opsdroid[common]`, error is shown as below on Ubuntu 18.04.5 LTS (Bionic Beaver)
```
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->nbconvert>=5.6.1->opsdroid[common]) (5.1.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->click>=7.1.2->opsdroid[common]) (3.5.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->bleach>=3.1.5->opsdroid[common]) (2.4.7)
Installing collected packages: argparse, pyyaml, pycryptodome, pycron, puremagic, parse, opsdroid-get-image-size, nbconvert, logbook, h2, h11, get-video-properties, future, dataclasses, click, bitstring, Babel, arrow, appdirs, aiohttp-socks, aiofiles, slack-sdk, opsdroid, matrix-nio, emoji, certifi, aiosqlite
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

And is there platforms support matrix available for reference? I noticed only Ubuntu 16.04 is mentioned in the installation guide, not sure if opsdroid supports the newer version of Ubuntu (18.04 and 20.04), and other Linux OS (i.e RedHat), and other arch (i.e zLinux, pLinux)? 
https://docs.opsdroid.dev/en/stable/installation.html#installation-methods

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.

## Expected Functionality
Explain what should happen.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:** 0.23.0
- **Python version:** Python 3.6.9
- **OS/Docker version:** Ubuntu 18.04.5 LTS

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by FabioRosado** [comment]
From that snippet that you shared with us it seems that you already have pyyaml installed locally with the version 3.12 but we are specifying anything bigger than 5.3.1. 

https://github.com/opsdroid/opsdroid/blob/e806de3b2533f8f7ac233c8ece5ffc0e7d76bbda/setup.cfg#L58

It seems that pyyaml might have come with your distro or perhaps was installed with elevated privileges. You could try using pipenv/conda/virtualenv to create a new virtual environment and see if that fixes the issue for you.

**Comment by yypptest** [comment]
@FabioRosado, pipenv seems not work, and I resolved this issue by running below command to upgrade the pyyaml package
```
sudo pip3 install pyyaml --upgrade --ignore-installed pyyaml  
```

**Comment by yypptest** [comment]
I still have a question for the support matrix, is there platform/OS support matrix available for reference? 

I noticed only Ubuntu 16.04 is mentioned in the installation guide, not sure if opsdroid supports the newer version of Ubuntu (18.04 and 20.04), and other Linux OS (i.e RedHat), and other arch (i.e zLinux, pLinux)?
https://docs.opsdroid.dev/en/stable/installation.html#installation-methods

**Comment by FabioRosado** [comment]
Thank you for the update, glad that this works. I suspect that we should be able to support Ubuntu 18.04 but perhaps @Cadair  might know better on the Matrix front?

Opsdroid should work in any version of Ubuntu and our docs might be outdated, do you think this is something that you would like to contribute?

**Comment by jacobtomlinson** [comment]
We have a [Python version support page](https://docs.opsdroid.dev/en/stable/maintaining/supported-python-versions.html#support-table).

We test on Linux (ubuntu), macos and Windows on x86_64. But Opsdroid is pure Python so if you can install the dependencies it should run.

For Kubernetes you can just use the [Opsdroid Docker image](https://hub.docker.com/r/opsdroid/opsdroid). We do have a [helm chart](https://github.com/opsdroid/helm-chart), although it may be a little out of date.

**Comment by Satishmane-mit** [comment]
i think the error is in PyYaml file cause it shows this "Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall." and i think this time to configure PyYaml file again

**Comment by yypptest** [comment]
Thanks for all your response. The original issue is resolved, so close this issue.
