### ISSUE TITLE
Merge connectors and databases into the main project

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#185]
One solution for handling versioning the connector and database modules would be to merge them into the main project.

## Pros
* Modules will be updated inline with opsdroid
* Reduce complexity of the loader
* Combined documentation

## Cons
* Reduce flexibility of third-party modules
* Complex testing or testing exceptions
* More dependancies for the main project

**Comment by go8ose** [comment]
I like this idea.  Especially for connectors. opsdroid is not useful without connectors.  It's arguable that the same is true for databases.  So you'd expect the core package to include the things that make the software useful.

Perhaps core connectors and databases should have a requirement that they don't add unnecessary dependancies.  For the databases, that means the core databases would be included, you might want to have a fairly small number of official databases that are in core.

For connectors you might say that you don't use third party API libraries, you require the connector to use an existing dependancy.  That might make writing the core connectors a little harder, but perhaps that is ok.

To maintain flexibility for users that want more connectors and databases you could continue to support the current approach.  Or require the non-core connector/database to be pip installed.

I only just learned about this project yesterday, so all my opinions should be taken with a large grain of salt. But I as you hadn't had any responses for awhile on this, I figured I'd give my two cents worth.

**Comment by jacobtomlinson** [comment]
@go8ose again sorry I hadn't seen this comment, I think I missed a load of notifications a while back.

Now that you've become more familiar with the project and we've had more discussions how do you feel about this? Do you still agree with what you wrote above?

**Comment by go8ose** [comment]
I've changed thoughts a little bit. Let me first declare that I still find the dynamic importing in opsdroid to be a bit novel.  I've not noticed that being done elsewhere (but you can tell by my github stars I'm not a serious developer).  I can see the advantage for skills. This approach makes it simpler for users to add skills to their bot, all they need to do is alter a configuration file.  They don't have to re-deploy their opsdroid.

But the project is called "opsdroid", so I'm assuming it's for "Ops" people, who should be capable of dealing with installing dependancies, or using tooling that installs dependancies.  And restarting their bot when they do so. 

Hence I don't think there is a problem with having all the connector and database modules in core, and therefore having a project that pulls in extra dependancies when you pip install it. And given how you'd expect the connector and database modules to change less frequently, even for 3rd party modules I don't think you'd need to dynamically load them.  If people want to write new ones and use them, that's great.  But they can pip install them.

To be helpful, in that case the opsdroid project should try to have a stable API for them to develop against, manage that API along with the released version numbers, and announce changes to that API in a changelog document.  Though perhaps all that extra management could wait until after a 1.0.0 version.

As for what I wrote about avoiding 3rd party dependancies, I've changed my mind on that. Doing so would probably add a lot more work for opsdroid developers.  That sounds like a large disadvantage, with only a small advantage (that of reduced dependancies).  The python ecosystem has tooling for managing dependancies, so why wouldn't we use them?

**Comment by jacobtomlinson** [comment]
Thanks for the thorough response, it's really useful!

My initial idea for module installation was inspired by hubot. In hubot you install new adapters and database modules by installing separate packages on the same system as hubot, then when it starts it looks for all node modules with `hubot-` at the beginning and loads them, you also have to set environment variables to pass config to the bot. I wasn't particularly impressed by this as it isn't obvious at first glance how your hubot is configured, there is no central place for config and debugging. So I decided to give opsdroid the config file which is the single place to configure your bot. The goal is for people to install opsdroid, edit the config and then run it, with no additional pip installing of things. When things go wrong it is obvious where to look.

This has lead to the dynamic loading of modules and their dependancies, which I both love and hate at the same time. It feels like it is hugely reinventing the wheel and a hack of the python package management system, it introduces issues like #92 and #102 which pip and conda solved a long time ago. It does however provide the simplicity and flexibility, from a user point of view, that I was trying to achieve.

As you say above, connetors and databases are going to be fairly static. Once you've configured them you're probably not going to touch them again unless you really have to, but you will probably add and remove skills more frequently. It is also unlikely there would be a requirement for duplicate connectors, once Slack is done it's done and there is no benefit in someone writing another. So incorporating them into the core project makes sense from that angle.

I am concerned that moving them into the core code increases the barrier to entry for people who just want to hack together a quick connector for their obscure chat platform. I also wanted to empower people who perhaps have a custom or proprietary chat platform within their organisation and don't want to release their connector on GitHub.

I would be really interested to hear what @SolarDrew has to say as he recently implemented the matrix connector. Drew, do you think that if you were required to raise a PR against the core opsdroid project in order to add matrix support you would still have done it?

**Comment by go8ose** [comment]
I like the model that the [saltstack](https://saltstack.com/community/) project has.  Everything is in "core", (and hence lots of dependancies), but it's also possible to easily add your own external modules.  This means when you go to use it, all the core stuff just works, it's already installed.  People get to develop their own things and keep it private.  But it's easy for them to contribute it to the core project later on if they want.

Saltstack have good documentation on writing your own "execution modules" at https://docs.saltstack.com/en/latest/ref/modules/.  In saltstack they don't do git cloning for you, it's up to the users to deploy the code to the right place.

I think if in opsdroid we had documentation that said what directories to put your custom database and connector modules into, we'd be fine.  This could be controlled by the configuration file, but also have some sensible defaults (that perhaps mimic where the configuration files is searched for).   I.e. by default in configuration.yaml we could have a "module-search-path" that defaults to:
 ./opsdroid-modules:~/.opsdroid/modules:/etc/opsdroid/modules

**Comment by jacobtomlinson** [comment]
Yeah that does sound like it could be a good approach. From a developer perspective it doesn't sound any more complex. From a user perspective I think using custom modules would become harder, but using core modules would be easier. This could be a fair tradeoff!

I definitely want skills to maintain the current approach of dynamic installation though. And therefore perhaps it makes more sense for connectors and databases to be consistent with that.

I'm definitely still conflicted 😆

**Comment by SolarDrew** [comment]
I would have just opened a PR, yes, but I'm not new to open source so that may not be representative of many other new contributors. You might be able to reduce the barrier to entry a little by linking to some basic git/GitHub tutorials in the docs.

I agree it makes some sense for connectors and databases to have the same installation process as skills, but on the other hand they are far more integral to the basic functioning, so it also makes sense to me that when you install opsdroid you just get all the connectors. I think people will get used to "connectors come with the bot, skills don't" fairly relatively quickly.
