### ISSUE TITLE
pip install opsdroid[all] doesn't work 

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1857]
The insanity needed to make the [teams connector](https://github.com/opsdroid/opsdroid/blob/master/setup.cfg#L96-L105) work has broken people's ability to pip install opsdroid as specified in our getting started docs:

```
pip install "opsdroid[all]"
Collecting opsdroid[all]
  Downloading opsdroid-0.24.1.tar.gz (308 kB)
     |████████████████████████████████| 308 kB 4.3 MB/s            
  Preparing metadata (setup.py) ... done
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
opsdroid depends on botbuilder_core@ https://github.com/opsdroid/wheels-for-teams-connector/releases/download/4.11.0/botbuilder_core-4.11.0-py3-none-any.whl
```

This is *baaadddd* :wink: 

---
tbh I kinda feel like we never should have published a release to PyPI with this like this but :shrug:

**Comment by arusahni** [comment]
A temporary workaround could be to update the documentation to encourage installing the connector they need (e.g., `opsdroid[connector_slack]`) instead of `[all]`. Of course, this doesn't help those trying to integrate with Teams.
