### ISSUE TITLE
Add a gitlab connector to opsdroid

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#1861]
At work, we use opsdroid for some things like nuking cloud accounts so devs can test things with a fresh account every time. We have moved to gitlab a couple months ago and would like to expand our use of opsdroid to automate some of our workflows.

With this in mind, we should add a gitlab connector to opsdroid so we can get events from gitlab and create skills based on those events.

**Comment by jacobtomlinson** [comment]
Sounds great!

**Comment by FabioRosado** [comment]
Did some good initial progress on this, building the events from the payload now
