### ISSUE TITLE
Looking for Teams Service Endpoints in Mongo database forces error when no endpoints found within specified Mongo collection

### ISSUE THREAD

**Issue by bparbhu** [opsdroid/opsdroid#1863]
Hi all,

So I'm getting an error when using both teams and a mongo database. The database uses the new SRV protocol which has been added recently, much thanks to @jacobtomlinson  and @FabioRosado  for helping by adding functionality for that. The teams connector also goes through the new developer portal. So my bot and app are done through that versus the former app studio method they used before.

I'm also doing my opsdroid deployment through docker swarm. 

For some reason Microsoft teams is looking for teams service endpoints within the specified collection I use within my config.
The error pasted below errors out when opsdroid is looking for those endpoints but can't find them within the mongodb collection.

![opsdroid error print out](https://user-images.githubusercontent.com/7581178/141191140-8361611c-a1ba-45cc-80c9-0ad519017b36.png)

**Comment by bparbhu** [comment]
I'm not exactly sure what might be causing the error, if it's something teams related due to the new developer portal or mongo-related.

**Comment by jacobtomlinson** [comment]
Ah this is interesting. This is happening because connectors are started before databases, and teams is trying to use a database during startup.

**Comment by bparbhu** [comment]
So I think this is still happening even with the connectors starting before databases.
I just tried this again with pulling in the latest changes into a new docker image and deploying again.
![opsdroid teams connector error](https://user-images.githubusercontent.com/7581178/142295560-a055328c-eec3-4fe2-bda8-403a2f5cea75.png)

**Comment by jacobtomlinson** [comment]
That looks like a separate error, would you mind opening a new issue? Also could you copy the actual log into the issue (and wrap it in triple backticks) rather than sharing a screenshot. Makes debugging much easier.

**Comment by bparbhu** [comment]
Ah ok, I will post it as a separate error then. Sorry about that @jacobtomlinson, my fault. I'll make the post now.
