### ISSUE TITLE
How to load custom events that added by custom connector?

### ISSUE THREAD

**Issue by st01cs** [opsdroid/opsdroid#1870]
I created a custom connector for our IM, and loads connector by configuration. Therer are several events defined by this connector. I found that connector and skill path dose not include opsdroid_modules. 

So how can I load those events?

**Comment by FabioRosado** [comment]
Hello, do you have your connector somewhere public? If not, you might want to look at the [docs on match_event](https://docs.opsdroid.dev/en/stable/skills/matchers/event.html?highlight=match_event#example) if you haven't already.

Providing that your custom connector is emitting events in a similar way as how we are doing for the core events, for example:

https://github.com/opsdroid/opsdroid/blob/d22d8e329dc1ad5dfdf3a6a45f5269e7f80196c8/opsdroid/connector/github/__init__.py#L233

You should be able to do something like:

```python
from opsdroid.skill import Skill
from opsdroid.matchers import match_event
from opsdroid.events import Image, Message

class MySkill(Skill):
    @match_event(<your custom event here>)
    def my_skill(self, event):
       <do things with event>
```

**Comment by jacobtomlinson** [comment]
Awesome to hear you have built a custom connector! I would recommend that you make your connector a full Python module that you can import yourself, that way you can import whatever you need from it within your skills.

For example if you called it `super_awesome_connector` in the `setup.py`/`pyproj.toml` then you would configure it like this:

```yaml
connectors:
  super_awesome_connector:
    module: super_awesome_connector
```

Then you can import events in your skill like this:

```python
from opsdroid.skill import Skill
from opsdroid.matchers import match_event
from super_awesome_connector import SuperAwesomeEvent

class MySkill(Skill):
    @match_event(SuperAwesomeEvent)
    def my_skill(self, event):
        # Do the things!
```

**Comment by st01cs** [comment]
Thanks for your help! 

I used @jacobtomlinson solution.
