### ISSUE TITLE
Intent matching loop occurs when Opsdroid is used in conjunction with Rasa NLU-only server

### ISSUE THREAD

**Issue by bparbhu** [opsdroid/opsdroid#1876]
Hey guys,

So in setting up my soon to be opsdroid-rasa swarm I started testing it out with just a docker-compose file.
I'm using a Rasa NLU-only server because I train my Rasa models elsewhere and I also just want my containers to serve up 
the model that's trained already.

I'm also using the telegram connector as well.

I started testing out my skill and I'm trying to just trigger a greet intent which I will include as an attachment.
The skill gets loaded and I don't get any errors in regards to opsdroid or rasa but I do get into a loop with
get_ranked_skills.  I'm more curious as to what opsdroid is doing when stuck in the loop as it should be trying to match a response based on the intent but it gets put into a loop of some sort instead of erroring out or telling me that there was no intent found.

I have included my skill example, my docker compose, the rasa nlu intent file, and my opsdroid config.

More curious if I'm doing something completely wrong as well with this kind of setup.

Thanks again,

-Brian
[opsdroid-config-example.txt](https://github.com/opsdroid/opsdroid/files/7715672/opsdroid-config-example.txt)
[hello_example.txt](https://github.com/opsdroid/opsdroid/files/7715673/hello_example.txt)
[rasa-greet-example.txt](https://github.com/opsdroid/opsdroid/files/7715674/rasa-greet-example.txt)
[docker-compose old.txt](https://github.com/opsdroid/opsdroid/files/7715675/docker-compose.old.txt)
[opsdroid-rasa-loop.txt](https://github.com/opsdroid/opsdroid/files/7715715/opsdroid-rasa-loop.txt)

**Comment by jacobtomlinson** [comment]
The strange thing about that loop is each iteration seems to be about 30 seconds apart, which is a very long time for opsdroid ot be hanging around, and is oddly regular. I wonder if Telegram is trying to redeliver the message because we aren't giving the correct response.

@FabioRosado do you have any thoughts on this?

**Comment by bparbhu** [comment]
I also ran into a similar problem with webex teams today as well. I included the output from opsdroid and rasa.
[opsdroid_webex_rasa_loop.txt](https://github.com/opsdroid/opsdroid/files/7723448/opsdroid_webex_rasa_loop.txt)

**Comment by bparbhu** [comment]
Both of these connectors also expose themselves to the internet and go through ngrok tunneling services.

**Comment by bparbhu** [comment]
Also, let me know if you guys need anything from me as well to help out with this. More than happy to help.

**Comment by FabioRosado** [comment]
Sorry just look at this now. I started by looking at the webex logs and it seems that the message was sent by direct message perhaps? if that's the case I don't think the webex connector accepts direct messages.

From the telegram I can't see anything in the logs and agreed the 30 seconds delay is weird. We are always returning a 200 from the webhook so that should work.

@bparbhu can you provide full logs in debug mode so I can dig deeper into what's happening? thanks!

**Comment by bparbhu** [comment]
Sure thing @FabioRosado , I'll do another try with telegram and give you my log in debug mode.

**Comment by bparbhu** [comment]
So I don't think this is telegram related. I started looking more into this by just doing logging statements in debug mode from when the get_ranked_skills function kicks off to the parse_rasanlu and then call_rasanlu function within the rasa parser code base. The thing that isn't getting triggered which hangs is post response within the the call_rasanlu function. It never completes or just hangs even when specifiying a large timeout window. I included my debug log which is using webex teams.

**Comment by bparbhu** [comment]
Here's the function as I added the log
```
async def call_rasanlu(text, config):
    """Call the Rasa NLU api and return the response."""
    async with aiohttp.ClientSession(trust_env=True) as session:
        headers = {}
        data = {"text": text}
        url = config.get("url", RASANLU_DEFAULT_URL) + "/model/parse"
        _LOGGER.debug(_(url))
        if "token" in config:
            url += "?&token={}".format(config["token"])
        try:
            _LOGGER.debug(_("Rasa NLU is posting data..."))
            resp = await session.post(url, data=json.dumps(data), headers=headers,timeout=300000000)
            print(resp.status)
        except aiohttp.client_exceptions.ClientConnectorError:
            _LOGGER.error(_("Unable to connect to Rasa NLU."))
            return None
        if resp.status == 200:
            result = await resp.json()
            _LOGGER.debug(_("Rasa NLU response - %s."), json.dumps(result))
        else:
            result = await resp.text()
            _LOGGER.error(_("Bad Rasa NLU response - %s."), result)
        _LOGGER.debug(_("Rasa NLU gave a result..."))
        return result
```

**Comment by bparbhu** [comment]
So taking things a bit further. I started making some changes to the core.py script under the train_parsers section. I added another method in the rasanlu parser code base for using pretrained models. Many if not most of the functions I'm calling are within the opdroid codebase. This is what the function looks like. Though, I could still use some help in getting this to work. It looks like the model gets detected and initialized into memory but when it comes to parsing the text from an input the call_rasanlu function still hangs. Just trying to sort this last piece out. I'm open to suggestions.

```
async def use_pretrained_model(config):
    """Use a Rasa Pre-trained model on the loaded skills"""
    _LOGGER.info(_("Let's use your Rasa pre-trained model"))
    _LOGGER.debug(_("Now Checking your Rasa NLU compatibility with OpsDroid"))
    await _check_rasanlu_compatibility(config)
    _LOGGER.debug(_("Now Seeing if your Rasa model is loaded properly"))
    if await _is_model_loaded(config):
        await _init_model(config)
        _LOGGER.info(_("Successfully loaded Rasa NLU model."))
        return True
    else:
        _LOGGER.error(_("Failed getting Rasa NLU server status."))
        return False
```

**Comment by bparbhu** [comment]
The core.py addition looks like this.

```
    async def train_parsers(self, skills):
        """Train the parsers.
        Args:
            skills (list): A list of all the loaded skills.
        """
        if "parsers" in self.modules:
            parsers = self.modules.get("parsers", {})
            rasanlu = get_parser_config("rasanlu", parsers)
            if rasanlu and rasanlu["enabled"] and rasanlu.get("train", True):
                await train_rasanlu(rasanlu, skills)
            elif rasanlu and rasanlu["enabled"]:
                await use_pretrained_model(rasanlu)
            else:
                raise AssertionError("Pick a valid training mode")
```
