### ISSUE TITLE
Get multiple responses for one slack input command

### ISSUE THREAD

**Issue by yypptest** [opsdroid/opsdroid#1890]
# Description
Using opsdroid with slack connector, there will be multiple responses for one slack input command.  From the debugging log, the same command is been detected and parsed for several times by opsdroid. 

After investigation, it seems the slack will retry if the server took longer than 3 seconds to respond to the previous event delivery attempt (https://api.slack.com/apis/connections/events-api#graceful_retries). Similar with the issue mentioned here https://github.com/slackapi/python-slack-sdk/issues/335

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.

## Expected Functionality
Expect opsdroid could provide a config setting for slack to acknowledge the slack API once the command is detected. 

## Experienced Functionality
Get multiple responses for one slack input command.

## Versions
- **Opsdroid version:** 0.24.1
- **Python version:**  3.8
- **OS/Docker version:** Redhat 8

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.

```

**Comment by martinohmann** [comment]
We also ran into this issue. The slack docs note that one should ack the event before processing it. Right now, it's the other way around in opsdroid:

> Respond to events with a HTTP 200 OK as soon as you can. Avoid actually processing and reacting to events within the same process. Implement a queue to handle inbound events after they are received.

https://api.slack.com/apis/connections/events-api#the-events-api__responding-to-events

**Comment by yypptest** [comment]
@FabioRosado Do you have an estimates when the next opsdroid release is planned? Thanks!

**Comment by FabioRosado** [comment]
Hey @yypptest  I've opened up an PR to address a small bug in the slack connector. Once that's in I'll try to do a release unless one of the maintainers beats me to it 😄

**Comment by yypptest** [comment]
@FabioRosado that's great, thank you!
