### ISSUE TITLE
Feature Request: Suggest implementing 'modal' support for the Slack connector

### ISSUE THREAD

**Issue by yypptest** [opsdroid/opsdroid#1891]
# Description
I'm developing the skill with slack connector, and need to using 'modal' type in the skill to temporarily displaying dynamic and interactive information. So suggest opsdroid slack connector to have the capability to send a message as 'modal' type and handle the respond of the modal. 

## Expected Functionality
The slack connector is able to send a message as 'modal' type and handle the respond of the modal. 

## Experienced Functionality
when I attempted to send message using the type `Modal` which is provided by Slack, I got the error as below.  It seems the modal type is not supported yet. 
```
The server responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['unsupported type: modal [json-pointer:/blocks/0/type]'], 'response_metadata': {'messages': ['[ERROR] unsupported type: modal [json-pointer:/blocks/0/type]']}}
```

## Versions
- **Opsdroid version:** 0.24.1
- **Python version:** 3.8
- **OS/Docker version:** Redhat 8

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by FabioRosado** [comment]
@yypptest  apologies for the delay in getting back to you, I've just tested this and it seems we can fix the problem by passing the `"type": "modal"` to the API and it should work.

I'm going to add a new events for Modals that will contain this, when I tested the modal opsdroid submitted the blocks in the channel. Do you have a minimal reproducible example so I don't have to create a dummy test to confirm it works?

Thank you!

**Comment by yypptest** [comment]
Sorry I just noticed your message. 

Actually I just tried with the modal type last month with the example provided by slack to see if it's supported. Maybe you can also try with the example here https://api.slack.com/surfaces/modals/using

**Comment by chillipeper** [comment]
hey all, I had a while ago some code that covers this issue but did not find cycles to work on it. Hopefully, it's useful. FWIW this code has been running already for a couple of months on my local instance without any issues.
