### ISSUE TITLE
Message replies using Blocks in a thread end up outside of the thread even when start-thread: true

### ISSUE THREAD

**Issue by rodrigo-albuquerque** [opsdroid/opsdroid#1896]
# Description
When start-thread: true in configuration.yaml, regular text replies do end up in the thread. Fine.

However, the same reply inside of Blocks() construct, end up outside of the thread in a new message in the channel.

This is not expected.

## Steps to Reproduce
1) Set start-thread: true in configuration.yaml
2) Write the first message, then, create a thread inside of this message saying "hi" with the following code:

message.respond here will reply in a thread as expected:

```python
import random

from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class HelloSkill(Skill):

    @match_regex(r'hi|hello|hey|hallo', case_sensitive=False)
    async def hello(self, message):
        await message.respond('Hello!')
```

message.respond here will NOT reply in a thread (just because we're. using "Blocks"?):

```python
import random

from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class HelloSkill(Skill):

    @match_regex(r'hi|hello|hey|hallo', case_sensitive=False)
    async def hello(self, message):
        await message.respond(Blocks([
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "Hey! I'm opsdroid.\nI'm a natural language event driven automation bot framework.\n*What a mouthful!*"
                    },
                    "accessory": {
                        "type": "image",
                        "image_url": "https://raw.githubusercontent.com/opsdroid/style-guidelines/master/logos/logo-light.png",
                        "alt_text": "opsdroid logo"
                    }
                },
                {
                    "type": "actions",
                    "elements": [
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "Visit website",
                                "emoji": True
                            },
                            "url": "https://opsdroid.dev"
                        }
                    ]
                }
            ]
        ))
```

## Expected Functionality
message.respond(Blocks[...]) should reply in a thread when user types "hi" inside of a thread and start-thread: true is set in configuration.yaml

**Comment by FabioRosado** [comment]
I started working on this, but I can't give you a date were I will have it done by.
Just wondering, would it make sense to add another config arg to set "start-thread-blocks" to true/false so users can stop opsdroid from replying to blocks only if they want?

**Comment by rodrigo-albuquerque** [comment]
If there's a use case for this then yeah but in my case the reason I set start-thread: true is because I want *ALL* replies within a thread. No exceptions. I'm not sure who would want a thread not to be started just because they're using blocks. However, if you feel like there's a good use case for this kind of implementation, then go for it :)

**Comment by yypptest** [comment]
I have problem to enable one thread for non Block response message with `start-thread: True` in configuration.yaml, it's for the same hello skill. 

And I'm using Event API as backend, not sure if `start-thread` works with this API?
```
import random

from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class HelloSkill(Skill):

    @match_regex(r'hi|hello|hey|hallo', case_sensitive=False)
    async def hello(self, message):
        await message.respond('Hello!')
```

**Comment by yypptest** [comment]
I have problem to enable one thread for non Block response message with `start-thread: True` in configuration.yaml, it's for the same hello skill. 

And I'm using Event API as backend, not sure if `start-thread` works with this API?
```
import random

from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class HelloSkill(Skill):

    @match_regex(r'hi|hello|hey|hallo', case_sensitive=False)
    async def hello(self, message):
        await message.respond('Hello!')
```

**Comment by FabioRosado** [comment]
@rodrigo-albuquerque  apologies that this took me way longer than it should! The fix was pretty easy and I've opened up the PR to address this. I've decided to just keep it simple and use the `start-thread`, if folks complain that they don't want blocks to reply in a thread then we can add some logic after 😄
