### ISSUE TITLE
Event responses from a button end up outside of a thread even though start-thread = true

### ISSUE THREAD

**Issue by rodrigo-albuquerque** [opsdroid/opsdroid#1905]
# Description

When start-thread: true in configuration.yaml, replies using regular text or Blocks() construct end up inside of the thread, which is expected.

However, if the Blocks() construct has a button, the reply ends up outside of the thread in a new message in the channel.

# Steps to Reproduce:

0) set "start-thread: true" in configuration.yaml

1) Create a function that responds to a "hello" message using Blocks() with a button within a thread:

```python
class HelloCatcher(Skill):
    @match_regex(r'hello')
    async def my_first_reply(self, message):
        answer = \
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"Click me!"
                },
                "accessory": {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "New reply",
                        "emoji": True
                    },
                    "style": "primary",
                    "value": "create",
                    "action_id": "new",
                },
            } 
        await message.respond(Blocks(answer))
```

2) Create a reply for when we click on above button

```python
@match_event(BlockActions, value="create")
    async def my_reply(self, event):
        await event.respond('This will unexpectedly appear outside of the thread.')
```

This is not expected. 

The expected behaviour is for the reply in 2) to be within the same thread.

# Related 

Previously, an issue where Opsdroid wouldn't reply in a thread when using blocks was fixed (for reference).

Previous issue raised: https://github.com/opsdroid/opsdroid/issues/1896
Previous fix: https://github.com/opsdroid/opsdroid/commit/33241f2d74940e061fada8eee8d8238230593295

**Comment by rodrigo-albuquerque** [comment]
Hi Fabio, quick question. Is this somehow related to the other issue where Block replies ended up outside of a thread?

**Comment by FabioRosado** [comment]
> Hi Fabio, quick question. Is this somehow related to the other issue where Block replies ended up outside of a thread?

It is somewhat related to that yet, but we are doing some 'odd' things with the event from the button click and when I had a quick look, I couldn't figure out what was happening there 😅
