### ISSUE TITLE
Stickers form closed

### ISSUE THREAD

**Issue by jaas666** [opsdroid/opsdroid#1918]
# Description

[Contribution page](https://github.com/opsdroid/opsdroid/blob/master/docs/contributing/index.md) still mention stickers for contributors, yet the form is not accepting new entries.

Is the form closed permanently? Shall we remove the mention of the stickers if that's the case?

**Comment by FabioRosado** [comment]
Hello @jaas666  that's correct we aren't sending stickers at the moment I think we can remove this 😄
