### ISSUE TITLE
Broken links in documentation.

### ISSUE THREAD

**Issue by jaas666** [opsdroid/opsdroid#1922]
# Description
I've found some broken links in the documentation but most of them are simply missing the .md extension. After submitting a couple PR's (#1917 #1919 #1921) to fix this I've come to the realization that they might not be mistakes.

Can someone confirm if the missing extension on the links from the documentation are on purpose? Like, they have to be like that to show correctly on the actual website or something?

Shall I continue "fixing" them to work on Github?

**Comment by jaas666** [comment]
Anyone?

**Comment by FabioRosado** [comment]
Hello @jaas666 I've confirmed that the docs still work on the latest version, so if you would like you can keep adding the extension to the link if it helps navigating the docs in github 😄

**Comment by jaas666** [comment]
Perfect.. I'll go through all of them today. Thanks
