### ISSUE TITLE
support to ssl handshake certification

### ISSUE THREAD

**Issue by yypptest** [opsdroid/opsdroid#1924]
# Description
We are using opsdroid as a bot with slack connector, and we enabled SSL. 

The security test report that no ssl handshake certification being passed, even there's no cert file provided from client side, the verification passed. Does opsdroid support two way certification? 

<img width="1180" alt="opsdroid-ssl" src="https://user-images.githubusercontent.com/64583929/168730692-422a01f8-8da8-4161-afd6-d509ec8edb00.png">

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.

## Expected Functionality
Explain what should happen.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:** 0.26.0
- **Python version:** 3.9
- **OS/Docker version:**  

## Configuration File
Please include your version of the configuration file below.

```yaml

# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by FabioRosado** [comment]
I haven't tested the SSL portion of opsdroid, but did you pass the ssl cert file and key to the configuration as the [docs mention](https://docs.opsdroid.dev/en/stable/configuration.html?highlight=ssl#web-server) ?

**Comment by yypptest** [comment]
yes, I did, and the opsdroid started with 8443 port.

**Comment by FabioRosado** [comment]
Great thank you for the clarification, I will poke at this and see what's happening 😄
