### ISSUE TITLE
Do we actually need openssh?

### ISSUE THREAD

**Issue by Sleuth56** [opsdroid/opsdroid#1945]
# Description
I was running Lynis against dockerfiles and it noticed that openssh was being installed in the opsdroid container. That's an odd package to have installed in a container. What is it for? I assume it's a dependency or it's left over from testing something.

## Versions
- **Opsdroid version:** v0.27.0
- **Python version:** N.A
- **OS/Docker version:** N.A

**Comment by jacobtomlinson** [comment]
Ping @Dissonant-Tech who added this in #1820.

**Comment by Sleuth56** [comment]
According to the Dockfile it's only installed on the build container. Thank you for the explanation. I am going to close this issue.
