### ISSUE TITLE
Idea for connector

### ISSUE THREAD

**Issue by ZoeyKats** [opsdroid/opsdroid#1978]
Hello i am interested in implementing a new connector that connects to the website https://www.horoscope.com/us/index.aspx
This website is a horoscope website and it could be used so that the user can learn information about their horoscope (daily, monthly, weekly or yearly). Are you interested in me implementing it?

**Comment by ZoeyKats** [comment]
Sure i will consider it! i will start working on it

**Comment by jacobtomlinson** [comment]
Closing this out as there is nothing to do here.
