### ISSUE TITLE
Create script to update automatically the config file with new skills 

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#214]
- Create a scripts directory in the root of the project.

- If a new skill is added, call the script (located in the scripts directory) in the Makefile and update the example_configuration.yaml automatically.

**Comment by vitkhab** [comment]
@FabioRosado "If a new skill is added" where? What should the script use as a source of truth? Should the script automatically detect new skills?
And what should the script put it into example_configuration.yaml? There might be lots of configuration associated with new skills.

I see next solution:
- Trigger to run script is to be defined
- On run script looks at https://github.com/opsdroid repos and gets set of "skill-*" repos
- It parses README.md and takes "Configuration" section from there
- It puts contents of "Configuration" into example_configuration.yaml

Please, correct me if I understood wrong.

**Comment by FabioRosado** [comment]
Hello @vitkhab, we created this issue when I updated the example_config file @jacobtomlinson  might have a better idea of what should be done, but I believe that you got it right.

Since opsdroid checks the  https://github.com/opsdroid repo to install the skills, I believe Jacob wanted the script to just update the example_config file with a new skill found there (probably just adding the comment bit `# <name of skill> (<repo url>)` and the `name: <skill name> ` should be a good starting point. 

Since some skills have required parameters that need to be included in the configuration, perhaps the script could capture this as well on the README.md of each skill?

**Comment by jacobtomlinson** [comment]
@FabioRosado @vitkhab 

Good question about when to trigger the script. I imagine this could be done at release as part of the the release documentation #110.

I think it would be awesome if it could scrape through the skills and pull out their config examples to make one big one. And as @FabioRosado said add the comments in the format of `# <name of skill> (<repo url>)`.

**Comment by vitkhab** [comment]
I made a PR with prototype. And these are my concerns:
- I can never be sure, that `Configuration` section provides working code. And it doesn't for https://github.com/opsdroid/skill-apiai#configuration . What should script do? Put not working example inside configuration or skip it or raise exception?
- I need set of skills uncommented by default. Now I'm taking it right from example_configuration.yaml. Is it okay?
- Still I need help with triggering the script. I didn't look into it yet.

**Comment by jacobtomlinson** [comment]
Nice one!

- I agree. I would raise an exception.
- I would create a constant at the beginning of the script with the uncommented skills. I would like this script to automatically update the `example_configuration.yaml` file as well as the `README.md`.
- I imagine this will be run manually by maintainers as part of the release process.
