### ISSUE TITLE
Log some getting started guidance on first run

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#215]
If a users starts opsdroid for the first time they will get a [default config file created](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/loader.py#L109) for them.

At the same time it might be nice to log some getting started information. Perhaps a pointer on how to install opsdroid desktop and a link to the getting started videos or the config reference.

**Comment by FabioRosado** [comment]
Would you like this to be added in the **main** and to be logged every time opsdroid is started or only when a default config file is created?
