### ISSUE TITLE
Add --load-config flag

### ISSUE THREAD

**Issue by gabeduke** [opsdroid/opsdroid#244]
Need a flag for installing local skill dependencies when running a dockerized app. Should call the install new requirements.txt from skills loaded by `path` without running the bot

**Comment by jacobtomlinson** [comment]
This flag basically needs to tell opsdroid to exit after running the [load method](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/__main__.py#L121).

This would allow you to install all modules and their dependancies without running opsdroid itself.

**Comment by betojulio** [comment]
Can I take this one?

**Comment by FabioRosado** [comment]
Hello @betojulio that would be great, please go ahead and submit a PR with this issue, if you need any help with anything you can ask us in [gitter](https://gitter.im/opsdroid/developers)

**Comment by betojulio** [comment]
Cool, thanks...
