### ISSUE TITLE
New Docker image should be built on every merge

### ISSUE THREAD

**Issue by gtseres** [opsdroid/opsdroid#246]
Having a look at [DockerHub](https://hub.docker.com/r/opsdroid/opsdroid/builds/) or inspecting the latest Docker image after pulling it, it seems that it has been created on the 20th of September (10 days ago). This means that the latest image does not contain any fixes that have been made to opsdroid after that date.

We could automatically build a new `opsdroid:latest` Docker image when a pull request is merged and push it to Dockerhub. Not sure how this can be tackled though, maybe [Github service hooks](https://docs.docker.com/docker-hub/github/#github-service-hooks) could help here.

**Comment by jacobtomlinson** [comment]
The `latest` tag is an alias to the latest official release (currently `v0.9.1`). If you're looking for an image which is equivalent to master you need the `dev` tag.
