### ISSUE TITLE
Update skills.md to reflect the changes in adding new skills

### ISSUE THREAD

**Issue by gtseres** [opsdroid/opsdroid#248]
After going through the [`skills.md`](https://github.com/opsdroid/opsdroid/blob/master/docs/extending/skills.md) documentation file and comparing it with a sample skill ([skill-hello](https://github.com/opsdroid/skill-google-it/blob/master/__init__.py)), there is a couple of things that may be outdated:
1. `__init__.py` should exist for a skill instead of `<skill_name>.py`
2. `match_regex` now exists in `opsdroid.matchers` instead of `opsdroid.skills`

**Comment by jacobtomlinson** [comment]
Definitely!

1. You can still use `<skill_name>.pu` but `__init__.py` is preferred
2. Yep!
