### ISSUE TITLE
Add wit.ai parser and matcher

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#253]
Add a parser and matcher for [wit.ai](https://wit.ai/), similar to the ones for api.ai ([parser](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/parsers/apiai.py), [matcher](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/matchers.py#L26)).

The parser needs to send the message text to wit.ai and then compare the skills loaded using the matcher against the response.

**Comment by FabioRosado** [comment]
I've checked wit.ai and they have a python library to work with their API so this should be easier to implement. I'll give it a try 👍

**Comment by jacobtomlinson** [comment]
Nice! Make sure it works with asyncio though. You may end up writing some blocking code which isn't good. It might be easier to use their API directly using `aiohttp` like the api.ai parser.

**Comment by FabioRosado** [comment]
Yeah, they don't work with asyncio so I will have to use the API. I'll try to swing it, I'll need to learn how to interact with API's properly anyway haha

**Comment by FabioRosado** [comment]
I forgot to mention  this issue on my PR. Is there anything else I need to add before we can close the issue?

**Comment by jacobtomlinson** [comment]
Yeah we should've referenced this in the PR. Closed now.
