### ISSUE TITLE
add a conversation parser/matcher workflow

### ISSUE THREAD

**Issue by go8ose** [opsdroid/opsdroid#261]
Instead of decorating a skill with a matcher, it would be nice if you can have a skill that registers a regex matcher temporarily.  Something like:

    @conversation()
    async def do_something_destructive(opsdroid, config, flow):
    
      await message =  flow.match_regex(r'delete (\w+)')
      delete_target = message.regex.group(1)
      await message.respond("Are you sure you want me to delete {}".format(delete_target)
      await message =  flow.or(
        flow.match_regex(r'yes|y|ya|ja'),
        flow.sleep(5),
      )
    
      if message.or_match() == 0:
        # dispatch some kind of action, await the result
        await message.respond("I have deleted {}".format(delete_target)
      elif message.or_match() == 1:
        await message.respond("I didn't get an answer from you in 5 seconds, maybe you should try again later")

What do you think?

**Comment by go8ose** [comment]
This looks like an alternative to #156.  I like my in-the-one-method approach, because I think it makes it easier to write.  But maybe that's because I'm used to an iterative programming style.

**Comment by jacobtomlinson** [comment]
Thank so for raising this. 

I dislike forcing people down specific flows on conversation. Conversations rarely follow an exact pattern and often change context mid flow. 

Using context adds more flexibility and allows each skill to exist in isolation but only be called when the appropriate chain of events have happened.

**Comment by jacobtomlinson** [comment]
Closed due to inactivity.
