### ISSUE TITLE
Add a test for `aiohttp.ClientOSError` exceptions in parsers

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#270]
In both the [api.ai](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/parsers/apiai.py#L43) and [LUIS](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/parsers/luisai.py#L39) parsers there is a `try ... except` block for an `aiohttp.ClientOSError` when contacting the API.

These lines are not covered in the tests. This needs adding.

**Comment by FabioRosado** [comment]
While browsing stackoverflow and checking the wit.ai test cases I came up with this:

```
    async def test_parse_witai_clientOSError(self):
        with OpsDroid() as opsdroid:
            opsdroid.config['parsers'] = [
                {'name': 'witai', 'access-token': 'test'}
            ]
            mock_skill = amock.CoroutineMock()
            match_witai('get_weather')(mock_skill)

            with amock.patch.object(witai, 'call_witai') as mocked_call_witai:
                mocked_call_witai.raiseError.ClientOSError = ClientOSError()

            self.assertTrue(ClientOSError)
```

This simply raises the ClientOSError and assets it to true. Would this be something worth using for this issue or I should put more thought into it?
