### ISSUE TITLE
Better logging when loading modules

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#281]
Currently when loading modules opsdroid tries to import a few different name variations to allow for different ways of writing modules.

When then module fails to import a line is logged stating so, however the next import may succeed resulting in the module loading but the logs looking as if it perhaps hasn't.

Perhaps logging should only occur when a module totally fails to load.

```
DEBUG opsdroid.loader: Installing homeassistant
DEBUG opsdroid.loader: Installed homeassistant to /Users/jacob/.opsdroid/modules/opsdroid-modules/skill/homeassistant
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.homeassistant.homeassistant
DEBUG opsdroid.loader: No module named 'opsdroid-modules.skill.homeassistant.homeassistant'
DEBUG opsdroid.loader: Loaded skill: opsdroid-modules.skill.homeassistant
```

**Comment by suprithIUB** [comment]
Hi Jacob, I'd like to work on this. I'll send a PR in few hours. Any suggestions on best way to test this?

**Comment by jacobtomlinson** [comment]
Reopened due to #290
