### ISSUE TITLE
Fixes to module imports breaks opsdroid

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#290]
# Description
After merging #287 starting opsdroid results in an error.

## Steps to Reproduce
- clone the latest master branch 
- `git checkout 177449b49165b317c51fd14fb5f95e5229f60538`
- `python -m opsdroid` 

## Expected Functionality
opsdroid should start

## Experienced Functionality
The following error occurs

```
Traceback (most recent call last):
  File "/Users/jacob/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jacob/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/__main__.py", line 134, in <module>
    main()
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/__main__.py", line 129, in main
    opsdroid.start_loop()
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/core.py", line 123, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/loader.py", line 206, in load_modules_from_config
    self._reload_modules(skills)
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/loader.py", line 128, in _reload_modules
    importlib.reload(module["module"])
  File "/Users/jacob/.pyenv/versions/3.5.1/lib/python3.5/importlib/__init__.py", line 147, in reload
    raise ImportError(msg.format(name), name=name)
ImportError: module opsdroid-modules.skill.hello not in sys.modules
```

## Versions
- **Opsdroid version:** v0.9.1-25-g177449b
- **Python version:** 3.5.1 and 3.5.4
- **OS/Docker version:** macOS 10.13

## Configuration File
Default config

## Additional Details
NA

**Comment by jacobtomlinson** [comment]
#289 will back out the PR for now.

@suprithIUB please could you take a look at this.

**Comment by suprithIUB** [comment]
Sure. I'll take a look

**Comment by suprithIUB** [comment]
Hi Jacob,

I tested opsdroid with python 3.6 and it works fine. I'll update the thread after verifying opdroid on 3.5.1 and 3.5.4.

**Comment by suprithIUB** [comment]
Hi Jacob, Quick question, Why are we reloading already imported modules? Many suggest against reloading the modules.

**Comment by jacobtomlinson** [comment]
The only modules being reloaded are not being imported into the namespace, they are using the import machinery to load them as an object. This mitigates many of the issues around reloading modules. The functionality is there to allow soft restarts of the application where opsdroid would load new versions of skills without restarting the application, this is particularly useful when developing skills.

**Comment by suprithIUB** [comment]
Do I have write access to resolve conflict? If not, please take a look and let me know if you are okay with changes.

**Comment by FabioRosado** [comment]
@suprithIUB  if you pull the changes from the main opsdroid repo with the command `pull upstream master` (provided that you have the main opsdroid repo set as a remote) you can resolve the conflicts in the opsdroid.loader. 

Once the conflicts have been resolved you should be able to push these onto your github repository and the PR should be updated with the new version.

Let me know if you need further help on this matter 👍
