### ISSUE TITLE
When installing modules from a git repo, make sure they are up to date on startup.

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#295]
Correct me if I am wrong but it appears that when you pull a component in using the `repo:` or in fact when it comes from the opsdroid org, when opsdroid starts it does not fetch updates to the repo?

Is this intended behaviour or something that could be changed?

**Comment by jacobtomlinson** [comment]
This is definitely desired functionality 😄 .

**Comment by afibanez** [comment]
I will do a PR with a proposal :smiley:

**Comment by afibanez** [comment]
So now we can close this issue :wink:
