### ISSUE TITLE
Clustering and parallelisation

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#299]
The initial design for opsdroid was for a singular instance to run and handle everything. However it would be interesting to explore how opsdroid could scale if it was required to handle large numbers of conversations.

## Connectors
Each connector interacts with the chat service in a slightly different way, but they broadly fall into two categories: 
- **Push** - the chat service sends messages to opsdroid via a REST API ([Facebook Messenger](https://github.com/opsdroid/connector-facebook), [Cisco Spark](https://github.com/opsdroid/connector-ciscospark))
- **Pull** - opsdroid routinely requests messages from a REST API ([Twitter](https://github.com/opsdroid/connector-twitter)) or consumes a websocket ([Slack](https://github.com/opsdroid/connector-slack)).

Any connector which uses the push method could be run in parallel behind a load balancer, provided that each opsdroid instance has the same database configured in order to share state between them. This would ensure each instance of opsdroid is stateless and any one of them can parse a message in an identical and reproducible way.

The downside of push connectors is it requires exposing your opsdroid instances to the internet (although you could mitigate risk by using your firewall to limit traffic to the specific chat services only). Some users may be individuals running opsdroid at home on a Raspberry Pi and it makes their life easier to use the pull method as they don't have to mess with their router config.

Some chat services such as Slack provide APIs for both [push](https://api.slack.com/events-api) and [pull](https://api.slack.com/rtm), although only pull is implemented in the connector at this time. Others just provide one or the other. Therefore it could be feasible to implement both methods for services which support them and then allow users to select one via the config.

## Cron
Each opsdroid instance keeps track of the time and triggers cron based skills. Therefore if you were to run a cluster of instances you would get duplicate cron skills running. Also if any connector is a pull connector then the same would happen and messages would be parsed multiple times.

To resolve this the opsdroid instances would need to know they were part of a cluster and hold elections to elect a master which would run these functions.

## What could we do?

Connectors could have properties to say whether they support push or pull, and for which mode they are currently running in.

We could add a config section to opsdroid which would allow the user to point the instance at a service discovery application such as [etcd](https://github.com/coreos/etcd) or [Consul](https://www.consul.io/) to handle dynamic clusters, or directly at each other for static clusters.

This way the instances could agree among themselves which one is going to honour the cron connection and which one should run the pull connectors if any have been specified. This way pull connectors could still be used in a scalable cluster, they will just be limited to one instance and will not scale. 

For connectors with both push and pull I feel it would be best for them to default to pull, change to push if the cluster config exists, but allow the user to override these in the config on a connector-by-connector basis.

**Comment by go8ose** [comment]
Clustering sounds like a very large feature to implement. Perhaps this is a good idea for a post 1.0 version, or maybe an enterprise version.

**Comment by suprithIUB** [comment]
I would love to work on this. I'll read some papers and get some ideas.

**Comment by jacobtomlinson** [comment]
Please feel free to do some research. As @go8ose says this is a large feature so we should discuss how you plan to tackle it before you make a start.

**Comment by jacobtomlinson** [comment]
Going to close this off for now. It can always be reopened if this comes up again.
