### ISSUE TITLE
For local skill files, no-cache should the default config?

### ISSUE THREAD

**Issue by sgreszcz** [opsdroid/opsdroid#310]
# Description

Not sure if caching for local skill files should be on by default as it is a bit confusing to not see changes to the skills being reflected in the functionality. I had to dig a bit to see that opsdroid was caching local files in ~/.opsdroid/modules. Totally makes sense for git repositories though where the lag would be a problem for quick parsing.

## Steps to Reproduce

1) Build a local skill - with bugs is better :)
2) Fix the bugs
3) Test again, and the same bugs are there
4) Reconfigure configuration.yaml to "no-cache: true"
5) opsdroid should refer to the path: defined code, not in ~/.opsdroid/modules/

``` yaml
# Configurations for other skills uncomment desired skill to activate it.
  - name: demo
    path: /home/cdc/skill-demo
    no-cache: true
```

## Expected Functionality
Explain what should happen.

I would assume that for local skills, where time lag from pulling from the internet/GIT is not important, no-cache should be on by default.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

opsdroid by default refers to ~/.opsdroid/modules rather than /path/to/skill for local skills.

## Versions
- **Opsdroid version:**
opsdroid (0.9.1)
- **Python version:**
Python 3.5.2
- **OS/Docker version:**
Ubuntu 16.04.3

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by FabioRosado** [comment]
I might be wrong but I believe that the idea of the no-cache flag was created to be used by devs when testing/developing their skills. 

Once a skill is released as final version there won't be much need to reload it unless an update has been made. Also, if you delete the local folder (because you uploaded it to github) and forgot to change the path in your configuration the skill will stop working.

This is just my opinion though 😃

**Comment by jacobtomlinson** [comment]
I think I agree with what @FabioRosado is saying. I wonder if a good compromise would be to have a higher level `developer: True` config option which sets `no-cache` to default to `True`. This could be documented in the "how to write a skill" docs as a recommended option for when you are developing locally.
