### ISSUE TITLE
opsdroid chat community

### ISSUE THREAD

**Issue by go8ose** [opsdroid/opsdroid#317]
# Description
This project is about building a tool for automatic responses to a variety of chat protocols.  It feels like it is becoming a small community of like minded developers.  However there is no (semi-)official space for the community to congregate outside of the raw commits/issues/PRs.

Perhaps we should have a chat space, that is mentioned in opsdroid/docs somewhere. 

## Expected Functionality
I'd expect that this would be initially free-form, with perhaps only one room.  As the community grows I imagine more rooms might be made on an as-needed basis, and moderators/administrators would be somehow nominated/elected.

## Experienced Functionality
Instead we don't have anywhere for casual chat, or a place for new people to ask general questions. I predict that we will soon see:
 * bug reports from people which are caused by incorrect configuration or fault installations, rather than faults in the software
 * friction between developers, as they argue for particular technical directions, based on their unstated perceptions of where the project is going, without having the benefit of a broader view of the opsdroid landscape

It's possible that a chat community could mitigate some of those issues (though I doubt it will avoid them entirely).

**Comment by FabioRosado** [comment]
We currently use [gitter](https://gitter.im/opsdroid/) to talk about dev issues, there is also a lobby and a general room but at the moment no one is using those.

Perhaps we should mention the gitter chatroom in the CONTRIBUTION.md or some other place? If I'm not mistaken the only place that the gitter chatroom is mentioned is in the form of a button on the header of README.md.

**Comment by jacobtomlinson** [comment]
Yeah this is a good point. I would say that currently the community is small enough that Gitter and GitHub is enough. I think a forum would be overkill for now.

@go8ose Do you have any specific technologies which you would recommend that we use in the future?

**Comment by go8ose** [comment]
@jacobtomlinson I don't have any specific technology recommendations.  Gitter seems fine, it's got clients for the major platforms, looks easy to get started with.  I guess documenting it more prominently would be sufficient to close out this issue.  In that vein, I thought a note on README.md about the gitter chat space is sufficient.  But the README is getting a little long.  It might be good to strip that down a bit, and move some parts of it elsewhere.  Also updating opsdroid/opsdroid.github.io to mention the this chat space would be a good idea as well. Perhaps just a "Community" link up with the "Blog" and "Documentation" links would be sufficient.  If there is more information for the community later, we could later develop a community page, and link to it instead of the gitter chat.

I find it slightly amusing that this issue is itself an example of a bug report for something that is already solved.

**Comment by jacobtomlinson** [comment]
All good suggestions! I'll raise some more bite sized issues to tackle some parts of what you're said.

I think the fact that you were unable to find the Gitter community shows that this issue has not yet beed solved.
