### ISSUE TITLE
Add more references to the Gitter group in the docs

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#321]
# Description
Add more references and links to the [Gitter group](https://gitter.im/opsdroid) throughout the documentation. This will help users and contributors stay more involved in the opsdroid community.

Resulting from #317.

**Comment by ItsBraanddon** [comment]
I would be happy to help. I understand that you want me to add more References and Links to the Gitter Group. Could you explain how you would like me to do that? 👍

**Comment by jacobtomlinson** [comment]
Thanks that would be great. If you have a look through the documentation in
the `docs` folder and see if there is anywhere that it would be good to add
more references to the Gitter.

@FabioRosado has just done a load of work on the docs so he may have some
thoughts.

**Comment by FabioRosado** [comment]
Hello @ItsBraanddon  welcome on board!
As Jacob mentioned I've added a few mentions to the gitter channel to some of the documentation (some in the tutorials, in contributing, etc).

But I'm sure there are a a few places that I've missed. Perhaps it would make sense adding the gitter reference on the matchers/parsers part of documentation (since it can be a thing people might need help getting started).

You could read the documentation and check to see if it would make sense to add the reference of gitter channel or not.

Let me know if you need help with anything 👍

**Comment by go8ose** [comment]
There are several different opsdroid gitter channels.  While you are reviewing the documentation it might make sense to provide a mention of each gitter channel, and what it's for.

**Comment by FabioRosado** [comment]
That might be a good idea @go8ose, when I linked the gitter  in the documentation I've added just the channel(https://gitter.im/opsdroid/) but didn't say which room to use

**Comment by jacobtomlinson** [comment]
Thanks @go8ose that's a good idea. Annoyingly it's not possible to delete gitter rooms otherwise I'd clean it up a bit. I mainly intend just for developers and general to be used.

**Comment by lights-a5** [comment]
Is this still an issue? I'm currently trying to get into contributing to open source stuff, but I'm still learning and I figured this is something I could do.

**Comment by jacobtomlinson** [comment]
Yes please go ahead!

**Comment by jacobtomlinson** [comment]
This has been quiet for a while so it's available if anyone wants to grab it.

**Comment by musatoktas** [comment]
Hey!
Basicly what I understand is, you want us to share referance links from your docs in Gitter channel am I right?

**Comment by FabioRosado** [comment]
Hello @musatoktas and welcome!
No, we think that it could be helpful if we link our Gitter channel in our documentation to help people if they need anything. 
Hope this helps.

**Comment by musatoktas** [comment]
Hey!! Shall I add reference to Gitter Channel every doc files' beginning and endings. Like this; https://github.com/opsdroid/opsdroid/pull/507

**Comment by adityac8** [comment]
Hey @jacobtomlinson I would like to work on this 😃

**Comment by jacobtomlinson** [comment]
@adityac8 that's great. Have a look at the PR that @musatoktas raised and see the comments I made.

If you can raise a new PR including his change and then the tweaks I suggested that would be great!
