### ISSUE TITLE
Typo in welcome message

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#324]
# Description
There is a typo in the welcome message.

## Steps to Reproduce
Run opsdroid with `welcome-message: true` in the config.

## Expected Functionality
Should say 
> Started application

## Experienced Functionality
Says
> Stated application

**Comment by raghavgr** [comment]
Hi, I was thinking of working on this issue. However, when I am running `opsdroid` on my Mac terminal it is throwing an error. I have attached a screenshot.
<img width="1181" alt="screen shot 2017-11-03 at 5 04 39 pm" src="https://user-images.githubusercontent.com/33322020/32377550-1d82a16a-c0b9-11e7-8bc8-562fa206dcf7.png">

**Comment by jacobtomlinson** [comment]
@raghavgr It looks like you are using Python 2. You need to be running at least Python 3.5 to use opsdroid.
