### ISSUE TITLE
Tests overwrite config

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#325]
# Description
When running the test suite (`tox`) the config file in `~/.opsdroid/configuration.yaml` is overwritten as a side effect of the test suite.

## Steps to Reproduce

- Edit your `~/.opsdroid/configuration.yaml` file
- Run `tox`
- Check your config to see it has reverted to the default

## Expected Functionality
The config should not be modified.

## Experienced Functionality
The config is modified.

**Comment by suprithIUB** [comment]
Hi @jacobtomlinson I've identified the root cause. I'll send a pr in few hours.

**Comment by FabioRosado** [comment]
My config file got overwritten when testing the changes added by Recast.AI parser. Just checking if this happen to you as well @jacobtomlinson or if it's just a side-effect of using pyCharm to run the tests.

**Comment by jacobtomlinson** [comment]
I haven't had it happen since #326.
