### ISSUE TITLE
Add rasa parser and matcher

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#335]
# Description
Add support for [Rasa NLU](https://github.com/RasaHQ/rasa_nlu), similar to the ones for Dialogflow ([parser](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/parsers/dialogflow.py), [matcher](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/matchers.py#L56)).

As Rasa is written in Python it can be directly imported into the project rather than being used via the HTTP api.

**Comment by sgreszcz** [comment]
Heard about Rasa NLU on [Python Init Podcast](https://www.podcastinit.com/rasa-ai-chatbots-with-joey-faulkner-episode-134/) where they also spoke about the potential for opsdroid integration.  Awesome.

**Comment by FabioRosado** [comment]
I tried to install rasa on my fedora machine and was unable to do it (some issues while installing some of its requirements). Docker install didn't work as well (but then again I'm having issues with docker and fedora 26)

Perhaps using the API would be a better alternative? We could always create a skill if people wanted to use opsdroid and an imported version of Rasa - would this even work?

**Comment by jacobtomlinson** [comment]
I was testing using the docker image. Seemed to be working well for me on MacOS. 

It's a tricky one because I would love for Rasa to be the "default" parser. From a skill developer point of view you wouldn't have to write awful regexs any more and you could create way more flexible skills. At the moment you kind of have to create a regex and then add Dialogflow/LUIS/wit options as more flexible optional enhancements. 

That being said Rasa NLU is big in terms of size and system requirements. It could end up making opsdroid really slow for people using it and take up lots of disk space. 

I'm thinking a good compromise would be to make it optional and use the API to interact with it. But update the documentation to show that it is the recommended option
