### ISSUE TITLE
Pass config to skill setup method

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#341]
# Description
When running the `setup` method of a skill only a pointer to opsdroid is passed, the config for that skill should be passed too. See the [call here](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/core.py#L153).

**Comment by RonitRay** [comment]
Hi, I'm a first-time contributor, and would like to work on this. Would that be alright?

**Comment by jacobtomlinson** [comment]
Yep that looks right to me. If you raise a Pull Request we can always review it there.

**Comment by RonitRay** [comment]
Raised a PR, do let me know if that seems fine or how it should be approached otherwise.
Thanks for letting me work on this!
