### ISSUE TITLE
String Formatting consistency

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#375]
Hello guys, I hope you had a good time over the holidays!

I was reading the book Mastering Python and came across string formatting, which reminded me that we switched the string format of the logging by using % .

Through the code base we use both the % and .format() versions of the string formatting, that made me wonder if we should just stick with one version through the code base and which one should we use.

Also, note that in python 3.6 fstrings were introduced but since they are not backwards compatible, I haven't mentioned them.

Please let me know your opinion about this and if it's worth a PR to swap all the string formatting to use one style.

**Comment by jacobtomlinson** [comment]
Happy new year!

My preference is use `.format()` for everything except log messages which insist on `%` in pylint.

Eventually everything should switch to fstrings. However I don't anticipate this happening for a number of years. Maybe when the version of Python shipped with Debian is 3.6 we could safely make that the minimum for opsdroid.

**Comment by FabioRosado** [comment]
I didn't know that pylint insists on using % for log messages. I guess this Issue is pointless now since the only thing using the % string formatting is the logging haha

I haven't played around with fstrings much to be honest because it will take ages until everybody upgrades to 3.6 (at least until python 2 is still strong I guess)

**Comment by jacobtomlinson** [comment]
Well logging must be passed a string with placeholders like `%s`, `%i`, etc and the rest of the args must be the vars to populate the string. Which is slightly different to `'%s' % var`. But the point is it uses `%s` instead of `{}` for placeholders.

I'll close this for now, hopefully a change in the logging library or the default python version will cause us to reopen it.
