### ISSUE TITLE
Change logging level of opsdroid.memory

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#381]
# Description
When running opsdroid from the command line, every time opsdroid replies to the user input a logging.warning is printed in the console.

## Steps to Reproduce

**1.** Don't have any database configured in `configuration.yaml`
**2.** Start opsdroid from the command line
**3.** Type hello

## Expected Functionality
database warning to be shown on first lines of opsdroid but then go silent  afterwards.

## Experienced Functionality
```
hi
Hey fabiorosado
opsdroid> WARNING opsdroid.memory: No databases configured, data will not persist
WARNING opsdroid.memory: No databases configured, data will not persist
```

## Additional Details
When opsdroid loads, the warning message `WARNING opsdroid.loader: No databases in configuration` is shown. This should be enough to warn the user that no databases are configured.

It seems that even if no databases are configured, with each message, opsdroid will try to invoke: `opsdroid.memory._get_from_database()` and `opsdroid.memory._put_to_database()`
Perhaps these loggings could be removed as they seem redundant since the user already knows that no databases are configured - it also might help with some "spam" in the log files.

**Comment by jacobtomlinson** [comment]
Agreed these messages are overkill. Let's take them out.
