### ISSUE TITLE
Add intents params to rasa nlu docs

### ISSUE THREAD

**Issue by gabeduke** [opsdroid/opsdroid#383]
# Description
rasa nlu documentation should include the following requirements
* there must be at least 2 intents or rasa will not return anything. For a user new to rasa this could be a large time sink (:wave:)
* each intent must have at least 3 training values

**Comment by jacobtomlinson** [comment]
Ah that's really interesting! I hadn't noticed those limits. 

Maybe we should even go beyond documentation and add a check in the code too.

**Comment by gabeduke** [comment]
I'll start working on this.

**Comment by jacobtomlinson** [comment]
@gabeduke did you get a chance to look at this? If not I think I'll pick it up as I want to get it done before the next release which is imminent.

**Comment by gabeduke** [comment]
I've not been able to start work on this yet unfortunately. You can go ahead and take it over.
