### ISSUE TITLE
Skill dependencies are not reimported on reload

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#413]
# Description
When reloading skills any library which is imported in the skill is not reimported.

This means that if you split your skill into multiple files and import them from the `__init__.py` they don't get reimported. As opsdroid immediately reloads all skills on startup this means any skills in separate files are never loaded.

_Raised on [Gitter](https://gitter.im/opsdroid/developers) by @afibanez._

## Steps to Reproduce
- Create a skill with an `__init__.py` file and a `test.py` file.
- In the `__init__.py` add `from . import test`.
- Add one regex skill to the `__init__.py` and one to the `test.py`.
- Add `_LOGGER.debug(regex)` to `match_regex` in `matchers.py` in opsdroid to see the result.
- Run opsdroid. 

## Expected Functionality
Both skills should be loaded.

## Experienced Functionality
Both skills are loaded, then opsdroid reloads and only the skill in `__init__.py` is reloaded.

## Versions
- **Opsdroid version:** master
- **Python version:** 3.5.3
- **OS/Docker version:** macOS 10.13

**Comment by redfruitt** [comment]
I haven't used it, since its unreliable its better to remove it rather than having someone waste their time trying to figure out what's happening.

**Comment by jacobtomlinson** [comment]
Yeah had the same comments in gitter. Therefore it should be removed.

**Comment by redfruitt** [comment]
I'll take this up after I complete #449
