### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#424]
# Description
The contributing link in the [contributors](https://github.com/opsdroid/opsdroid#contributors) section points to `CONTRIBUTING.md` which doesn't exist. It should point to `docs/contributing.md`.

**Comment by jacobtomlinson** [comment]
cc @monkeywithacupcake

**Comment by dhairyakhale** [comment]
Hi! Can I take up this issue?

**Comment by jacobtomlinson** [comment]
@dhairyakhale please go ahead!

**Comment by dhairyakhale** [comment]
Submitted a PR. Please let me know if I made some mistake.

**Comment by monkeywithacupcake** [comment]
sorry I missed that!

**Comment by jacobtomlinson** [comment]
No probs!
