### ISSUE TITLE
Add pypi version badge to README

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#427]
# Description
We should have a badge showing the current version available on pypi next to the existing badges.

![pypi version](https://img.shields.io/pypi/v/opsdroid.svg)

```
https://img.shields.io/pypi/v/opsdroid.svg
```

**Comment by vettyvignesh** [comment]
Hi, I am new to open source so can you please assign this issue to me.

**Comment by may55** [comment]
I am new to open source, can you please tell me how exactly i can fix this issue?

**Comment by FabioRosado** [comment]
Hello @may55, welcome!
@vettyvignesh  is currently working on this issue, but if you want to contribute I'd suggest an equally easy issue to fix: #380 

Pop in the [gitter](https://gitter.im/opsdroid/developers) channel if you need any help 👍

**Comment by jacobtomlinson** [comment]
Closed in #429
