### ISSUE TITLE
Add references about asyncio and change the description about the youtube videos

### ISSUE THREAD

**Issue by OzRamsay** [opsdroid/opsdroid#437]
# Description
Documentation enhancement proposals 
1. currently the youtube videos are mentioned on the [home](http://opsdroid.readthedocs.io/en/latest/) page of documentation as "Installation Check out the Getting Started video series on YouTube." As the videos also teach how to create some skills, I propose to change the description and also add references to the videos to the [tutorials](http://opsdroid.readthedocs.io/en/latest/tutorials/basic-skill/) section.
2. To add more references about asyncio on [page](http://opsdroid.readthedocs.io/en/latest/tutorials/introduction/) 

If the proposals are accepted, I can implement them.

**Comment by jacobtomlinson** [comment]
Sounds good!

**Comment by OzRamsay** [comment]
Hi, @FabioRosado. I am very sorry, but I started a new job, so currently, I do not have time:(

**Comment by FabioRosado** [comment]
@OzRamsey no worries I was just checking up on this issue anyway. The issue will remain open and if you find some time and the issue is still open feel free to give it a go 😀

**Comment by FabioRosado** [comment]
@TarunRKaushik Hey nice seeing you here. Feel free to submit a PR with your changes 👍
