### ISSUE TITLE
Keep raw message as property of the Message class

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#443]
# Description
When a message created by a connector it only sets the text, room, username and connector properties. Many chat clients will provide more information about the message, for example the timestamp, message id, etc. 

It would be useful to keep track of this info in a property called `raw_message` as it may be useful to the connector when responding.

I think the best way to implement this would be adding a kwarg to the class `__init__` called `raw_message` which defaults to `None`. This can then be used by a connector if it wishes.

Related to opsdroid/connector-slack#9

**Comment by redfruitt** [comment]
Hi @jacobtomlinson, I'd like to work on this!

**Comment by jacobtomlinson** [comment]
Please go ahead!
