### ISSUE TITLE
Upgrading aiohttp beyond v3 breaks tests

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#457]
# Description
As demonstrated in #456 upgrading aiohttp to v3 or above causes a bunch of tests to fail. 

This is likely an issue with the tests but it should be investigated to ensure there are no fundamental issues with opsdroid.

The tests need to be fixed and the version updated in a manual replacement for #456.

**Comment by redfruitt** [comment]
I'll take this up
