### ISSUE TITLE
Document parser configuration

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#477]
The [configuration reference](https://github.com/opsdroid/opsdroid/blob/master/docs/configuration-reference.md) currently doesn't have a section on parsers. This should be added.

I also think each [parser/matcher section](https://github.com/opsdroid/opsdroid/tree/master/docs/matchers) should start with the configuration information for that parser, followed by the usage within a skill.

**Comment by TarunRKaushik** [comment]
U meant "it does not have a section on parsers"?

**Comment by jacobtomlinson** [comment]
Yes

**Comment by sbeesm** [comment]
Hello! First time contributor here. Can I work on this one?

**Comment by FabioRosado** [comment]
Hello there @sbeesm it would be great if you could work on this issue, please let me know if you need help with anything! 

Also, welcome 😀👍

**Comment by sbeesm** [comment]
If I'm not wrong, parsers are being used to analyse the messages that the bot receives and the matcher matches it with the available skills and the bot replies accordingly.
So is the working of a parser needs to be documented?

Very sorry but I am slightly confused about what exactly needs to be done and how to get started.
I've gone through some parsers and matchers code but couldn't really figure out what to do.
Please Help!

**Comment by jacobtomlinson** [comment]
Hi sbeesm

The configuration reference doesn't have any info on how to configure the parsers. Each parser needs to be added with information on how to configure it. 

Also if you look at the documentation for each matcher you'll see that some have a configuration section, some don't. They all need one and it should be at the top too.

**Comment by FabioRosado** [comment]
The parsers have all the logic to connect to the NLU parsers network and parse the meaning of the words that a user typed in channel/to opsdroid.

The matchers are used as decorators (check regex parser/matcher) and they are used to trigger the parser that connects to the NLU service.

As for what needs to be done, Jacob beat me to it haha

**Comment by sbeesm** [comment]
Thanks @jacobtomlinson and @FabioRosado for helping me get started. 😀

PR #382 fixes #353 and adds windows support but I still get this error when I try to run opsdroid:

> (C:\Anaconda3) C:\Users\HP>opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
INFO opsdroid.loader: Cloning hello from remote repository
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\opsdroid.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\opsdroid\__main__.py", line 130, in main
    opsdroid.start_loop()
  File "c:\anaconda3\lib\site-packages\opsdroid\core.py", line 136, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 257, in load_modules_from_config
    skills = self._load_modules('skill', config['skills'])
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 307, in _load_modules
    self._install_module(config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 336, in _install_module
    self._install_git_module(config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 386, in _install_git_module
    config["branch"])
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 98, in git_clone
    stderr=subprocess.PIPE)
  File "c:\anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
I have installed it using pip3 in anaconda in my default python 3.6 environment.

**Comment by sbeesm** [comment]
In the test and example_config files, most of the parsers have configurations like name, access-token, min-score.
Are there more configurations as well? If so, where can I find them?

And can u please tell me that how can I find more info on these configurations so that a proper documentation can be prepared. 🙏 
Because to be honest I am not really able to understand the concept of parser configs.

**Comment by FabioRosado** [comment]
At the moment you have different kinds of parsers in opsdroid:
- Natural Language Processors
  - Dialogflow
  - Rasa
  - luis.ai
  - recast.ai
  - witai
- Regex Parser
- Crontab parser
- weekhook
- always

All NLP parsers need to be specified in the file `configuration.yaml` in order to be used with opsdroid. Some parses take different configuration settings - as example check the [Rasa NLU configuration](https://github.com/opsdroid/opsdroid/blob/master/docs/matchers/rasanlu.md/#configuring-opsdroid).

As Jacob said the configuration should be at the top of the document because this will be the most important piece of information that someone might need (you will care more about how to activate the parser first than how it works).

I did a quick check and currently these are the parsers that don't have a configuration section:
- regex 
- always
- crontab

The things with regex for example is that you don't really need any specific parameter in the `configuration.yaml` file. Have a look at the [configuration example](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/configuration/example_configuration.yaml) file to have an idea what would be needed to included in each parser configuration section.

Hope this was helpful 👍

**Comment by sbeesm** [comment]
Is this ok?

```
Configuring opsdroid for Regex Matcher 
parsers:
   - name: regex
     enabled: true

In order to enable regex skills you must set the enabled parameter to true in the parsers section of the opsdroid configuration file.

If a skill is configured with both the regex and some other NLU matcher then users who don't use NLU will get a simple regex match. However users with some other NLU configured will get matches on more flexible messages, but will not see duplicate responses where the regex also matched.
```


```
Configuring opsdroid for Crontab Matcher
parsers:
   - name: crontab
     enabled: true

In order to enable crontab skills you must set the enabled paramater to true in the parsers section of the opsdroid configuration file.
```

**Comment by sbeesm** [comment]
The always matcher parses every message as it is always working/running. So can the always matcher be configured or does it need to be configured?

**Comment by sbeesm** [comment]
Also, all the links to matchers under the 'Matchers available' section in Docs/tutorials/intoduction.md seem to be broken. They are not working.

**Comment by FabioRosado** [comment]
What are you using to read the documentation? The links work in the site and on my pycharm :)

**Comment by sbeesm** [comment]
I am using Chrome browser, and this is what it shows:
![image](https://user-images.githubusercontent.com/27358509/37782077-095b6a1a-2e18-11e8-8a1b-9d63cda8f215.png)

**Comment by sbeesm** [comment]
And shall I add a new Parsers section in the Configuration Reference or just add the missing configurations in their respective matcher docs?

**Comment by FabioRosado** [comment]
Is it only the wit.ai not working or all of them?
The configuration should be added to both places

**Comment by sbeesm** [comment]
All of them aren't working.

**Comment by jacobtomlinson** [comment]
Yes the links are not designed to work on the GutHub website, they are designed to work in the mkdocs documentation.

**Comment by sbeesm** [comment]
I've created a PR #502 
Waiting for review!
