### ISSUE TITLE
PR template does not auto close issues

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#481]
# Description
In our [PR template](https://github.com/opsdroid/opsdroid/blob/master/docs/PULL_REQUEST_TEMPLATE.md) we have a section for stating which issue is closed by this PR.

```markdown
**Fixes** #<issue>
```

However this doesn't seem to actually auto close the issue. Removing the bold notation (`**`) fixes this.

**Comment by TarunRKaushik** [comment]
Well I raised a PR removing the bold notation.
