### ISSUE TITLE
Connectors need to be updated

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#511]
# Description
_This issue is not really related to opsdroid itself but to every single connector used in opsdroid - I'm creating this issue here to increase visibility._

Since PR #493 was merged into the master branch, opsdroid fails to reply to user input. The issue lies in [this line of code](https://github.com/opsdroid/opsdroid/blob/a4c13f4f2cff2af5899b4bb0f5897eeaff98b249/opsdroid/message.py#L55)

Since the optional argument `room` was added to the base class Connector and Message, every connector in opsdroid needs to update their `respond` function from:
`async def respond(self, message)`
to:
`async def respond(self, message, room=None)`

**Connectors that need to be updated:**

- [Connector-ciscopark](https://github.com/opsdroid/connector-ciscospark)
- [Connector-slack](https://github.com/opsdroid/connector-slack) (Bonus if you rename slack.py to __init__.py)
- [Connector-telegram](https://github.com/opsdroid/connector-telegram)
- [Connector-websocket](https://github.com/opsdroid/connector-websocket)
- [Connector-github](https://github.com/opsdroid/connector-github)
- [Connector-facebook](https://github.com/opsdroid/connector-facebook)
- [Connector-shell](https://github.com/opsdroid/connector-shell)
- [Connector-twitter](https://github.com/opsdroid/connector-twitter)

## Steps to Reproduce
1. Run latest dev branch of opsdroid.
2. Type 'hello'
3. Opsdroid fails 

## Expected Functionality
Opsdroid would reply to 'hello' input

## Experienced Functionality
```
opsdroid> INFO opsdroid.web: ======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
hi
opsdroid> ERROR asyncio: Task exception was never retrieved
future: <Task finished coro=<OpsDroid.run_skill() done, defined at /Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/core.py:206> exception=TypeError('respond() takes 2 positional arguments but 3 were given',)>
Traceback (most recent call last):
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/core.py", line 213, in run_skill
    await skill(self, config, message)
  File "/Users/fabiorosado/.opsdroid/modules/opsdroid-modules/skill/hello/__init__.py", line 14, in hello
    await message.respond(text)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/message.py", line 55, in respond
    await self.connector.respond(response, room)
TypeError: respond() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/core.py", line 216, in run_skill
    await message.respond(_("Whoops there has been an error"))
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/message.py", line 55, in respond
    await self.connector.respond(response, room)
TypeError: respond() takes 2 positional arguments but 3 were given
```

## Versions
- **Opsdroid version:**  dev
- **Python version:** 3.6
- **OS/Docker version:**  macOS 10.13.4

## Configuration File
Please include your version of the configuration file bellow.

```yaml
# basic config file

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by alexenriquent** [comment]
I'm new to open source contribution and it'd be great if I could help out. I've already submitted the pull requests to make changes to each of the connectors.  Hopefully I've done it right.

**Comment by FabioRosado** [comment]
Hello @alexenriquent welcome!
Thank you so much for taking the time to fix this issue that spans across all of the connectors on opsdroid, this is a great help.

I’m out at the moment and don’t have access to my laptop but later either me or Jacob will merge your changes to the connectors.

Also you can get opsdroid stickers for your work, dm [opsdroid twitter](https://mobile.twitter.com/opsdroid)  with your address if you would like to get them 😀👍
