### ISSUE TITLE
Fix no database warning message

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#515]
# Description
When opsdroid is run with no databases set in the `configuration.yaml` a warning message is logged saying the following:
`"No databases in configuration. This will cause skills which store things inmemory to lose data when opsdroid is restarted."` located on [line 241](https://github.com/opsdroid/opsdroid/blob/7e0aa02595ba18121aecb67006c0980eeb62ddfb/opsdroid/loader.py#L241) in the file opsdroid.loader.

The words "in" and "memory" should have a space between them - The issue resides in line splitting without adding a blank space after the word "in".

Example:
```python
            _LOGGER.warning(_("No databases in configuration."
                              "This will cause skills which store things in"
                              "memory to lose data when opsdroid is "
                              "restarted."))
```

## Steps to Reproduce
Run opsdroid without any database configured.

## Expected Functionality
The logging message should still show up but with a space between the two words.

## Experienced Functionality
Typo in warning message.

## Versions
- **Opsdroid version:** dev
- **Python version:** 3.6
- **OS/Docker version:** OS 10.13.4

## Configuration File
Please include your version of the configuration file bellow.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by subhrm** [comment]
I would try to fix this issue.
