### ISSUE TITLE
Pass path to config as cli argument

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#634]
The new config file location appears to cause confusion with existing users as they end up in a state where opsdroid is using the new config but the old config still exists.

Here is some feedback via Gitter/Matrix.

> jacobtomlinson: I would be really interested to hear feedback on how we could improve this transition. Perhaps we should empty .opsdroid and put in a warning file.
>
> colonelkrud: Probably a start blocking error that asks you to check and remove the old path if it exists.. rename it to stop the error. That way you 100% know the person running the bot is aware of the change

**Comment by colonelkrud** [comment]
We could also allow the user to pass the path at start with a flag.

**Comment by jacobtomlinson** [comment]
Just came back to this issue. We should totally add a CLI argument to allow you to pass the path to a config file instead of automatically checking through the default ones.

I propose we add a `-f` flag to all cli arguments (I think we can just so this in the root group) and if it is set we don't check any of the default config locations at all and exit with an error if the path the user gives doesn't exist.

**Also**

We could add a `--set` flag ([as in helm](https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of-set)) which allows you to override specific options on the command line.

For example you could call `opsdroid start --set web.port=8008` to change the web server port at runtime without modifying the config. 

This would require the argument being passed to `--set` to be parsed somehow into a dictionary, and then updated into the config dictionary after it has been loaded using `opsdroid.helper.config_merge` from #1252.

_This could also be done separately and raised in a new issue._

**Comment by FabioRosado** [comment]
Closed  since we can now load a config from a path (#1271)
