### ISSUE TITLE
Hacktoberfest 2018

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#641]
It is just over two weeks until the start of Hacktoberfest. I am also expecting a baby at the beginning of October and will not be able to put in as much effort this hacktoberfest as I would like. Therefore we should invest time now in preparing the project with a whole range of well written issues for people to tackle.

This should also make the review and merge process straightforward for @FabioRosado as it will be clear whether a PR satisfies and issue if the issue is well written.

I've also been thinking lately that we should start working our way towards a 1.0 release. The main motivation behind this is that people are building tools and bots on top of opsdroid, and we should work towards giving them a stable API. The project is maturing nicely and we should start pinning things down now.

I'm going to create a milestong for the 1.0, start assigning issues to it and will also start raising issues ready for hacktoberfest.

**Comment by FabioRosado** [comment]
First of all congratulations on the baby, hope everything goes well (and that you can get some sleep over the night 😄 

I've been thinking about issues but I have nothing at the moment, but I'm more than happy to help around on hacktoberfest. I also agree with the milestone and assign issues to it, it will give us a clear path that we should follow and which issues should be a priority than others.

**Comment by jacobtomlinson** [comment]
Thanks! 

I have tons of things in my head which I need to formalise into issues. We definitely aren't short of things to do. So I'll just crack on with typing them up.
