### ISSUE TITLE
Thinking delay and typing delay

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#65]
Configuration options should be added to allow users to set delays for responses. This would allow a bot to appear more human.

#### Thinking delay

This delay would be added to every message and would simulate a user thinking about what to respond. This option should take the delay seconds as an integer or an array of two integers to determine the delay or the range for random delays respectively.

#### Typing delay

This delay would be added to the response of every message and would simulate the user typing out the message. This option should take an integer of "words per minute" to determine the length of the delay relative to the length of the response. It should also trigger the "user is typing" call during the delay, for connectors that support it.

**Comment by gtseres** [comment]
Should this be added as a section in the configuration file? Maybe a `customizing` section, or something like that?

**Comment by jacobtomlinson** [comment]
@gtseres gah just seen this comment sorry!

Potentially, although it could be best to add it to each connector.
