### ISSUE TITLE
Treat skills with explicit path as local

### ISSUE THREAD

**Issue by colonelkrud** [opsdroid/opsdroid#654]
When defining custom skills in the configuration file, we have the ability to define a path for the skill. When this path is defined, we should be able to safely assume that the skill is local and accessible by the bot and therefore should not need to be cached.

My suggestion is to treat skills which have been explicitly defined with a local path as local skills and automatically apply the `nocache=true` unless caching is otherwise defined in the config.

**Comment by FabioRosado** [comment]
I like that idea and it does make sense to have the nocache set to true if the path is available in the config when you are developing the skill. 

We need to check with the community if this is something we should implement as well, the reason for that being that some devs are probably using their own skills with opsdroid and perhaps having the nocache set could cause a burden to them when opsdroid is run.

**Comment by jacobtomlinson** [comment]
To add some context this issue has come from a chat on Gitter/Matrix. We were saying that for anything specific with `path` should default to `no-cache: true` and anything with `repo` should default to `no-cache: false`. The user is still free to configure in whichever way they like.

My only concern is that this inconsistency may cause confusion. However as the current caching is already causing confusion I think this is probably a better approach.

**Comment by FabioRosado** [comment]
Ah okay I checked Gitter but is nothing there about this. Are we using matrix more?

**Comment by jacobtomlinson** [comment]
The two are bridged so you can use either. We were discussing it in general yesterday, but it might've gotten lost in the noise :).

**Comment by jacobtomlinson** [comment]
This just came up again. We really should do this.
