### ISSUE TITLE
Add conda package

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#660]
We should distribute opsdroid via `conda` as well as `pip`. 

This would require:
 - ~~Create an [opsdroid organisation](https://anaconda.org/opsdroid) on anaconda.org _(must be done by a maintainer)_~~
 - ~~Add an `ANACONDA_TOKEN` env var to Travis to enable uploading to anaconda _(must be done by a maintainer)_~~
 - Create a `meta.yml` file in a `conda` directory to specify the package
 - Add steps to the Travis deploy to build and push to anaconda
   - Install miniconda
   - Build the conda package
   - Push to anaconda
 - Add conda section to installation instructions

[This package](https://github.com/informatics-lab/jade_utils) that I've worked on recently would be good inspiration, although all the Travis steps would probably need to be combined into a script which is run at the deploy stage of opsdroid.

**Comment by jacobtomlinson** [comment]
Thanks for that @synapticarbors that's great! I'm still keen that we build onto our own channel on anaconda.org too. Conda forge adds some extra maintenance so this would need to be updated in the [making a release](https://github.com/opsdroid/opsdroid/blob/master/docs/project/making-a-release.md) documentation.

I would really appreciate if you could put in a PR to this repo to add the same meta config here for anaconda.org and update the documentation.

To answer your questions:
 - Myself and @FabioRosado are currently the only @opsdroid/maintainers but I expect that to grow slowly. I don't know if you can reference a team rather than individuals.
 - Currently packages are unnecessarily strict but we are planning on resolving this in #651. So `requirements.txt` will remain strict and up to date for testing purposes, but `setup.py` will be flexible.

**Comment by synapticarbors** [comment]
A few follow-ups:

- Do you and @FabioRosado want to be included as co-maintainers on the conda-forge package?
- In the conda package that will be in the opsdroid anaconda.org channel, where are you going to pull the dependencies from? The main channel will not have a bunch of them. I'm adding them to conda-forge as part of getting `opsdroid` built there. Or are you going to want to have all of the dependencies in your channel?

**Comment by jacobtomlinson** [comment]
- Yes please, probably best for now. 
- Good question. I would be happy to take your advice at this point. Do you think we should just go with the conda-forge version?

**Comment by jacobtomlinson** [comment]
@synapticarbors I'm gearing up to do a release of opsdroid. What needs to be done in conda forge for it to deploy there also?

**Comment by synapticarbors** [comment]
Once the release has been made on pypi, one of the conda-forge bots should issue a pull request. It can be done manually, but the bot usually picks it up pretty quickly. Once that PR appears, I can walk you through the things I usually check to make sure it looks good. The bot itself puts some useful info about what to check as well, but it can sometimes miss stuff.

**Comment by jacobtomlinson** [comment]
@synapticarbors ok great thanks. But just to confirm there is a manual release step which is required? I'll make sure to update the documentation once I've run through it once.

**Comment by jacobtomlinson** [comment]
@synapticarbors the PR has been raised. https://github.com/conda-forge/opsdroid-feedstock/pull/1#issuecomment-435692483

**Comment by synapticarbors** [comment]
I'm not 100% sure what you mean by a "manual release step". Basically you can do one of several things:

- Wait for the bot to make the PR once it detects the pypi change, and then assuming everything looks good, merge the PR, which triggers the new binary to be pushed to anaconda.org in the conda-forge channel
- Wait for the bot to make the PR and then make manual changes and push to the PR branch (or edit directly on the github website) and then merge as above.
- Make a manual PR from your own fork of the feedstock repo that includes all of the necessary changes and then merge that PR. 

If you need more info or clarification, let me know.
