### ISSUE TITLE
Move GitHub connector into core

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#664]
This issue covers adding the [GitHub connector](https://github.com/opsdroid/connector-github) to core.

## Background
A while ago we began moving connectors from external plugins into the core of the project (see #185 for more context). We started with [slack](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/connector/slack/__init__.py) and [websockets](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/connector/websocket/__init__.py) but need to go through all the other existing plugins and move them into the core.

## Steps

 - Make a new submodule directory in [`opsdroid.connector`](https://github.com/opsdroid/opsdroid/tree/master/opsdroid/connector) and copy the connector code over.
 - Update the [`requirements.txt`](https://github.com/opsdroid/opsdroid/blob/master/requirements.txt) with any dependencies from the connector if necessary.
 - Write tests for the connector. (See the [Slack connector tests](https://github.com/jacobtomlinson/opsdroid/blob/master/tests/test_connector_slack.py) for inspiration).
 - Copy the relevant information from the connector `README.md` into a [new documentation page](https://github.com/opsdroid/opsdroid/tree/master/docs/connectors).
 - Add the new page to the [mkdocs.yml](https://github.com/opsdroid/opsdroid/blob/master/mkdocs.yml).
 - Add to the [list of connectors](https://github.com/opsdroid/opsdroid/blob/master/docs/configuration-reference.md#connector-modules).
 - Add a deprecation notice to the old connector. (See [the slack connector](https://github.com/opsdroid/connector-slack))

**Comment by souravsingh** [comment]
@jacobtomlinson I am interested in taking a stab at this.

**Comment by FabioRosado** [comment]
Hello @souravsingh please go ahead and work on this issue, let us know if you need any help 👍

**Comment by jacobtomlinson** [comment]
Hey @souravsingh I'm guessing you've not had time to work on this. If anyone else wants to take this up then please go ahead.

**Comment by souravsingh** [comment]
I have been getting busy with work. Let me create a WIP pull request.

**Comment by jacobtomlinson** [comment]
@souravsingh That's no problem! I look forward to reviewing your PR.
