### ISSUE TITLE
Create a Mattermost connector module

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#673]
Let's add a [Mattermost connector](https://mattermost.com/).

## Steps

 - Make a new submodule directory in [`opsdroid.connector`](https://github.com/opsdroid/opsdroid/tree/master/opsdroid/connector) called `mattermost` and create an `__init__.py` file inside.
 - Implement the connector according to the [documentation on writing connectors](https://opsdroid.readthedocs.io/en/stable/extending/connectors/).
 - Update the [`requirements.txt`](https://github.com/opsdroid/opsdroid/blob/master/requirements.txt) with any new dependencies from the connector if necessary.
 - Write tests for the connector. (See the [Slack connector tests](https://github.com/jacobtomlinson/opsdroid/blob/master/tests/test_connector_slack.py) for inspiration).
 - Create a [new documentation page](https://github.com/opsdroid/opsdroid/tree/master/docs/connectors).
 - Add the new page to the [mkdocs.yml](https://github.com/opsdroid/opsdroid/blob/master/mkdocs.yml).
 - Add to the [list of connectors](https://github.com/opsdroid/opsdroid/blob/master/docs/configuration-reference.md#connector-modules).

### Resources to get you started
   - [Mattermost API](https://api.mattermost.com/)
   - [Asyncio Mattermost Python module](https://pypi.org/project/mattermostdriver-asyncio/)

### Asyncio
 Opsdroid uses [asyncio and an event loop](https://docs.python.org/3/library/asyncio.html), so here are some things to bear in mind:
   - Functions should be coroutines which are defined with `async def myfunc(): ...`
   - Coroutines are called with `await`. For example `await myfunc()`. This is how asyncio allows many functions to take it in turns as they swap over when the current thread calls `await`.
   - **Don't block the thread!** If you need to make a call to a blocking function such as `time.sleep()` or any kind of IO request such as `requests.get()` then you should `await` an async variant. For example  you can call `await asyncio.sleep(10)` to sleep without blocking the whole application and you can use `aiohttp` as an async url library.

**Comment by FabioRosado** [comment]
Hello @leeyjjoel please go ahead and work on the issue and let us know if you need any help while working on it 👍

**Comment by daniccan** [comment]
@jacobtomlinson Hi, is anyone working on this or can I pick it up?

**Comment by FabioRosado** [comment]
Hello @daniccan thank you for showing interest on this. No one is currently working on this task so it would be great if you could take it up 😄 👍  

Please let us know if you need any help

**Comment by daniccan** [comment]
Sure @FabioRosado. Thanks.

**Comment by daniccan** [comment]
To connect with the mattermost server, I am using the `mattermostdriver` in python. While registering the websocket to receive messages, I am getting `RuntimeError: This event loop is already running` error in the line `https://github.com/Vaelor/python-mattermost-driver/blob/master/src/mattermostdriver/driver.py#L146`.
