### ISSUE TITLE
Implement disconnect method to connectors

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#717]
# Description
Opsdroid can now exit in a clean way after #711 was merged. But most of the connectors (with the exception of websockets) don't implement the `disconnect` method and when opsdroid tries to exit, an exception occurs, because the connector task was destroyed while pending.

Implementing the disconnect method on every connector will avoid this exception to occur.

---
_As a work around until every connector is addressed should we just get all tasks and cancel every single one within the `core.unload` method?_

## Steps to Reproduce
Start opsdroid, wait for load and then kill it with `ctrl+c` the shell connector will throw the exception.

## Expected Functionality
Opsdroid should be able to exit without any exception being thrown.

## Experienced Functionality
Every single thing is cancelled but the connectors that don't implement the disconnect method.

```python
Caught exception

ERROR opsdroid.core: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<ConnectorShell.listen() done, defined at /Users/fabiorosado/Library/Application Support/opsdroid/opsdroid-modules/connector/shell/__init__.py:64> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10dbfd9a8>()]> cb=[gather.<locals>._done_callback(0)() at /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:609]>}
```

**Comment by jacobtomlinson** [comment]
Related to #723

**Comment by jacobtomlinson** [comment]
This still needs fixing.

**Comment by jacobtomlinson** [comment]
Only the Rocket Chat connector needs this implementing now. @FabioRosado is this something you could pick up?
