### ISSUE TITLE
Memory leak when using slack connector

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#743]
I've noticed in a couple of different deployments of opsdroid that there seems to be a memory leak. In my work deployment it seems to happen at the same time every day so it is likely related to the cron timing. It looks like the memory just keeps filling until the OOM killer ends the process and it restarts again. I'll have a look through the skills I have and see if anything lines up with the timings.

![image](https://user-images.githubusercontent.com/1610850/48697075-9e3d9000-ebdb-11e8-9bb5-5f429f046440.png)

![image](https://user-images.githubusercontent.com/1610850/48697086-a5649e00-ebdb-11e8-8d54-085810f36418.png)

**Comment by jacobtomlinson** [comment]
I don't seem to have any skills with cron timings around that time.

**Comment by FabioRosado** [comment]
@AndresCidoncha posted the following on gitter:

```
Andrés Cidoncha Carballo (Gitter)
BTW: I'm searching the memory leak cause, I only can tell that with the default config isn't happening.
```

Could it be a skill  added to the config?

**Comment by jacobtomlinson** [comment]
I've seen it happen on two separate opsdroids. One is using slack and websockets and has the grafana, apiap and homeassistant skills. The other is using slack, the sqlite database and the help, grafana, cloudhealth and a couple of custom skills. 

So potentially if this is not a bug in opsdroid core then it could be related to the slack connector or the grafana skill.

As the slack connector has changed more recently I would suggest investigating that first.

**Comment by AndresCidoncha** [comment]
When I had the problem only have in common with your configs the slack and sqlite connectors, so the problem must be in the slack connector :thinking:

**Comment by betojulio** [comment]
Hi, I have been using Opsdroid with slack for a week now, and  I have not encountered any memory issue so far.

stack:
kurbenetes Engine in GCP
- 1 node : 1 vcpu, 1.70 GB memory
- No DB

![image](https://user-images.githubusercontent.com/6899441/54073899-0cbd6100-4252-11e9-9bba-7cd3b4c4421b.png)

**Comment by FabioRosado** [comment]
I've been running opsdroid on my raspberry pi for the last two/three days and today I have noticed that opsdroid stopped responding to my commands. I went to the raspberry and noticed that it had been killed.

I'm using two skills that are using crontabs and the bot is set up to use slack and telegram. The sysanalytics skill is running every minute to get % of ram and CPU and put these into a sqlite db.

It seems that opsdroid got killed because of the memory leak. I wonder if the issue is indeed with slack and the keepalive (I had read something about this) or either the crontab or the sqlite database

I'm going to try and investigate further.

![IMG_2138](https://user-images.githubusercontent.com/3131401/60653198-7c7adb80-9e41-11e9-87be-bbb9acbb9fa0.PNG)

**Comment by FabioRosado** [comment]
So I got the logs for the slack connector:

```python
DEBUG websockets.protocol: client > Frame(fin=True, opcode=9, data=b'\xfb\xee\x18\x03', rsv1=False, rsv2=False, rsv3=False)
DEBUG websockets.protocol: client ! timed out waiting for pong
DEBUG websockets.protocol: client ! failing WebSocket connection in the OPEN state: 1011 [no reason]
DEBUG websockets.protocol: client - state = CLOSING
DEBUG websockets.protocol: client > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
```

It seems that the websockets timed out waiting for pong and I'm assuming that the connection closed afterwards. So the issue might be the heartbeat that keeps slack socket open. 

Any idea how to handle this from out end? 🤔

**Comment by jseiser** [comment]
Running into the same issue.  Opsdroid will either disconect from slack, or will die and restart.  All skills are using the slack connector, no cron jobs.  I had set the limit to 2GB, went in and uncapped it, and the same thing would happen, but it would eat up 4.5 GB.

![OpsdroidMemory](https://user-images.githubusercontent.com/4855527/63108703-840bc500-bf55-11e9-9627-485199a1d586.png)
