### ISSUE TITLE
Refactor Tests: Replace logmock with self.assertLogs

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#748]
Last year I needed to figure out how to assert if a logging level was called. I tried a few things and came up with the solution to mock the `_LOGGER.<level>` and then assert if logmock was called. 

I have noticed that you can use a `self.assertLogs(self, logger, level)` to check if a message was logged. Since when we are testing we don't really care about what message was logged but if the message was logging we should replace every `amock.patch('opsdroid.core._LOGGER.exception') as logmock` with the `self.assertLogs`.

This should make the tests a bit more readable and easier to maintain in the future. This Issue is also great for new contributors since it's quite easy to implement.

For a better explanation check the example:

_Old style:  test_main.py:132-136_
```python
    def test_welcome_message(self):
        config = {"welcome-message": True}
        with mock.patch('opsdroid.__main__._LOGGER.info') as logmock:
            opsdroid.welcome_message(config)
            self.assertTrue(logmock.called)

```

_Refactored test_
```python
    def test_welcome_message(self):
        config = {"welcome-message": True}
        opsdroid.welcome_message(config)
        self.assertLogs('_LOGGER', 'info')
```

If you need any help with this issue make sure to check out [gitter channel](https://gitter.im/opsdroid/general).

**Comment by jacobtomlinson** [comment]
Awesome! Looks like this was added to unittests in 3.4 (back in Feb).
