### ISSUE TITLE
Add mypy types

### ISSUE THREAD

**Issue by drmorr0** [opsdroid/opsdroid#756]
# Description
Let's add mypy types to opsdroid so that skills and other extensions using mypy can take advantage of type annotations.

**Comment by jacobtomlinson** [comment]
I've not come across mypy. Is this related to #639? Or are you proposing something else?

**Comment by jacobtomlinson** [comment]
Ok sure. I'm going to close this as a duplicate of that one. 

I would appreciate if you could have a read of that issue and join the discussion. Any code style change like this needs to be debated by the community, and the more input the better.
