### ISSUE TITLE
Support setuptools entry points for loading contributed extensions

### ISSUE THREAD

**Issue by petri** [opsdroid/opsdroid#767]
It is not desirable to have every contributed extension in the opsdroid core.

By supporting a loader mechanism that uses setuptools entry points, it becomes easy for contributors to maintain extensions as proper Python packages and publish them in PyPI.

The existing existing GitHub loader mechanism can of course be kept as-is; the two mechanisms are complementary.

**Comment by petri** [comment]
The entry points could be called simply `opsdroid_connectors`, `opsdroid_skills` and `opsdroid_databases`.

Someone contributing eg. a Skype connector in a package called eg. `opsdroid.contrib.skype` with a `connector.py` top-level module that has a `SkypeConnector` class, would then just need to add the following to setup.py:

```python
    entry_points = {
        'opsdroid_connectors': [
            'skype = opsdroid.contrib.skype.connector:SkypeConnector'
        ]
    },
```

**Comment by FabioRosado** [comment]
Just to clarify but this will add another thing that we will have to add to configure out opsdroid right?
So we would have to change `config.yaml` plus add the `entry_points` dict into setup.py as well?

**Comment by petri** [comment]
@FabioRosado no, the `entry_points` dict needs to be added just to the contributed proper Python packages.

**Comment by FabioRosado** [comment]
Oh that's great then, I didn't know much about that. Thanks for clarifying this. 

It sounds like a great way to keep opsdroid "small" again 👍

**Comment by jacobtomlinson** [comment]
This does sound good. I'm very keen to keep official supported modules in the core of opsdroid, they are not particularly big, many do not invoke additional dependencies and it makes testing and maintenance easier.

This could be a great way to support 3rd party connectors. However I'm not sure I see much difference between simply releasing a connector package to PyPI and configuring it with the new `module` config option added in #755.

**Comment by petri** [comment]
> > It is not desirable to have every contributed extension in the opsdroid core.
> 
> This is a broad statement. Could you give your reasoning for this?
> 
More code means more maintenance and more dependencies that may have platform-specific installation issues and so on. Some extensions may be obscure. 

The "batteries included" slogan comes at a price.

> I'm very keen to keep official supported modules in the core of opsdroid, they are not particularly big, many do not invoke additional dependencies (especially after #766) and it makes testing and maintenance easier.
> 

Yes #766 alleviates some of those issues and there is a mostly one-time packaging overhead, that's true as well.  Package management for testing & maintenance is not that much more work with modern Python tools I think, and on the other hand, it would become easier to make releases to just the core vs. those connectors/skills/database extensions that have fixes/improvements. 

But  digress - there's both pro's and cons to be sure. 

> This could be a great way to support 3rd party modules, particularly skills. I'm keen to eventually move away from the GitHub mode of installation to something more robust. However I'm not sure I see much difference between simply releasing a connector package to PyPI and configuring it with the new `module` config option added in #755.

That's a nice addition. The improvement provided by the entry point use is automatization and user convenience. Named entry points can be queried for by opsdroid so it will know what (named) connector/skill/database extensions user has installed. The opsdroid user thus does not need to specify a path or module; the name is enough.

**Comment by jacobtomlinson** [comment]
> More code means more maintenance and more dependencies that may have platform-specific installation issues and so on. Some extensions may be obscure.

Yes I agree. However opsdroid really doesn't have much code. It's a pretty simple package, the majority of the interesting stuff happens in the parsers, connectors and databases. I want to keep things simple for new users but extensible for advanced users. Therefore I would like to provide enough modules in the core to hit 80% of use cases, and then the rest can work through 3rd party libraries.

> The opsdroid user thus does not need to specify a path or module; the name is enough.

That would simplify things. Sounds good.

**Comment by petri** [comment]
completed, closing
