### ISSUE TITLE
Create a ZODB database extension

### ISSUE THREAD

**Issue by petri** [opsdroid/opsdroid#768]
I am working on this, just added issue for reference.

For ZODB docs, see http://www.zodb.org/en/latest/

**Comment by jacobtomlinson** [comment]
Nice thanks!

**Comment by petri** [comment]
See https://github.com/koodaamo/opsdroid-zodb. Also on PyPI.

**Comment by jacobtomlinson** [comment]
This is great thanks. Please feel free to put in a PR to the documentation in this project with install instructions and links to that module's documentation.
