### ISSUE TITLE
support providing an access token in the configuration for the matrix connector rather than the password

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#813]
This would alleviate the need to plain text the password in the config, and the access token can be deactivated. This would be a case of detecting the key in the config and skipping the login call

**Comment by FabioRosado** [comment]
Could you create a PR with the changes that have been merged into your fork? Seems like a nice thing to add 😄

**Comment by Cadair** [comment]
There is / was one

**Comment by FabioRosado** [comment]
Erm... yeah you are right! Ignore me 😬

**Comment by jacobtomlinson** [comment]
Would be good to get some progress on that. Looks like the change is done, just needs tests and docs.

**Comment by FabioRosado** [comment]
I am going to write tests for it and docs. Will create a PR later today hopefully 😄

**Comment by FabioRosado** [comment]
Just submitted a PR. Tox showed that the coverage was 100% hopefully it will work and we can merge the PR 😄
