### ISSUE TITLE
Regression: Add support for m.notice messages on a room-by-room basis

### ISSUE THREAD

**Issue by colonelkrud** [opsdroid/opsdroid#852]
Re-add support for m.notice like in separate connector listed below. Will also need to update docs to show send_m_notice config.

https://github.com/opsdroid/connector-matrix/commit/dba9088e96529c860231978f135af26067a2157b

https://github.com/opsdroid/opsdroid/blob/b98e2a9713088cafe13b9802f465d78db142b9af/opsdroid/connector/matrix/connector.py#L213

**Comment by Cadair** [comment]
It seems to be this: https://github.com/opsdroid/connector-matrix/commit/dba9088e96529c860231978f135af26067a2157b commit which never made it into core.

**Comment by jacobtomlinson** [comment]
@Cadair @SolarDrew do you have any interest in picking this up?

**Comment by SolarDrew** [comment]
Interest, yes, but not much time at the moment I'm afraid.
