### ISSUE TITLE
Pass botname to trigger skills or parse messages

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#864]
This has been suggested in the past and I have started thinking about this matter after @iobreaker mentioned it in issue #840. A few users have asked how to trigger a skill by using the botname, at the moment the workaround this issue is simply creating a regex rule containing `botname <text>` in order to get the skill to trigger.

This issue is meant to raise the discussion on this matter. 

Should we add a sort of flag in the `config.yaml` to only parse messages if the botname was used?  Or should we keep things as it is?

**Comment by iobreaker** [comment]
I think it's is more secure to pass in **public** rooms the name of the bot like

``
@SuperBot find wheater for paris
``

or just add a sign at the beginning of the phrase like 

``
 !find wheater for paris

or

;find wheater for paris
``

In private room this can be ignored

**Comment by jacobtomlinson** [comment]
This looks like it might be a duplicate of #273.
