### ISSUE TITLE
Handle user authorisation for skill interaction

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#865]
_This issue was suggested by @iobreaker on issue #849 - the talks were placed here so I could close the other issue._

Opsdroid should manage user authorisation outside skills or connectors. An example in configuration could be stored in sections like such:

```yaml
admin_users:
  - user1
  - user2

admin_skills:
  - skill1
  - skill2
```

Iobreaker suggests that the rules could be basic:

- Skills under admin_skill can only be executed by admins in private rooms (not public rooms)
- Other skills can be executed by all users (admins included) unless the skill manages its own admin list.

Jacob mentioned that we could implement this with constraints. We could add a `@constrain_admin` then this constraint could be used within skills - we could mark a skill as an admin skill in the config (the constraint would be added automatically)

According to iobreaker this modification could bring the ability to opsdroid admins to remotely issue private commands like:
- Get skills info
- Install skills
- Remove skills
- Disable skills
- Get X lines of skill's log
- Reload opsdroid config
- Get private/admin stats
- Get X lines of opsdroid logs
- Add authorization
- Remove Authorization
- Activate/deactivate connectors

**Comment by iobreaker** [comment]
What do you think about this ?

**Comment by colonelkrud** [comment]
How would we identify an admin across multiple connectors? Nicknames are not reliable as admin identification. We would need a UUID that can be reliably verified on each connector.

**Comment by FabioRosado** [comment]
I did raise this to iobreaker when we discussed the issue. The only way to keep things secure and avoid people from abusing the rules by changing the username, so we would need to get the user id from the connector and check if the userid == to the one in the config, if it is then parse the message. If not then ignore it.
