### ISSUE TITLE
Slack attachment support

### ISSUE THREAD

**Issue by brycearden** [opsdroid/opsdroid#878]
Is there any support for sending [slack attachment(s)](https://api.slack.com/docs/message-attachments) in opsdroid? I found [this open issue](https://github.com/opsdroid/connector-slack/issues/13) on the [connector-slack](https://github.com/opsdroid/connector-slack) project but can't seem to find any new information on additional support for attachments since the `connector-slack` project was deprecated.

**Comment by FabioRosado** [comment]
We have just merged event types to opsdroid, perhaps slack attachments could be supported easier with them, but so far the slack connector doesn't support them.  Would be good to update the slack connector to support this feature, would you like to work on it?

**Comment by brycearden** [comment]
I could probably take a look at it. Maybe something like `message.respond_with_json(dict)` might be the easiest route? That way users could take advantage of any json api's provided by a backend (i.e. not just the `slack-connector`).

**Comment by jacobtomlinson** [comment]
The way we handle events has changed dramatically. It might be useful for @Cadair to give some thoughts on how you imagine this specific example working?

**Comment by Cadair** [comment]
That's an interesting question that I haven't really considered. The events structure is well suited to having an event type for each of the attachments individually. I wonder if it would be worth having a collection event which could pass a group of events to the connector together and then the slack connector could represent them as attachments?

**Comment by jseiser** [comment]
Has there been any update on this?  If I could somehow format my slack messages it would greatly improve my end users interactions.

**Comment by FabioRosado** [comment]
The events have been merged and Jacob has a ongoing PR that will implement sending images and files so this will be done in the future.

Slack is a bit funny with permissions so things need to be tested and such

**Comment by jacobtomlinson** [comment]
> If I could somehow format my slack messages it would greatly improve my end users interactions.
What do you mean by this?

**Comment by jseiser** [comment]
Most of our skills, are just interacting with rest API's, returning JSON back to opsdroid.  Something like 'list inventories in Ansible AWX Dev', and returning data like 

`{3: 'xxx-automation-aws-inventory', 2: 'xxx-automation-ent-dev-Inventory'}`


Its ugly, and hard to read, especially as the results get longer and longer.  If we supported attachments, i could use each key/value pair as a field in the attachment.

**Comment by FabioRosado** [comment]
As a work around you could read the Json and Post the changed message

**Comment by jseiser** [comment]
@FabioRosado 

I dont follow.

**Comment by jacobtomlinson** [comment]
I'm interested in why you are sending the JSON object back to the chat client. I would've thought you would decode the response and extract the bits you want to show to the user. Alternatively you could pretty format the JSON and return it within code fences.

**Comment by jacobtomlinson** [comment]
Also looks like Slack are [transitioning from attachments to blocks](https://api.slack.com/messaging/attachments-to-blocks).

**Comment by FabioRosado** [comment]
Like Jacob said I meant that you could perhaps decode the Json object and transform it into a more readable format.

The blocks seem interesting but like it says in the docs we might need to rethink how to implement things with slack.

**Comment by jacobtomlinson** [comment]
I started having a quick hack to look at implementing this and it looks like we will need to fix `aioslacker` first as it seems to be out of date with the Slack API.

```
TypeError: post_message() got an unexpected keyword argument 'blocks'
```

https://api.slack.com/methods/chat.postMessage

**Comment by FabioRosado** [comment]
Did we created our own fork is aioslacker or was it of something else?

**Comment by jseiser** [comment]
Im an idiot.  I was attempting to send things, like I would direct to the slack client.  I never even though to just build up a string, with the proper concatenations to format the message.

```
        return_text = f"*{environment} - Accounts*\n"
        for account in accounts:
            return_text = f"{return_text}```ID: {account['id']} Name: {account['name']} Status: {account['status']}```\n"
        await message.respond(f"{return_text}")
```

Works fine.

**Comment by jacobtomlinson** [comment]
> Im an idiot.

Don't put yourself down! Could we improve the docs or add examples to help other people avoid these assumptions?
