### ISSUE TITLE
Add http&https proxy support

### ISSUE THREAD

**Issue by diluga** [opsdroid/opsdroid#884]
it that any plan to Add http&https proxy support?

**Comment by jacobtomlinson** [comment]
Sure! Is this something you feel like you could contribute?

**Comment by cupen** [comment]
@diluga  Is this what you want?
```bash
$ export http_proxy=xx.xx.xx.xx:1080
$ export https_proxy=xx.xx.xx.xx:1080
$ opsdroid
```

**Comment by diluga** [comment]
> @diluga Is this what you want?
> 
> ```shell
> $ export http_proxy=xx.xx.xx.xx:1080
> $ export https_proxy=xx.xx.xx.xx:1080
> $ opsdroid
> ```

yes~

**Comment by cupen** [comment]
@diluga so…… is it done?  ;p

**Comment by diluga** [comment]
thx~

**Comment by jacobtomlinson** [comment]
This has not been done. It is available to be picked up.

**Comment by martingoldstone** [comment]
I'd be happy to take a look at this

**Comment by jacobtomlinson** [comment]
@martingoldstone that would be great thanks!
