### ISSUE TITLE
Matrix Sync Error called by asyncio.TimeoutError

### ISSUE THREAD

**Issue by colonelkrud** [opsdroid/opsdroid#904]
Most web servers do not have a TimeOut of 6 hours. Apache2 ships with a 300 second timeout. We should either lower this value to something under 300 seconds or deal with timeout errors without calling `ERROR opsdroid.connector.matrix.connector: Matrix Sync Error` every 5 minutes (300 seconds). 

https://github.com/opsdroid/opsdroid/blob/11508b513ea563a58fc95581b7032256449c65c1/opsdroid/connector/matrix/connector.py#L139

**Comment by Cadair** [comment]
Yeah we should drop this, 300s sounds sensible.

**Comment by paw39** [comment]
Hi! Can I fix it as my first issue? :)

**Comment by FabioRosado** [comment]
Hello Pawel yeah you can tackle the issue, let us know if you need any help 👍

**Comment by paw39** [comment]
How can I simply test it after change this timeout? Description from main page of this repo will be good?

**Comment by paw39** [comment]
Or maybe I don't have to? :) Just change this value.

**Comment by Cadair** [comment]
this can be closed now :smile:

**Comment by FabioRosado** [comment]
Haha oops I forgot to check if the PR would close the issue thanks for the call Cadair 😄
