### ISSUE TITLE
Docker build is failing

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#923]
The Docker builds are failing due to timeout (no action for over 10minutes). The PR raised by @anxodio  errored on `Step 3/16 : RUN mkdir -p /usr/src/app` after I have restarted the build the docker build failed on `(1/5) Installing nghttp2-libs (1.35.1-r0)`

This is the error message:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

Not sure if this is something related to the [docker breach](https://thehackernews.com/2019/04/docker-hub-data-breach.html) or not.

**Comment by jacobtomlinson** [comment]
I don't think this is related to the breach. 

It looks like something in the build is going funny and stopping. The error is travis just cleaning up the jobs. 

I've triggered it again in case it was a transient Travis issue. Let's see what happens.

**Comment by FabioRosado** [comment]
I guess it was a travis issue then since now all docker tests are passing 😄 👍  
I am going to close this issue since it doesn't seem to apply anymore
