### ISSUE TITLE
AppVeyor failing on Python 3.5

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#941]
It looks like tests on Python 3.5 on AppVeyor have started failing. This seems to be due to the version of python being executed in tox not being the expected version.

**Comment by jacobtomlinson** [comment]
Made optional for now to unblock builds.

**Comment by FabioRosado** [comment]
Do you think this is something related to aiosqlite?

**Comment by jacobtomlinson** [comment]
Maybe?

**Comment by NanduTej** [comment]
Hey! Can I give this a try?

**Comment by FabioRosado** [comment]
Hey @NanduTej that would be great 😄 👍

**Comment by NanduTej** [comment]
> Hey @NanduTej that would be great smile +1

Thank you! So basically as far as I understood, appveyor is used for building the app and the tests for python 3.5 are failing in this. We have to figure out why. Is this right?

**Comment by FabioRosado** [comment]
Yeah that's pretty much it. I believe that the issue might be somewhere with the aiosqlite but if you can test 3.5 you can check the error log and see if its indeed coming from there or not

**Comment by NanduTej** [comment]
Hey! I ran the app on a python 3.5 virtual environment. The result I got was:

py35: commands succeeded
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
lint: commands succeeded
docker: commands succeeded

I followed only the commands mentioned in the contributor's guide. So maybe there is an issue on appveyor. Does that sound right? If yes, can you guide as to how I could test it there?

**Comment by jacobtomlinson** [comment]
Thanks for checking this out @NanduTej. I'm afraid none of us are that familiar with AppVeyor and probably wont be able to provide much assistance with this one. My recommendation would be to check out the AppVeyor documentation.

**Comment by NanduTej** [comment]
> Yeah that's pretty much it. I believe that the issue might be somewhere with the aiosqlite but if you can test 3.5 you can check the error log and see if its indeed coming from there or not

Hey! I realized I made some mistakes yesterday. You were right about this coming from aiosqlite. When running the tox command and while setting up the requirements, it fail at the aiosqlite part.

**Comment by jacobtomlinson** [comment]
Python 3.5 support has been removed in #960.
