### ISSUE TITLE
Add Snips NLU parser and matcher

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#982]
Add a parser and matcher for [Snips NLU](https://github.com/snipsco/snips-nlu).

Parser would need to call to the Snips NLU api and get back a response to set the intent and entities of an `Event`.

**Comment by himanshupathak21061998** [comment]
I want to work on this for `hacktoberfest`.

**Comment by FabioRosado** [comment]
Please feel free to work on this issue, let us know if you encounter any issues 👍

**Comment by daniccan** [comment]
Is anyone working on this? Can I pick it up? @himanshupathak21061998 @FabioRosado

**Comment by jacobtomlinson** [comment]
Things seem quiet here. Please go ahead @daniccan.

**Comment by himanshupathak21061998** [comment]
Hey @daniccan I am working on this. @jacobtomlinson actually I was not familiar with snips nlu that's why I started learning now I am getting a bit understanding of it. Sorry for delay just give me some time to complete the pr

**Comment by jacobtomlinson** [comment]
Ah ok sorry @himanshupathak21061998, you've just been silent on this for nearly a month.

Do you have an idea of when you'll get to this?

**Comment by himanshupathak21061998** [comment]
Give me atmost 4 days by the time I will complete this.

**Comment by himanshupathak21061998** [comment]
@jacobtomlinson I think we need to close this.

**Comment by jacobtomlinson** [comment]
Yeah, it's a real shame!
