### ISSUE TITLE
Add support for end to end encryption in Matrix Connector

### ISSUE THREAD

**Issue by awesome-michael** [opsdroid/opsdroid#992]
I tried opsdroid in a docker container to connect to a matrix server. So far everything works fine. But I realized that opsdroid does react in unencrypted rooms only. I assume that there is no end-to-end-encryption support built in the matrix connector. Is there a possibility to enable encryption in opsdroid?

**Comment by jacobtomlinson** [comment]
cc @Cadair @SolarDrew

**Comment by Cadair** [comment]
It's something I want to add, but I am unlikely to have time in the near future. To do it we need to change the underlying matrix library. 

In the short term if you want to use opsdroid in encrypted rooms the best thing would be to use https://github.com/matrix-org/pantalaimon which is an e2ee proxy.

**Comment by jacobtomlinson** [comment]
Is there anything we can do in opsdroid in the short term to warn users about this? Perhaps detect the room is encrypted and log a warning message.

**Comment by Cadair** [comment]
We could emit a warning if we receive encrypted events, would be easier to detect than rooms.

**Comment by Cadair** [comment]
The way I propose we would fix this, is change the underlying layer of the matrix connector to use [matrix-nio](https://github.com/poljar/matrix-nio) which is a more actively maintained Python library, and has built in support for asyncio.

For more details on using `matrix-nio` there is this: https://matrix.org/docs/guides/usage-of-matrix-nio guide.

**Comment by jacobtomlinson** [comment]
🎉
